from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent.parent

RUNTIME_PROBES = []

DIAG_PROBES = []

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_complex_lt_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_complex_lt_reject.c',
        note="diagnostics JSON should include semantic relational-complex rejection for '<'",
        expected_codes=[2000],
        expected_line=4,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_complex_le_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_complex_le_reject.c',
        note="diagnostics JSON should include semantic relational-complex rejection for '<='",
        expected_codes=[2000],
        expected_line=4,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_complex_gt_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_complex_gt_reject.c',
        note="diagnostics JSON should include semantic relational-complex rejection for '>'",
        expected_codes=[2000],
        expected_line=4,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_complex_ge_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_complex_ge_reject.c',
        note="diagnostics JSON should include semantic relational-complex rejection for '>='",
        expected_codes=[2000],
        expected_line=4,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_continue_outside_loop_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_continue_outside_loop_reject.c',
        note='diagnostics JSON should include control-flow rejection for continue outside loop',
        expected_codes=[2000],
        expected_line=3,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_break_outside_loop_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_break_outside_loop_reject.c',
        note='diagnostics JSON should include control-flow rejection for break outside loop/switch',
        expected_codes=[2000],
        expected_line=3,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_case_outside_switch_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_case_outside_switch_reject.c',
        note='diagnostics JSON should include control-flow rejection for case outside switch',
        expected_codes=[1000],
        expected_line=2,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_default_outside_switch_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_default_outside_switch_reject.c',
        note='diagnostics JSON should include control-flow rejection for default outside switch',
        expected_codes=[1000],
        expected_line=2,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_switch_duplicate_default_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_switch_duplicate_default_reject.c',
        note='diagnostics JSON should include duplicate default-label rejection',
        expected_codes=[2000],
        expected_line=9,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_switch_duplicate_case_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_switch_duplicate_case_reject.c',
        note='diagnostics JSON should include duplicate case-label rejection',
        expected_codes=[2000],
        expected_line=8,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_switch_nonconst_case_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_switch_nonconst_case_reject.c',
        note='diagnostics JSON should include non-constant case-label rejection',
        expected_codes=[2000],
        expected_line=6,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_continue_in_switch_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_continue_in_switch_reject.c',
        note='diagnostics JSON should include continue-in-switch rejection diagnostic',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_fnptr_table_too_many_args_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_fnptr_table_too_many_args_reject.c',
        note='diagnostics JSON should include fnptr too-many-args rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_fnptr_table_incompatible_assign_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_fnptr_table_incompatible_assign_reject.c',
        note='diagnostics JSON should include fnptr incompatible-assignment rejection',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_fnptr_table_incompatible_signature_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_fnptr_table_incompatible_signature_reject.c',
        note='diagnostics JSON should include fnptr incompatible-initializer-signature rejection',
        expected_codes=[2000],
        expected_line=4,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_fnptr_struct_arg_incompatible_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_fnptr_struct_arg_incompatible_reject.c',
        note='diagnostics JSON should include fnptr incompatible-struct-argument rejection',
        expected_codes=[2000],
        expected_line=12,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_fnptr_param_noncallable_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_fnptr_param_noncallable_reject.c',
        note='diagnostics JSON should include fnptr non-callable argument rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_file_scope_vla_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_vla_non_integer_bound_reject.c',
        note='diagnostics JSON should include file-scope VLA static-duration rejection',
        expected_codes=[2000],
        expected_line=2,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_offsetof_bitfield_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_offsetof_bitfield_reject.c',
        note='diagnostics JSON should include offsetof bitfield rejection',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_ternary_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_ternary_struct_condition_reject.c',
        note='diagnostics JSON should include ternary struct-condition rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_fnptr_table_too_few_args_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_fnptr_table_incompatible_assign_reject.c',
        note='diagnostics JSON should include fnptr too-few-args rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_switch_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_switch_struct_condition_reject.c',
        note='diagnostics JSON should include switch non-integer condition rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_if_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_if_struct_condition_reject.c',
        note='diagnostics JSON should include if non-scalar condition rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_while_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_while_struct_condition_reject.c',
        note='diagnostics JSON should include while non-scalar condition rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_return_struct_to_int_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_return_struct_to_int_reject.c',
        note='diagnostics JSON should include return-type mismatch rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_multitu_duplicate_external_definition_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_external_definition_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU duplicate external definition link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_external_definition_reject_main.c', PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_external_definition_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_multitu_extern_type_mismatch_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_multitu_extern_type_mismatch_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU extern-type mismatch link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/14__probe_diag_multitu_extern_type_mismatch_reject_main.c', PROBE_DIR / 'diagnostics/14__probe_diag_multitu_extern_type_mismatch_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_multitu_duplicate_tentative_type_conflict_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_tentative_type_conflict_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU tentative-definition type conflict link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_tentative_type_conflict_reject_main.c', PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_tentative_type_conflict_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_multitu_duplicate_function_definition_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_function_definition_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU duplicate function definition link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_function_definition_reject_main.c', PROBE_DIR / 'diagnostics/14__probe_diag_multitu_duplicate_function_definition_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_axis2_wave2_line_map_nested_include_macro_guard_reentry_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_axis2_wave2_line_map_nested_include_macro_guard_reentry_reject.c',
        note='axis2 wave2: diagnostics JSON should preserve deep line/file presence for nested include+macro guard reentry #line remap lane',
        expected_codes=[2000],
        expected_line=240308,
        expected_column=9,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_axis2_wave3_line_map_nested_include_macro_type_bridge_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_axis2_wave3_line_map_nested_include_macro_type_bridge_reject.c',
        note='axis2 wave3: diagnostics JSON should preserve deep line/file presence for four-layer include+macro type-bridge #line remap lane',
        expected_codes=[2000],
        expected_line=240697,
        expected_column=37,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='14__probe_diagjson_axis2_wave4_line_map_nested_include_macro_arity_overflow_reject',
        source=PROBE_DIR / 'diagnostics/14__probe_diag_axis2_wave4_line_map_nested_include_macro_arity_overflow_reject.c',
        note='axis2 wave4: diagnostics JSON should preserve deep line/file presence for five-layer include+macro arity-overflow #line remap lane',
        expected_codes=[2000],
        expected_line=320897,
        expected_column=32,
        expected_has_file=True,
    ),
]
