from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='14__probe_multitu_static_init_visibility_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_init_visibility_bridge_main.c',
        note='multi-TU static local + file-static visibility bridge should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_init_visibility_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_visibility_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_vla_param_nested_handoff_matrix',
        source=PROBE_DIR / 'runtime/14__probe_vla_param_nested_handoff_matrix.c',
        note='VLA nested parameter handoff matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_vla_stride_rebind_cross_fn_chain',
        source=PROBE_DIR / 'runtime/14__probe_vla_stride_rebind_cross_fn_chain.c',
        note='VLA stride rebind across helper-function chain should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_vla_ptrdiff_cross_scope_matrix',
        source=PROBE_DIR / 'runtime/14__probe_vla_ptrdiff_cross_scope_matrix.c',
        note='VLA ptrdiff cross-scope matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_intptr_roundtrip_offset_matrix',
        source=PROBE_DIR / 'runtime/14__probe_intptr_roundtrip_offset_matrix.c',
        note='intptr_t pointer roundtrip offset matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_uintptr_mask_rebase_matrix',
        source=PROBE_DIR / 'runtime/14__probe_uintptr_mask_rebase_matrix.c',
        note='uintptr_t mask/rebase reconstruction matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_ptrdiff_boundary_crosscheck_matrix',
        source=PROBE_DIR / 'runtime/14__probe_ptrdiff_boundary_crosscheck_matrix.c',
        note='ptrdiff_t boundary crosscheck matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_variadic_llong_double_bridge',
        source=PROBE_DIR / 'runtime/14__probe_variadic_llong_double_bridge.c',
        note='variadic long-long/double width bridge should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_control_do_while_switch_phi_chain',
        source=PROBE_DIR / 'runtime/14__probe_control_do_while_switch_phi_chain.c',
        note='do-while + switch + continue/goto phi paths should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_struct_array_double_by_value_roundtrip',
        source=PROBE_DIR / 'runtime/14__probe_struct_array_double_by_value_roundtrip.c',
        note='struct with array+double by-value roundtrip should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_vla_dim_recompute_stride_matrix',
        source=PROBE_DIR / 'runtime/14__probe_vla_dim_recompute_stride_matrix.c',
        note='VLA dimension recompute and stride matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_pointer_byte_rebase_roundtrip_matrix',
        source=PROBE_DIR / 'runtime/14__probe_pointer_byte_rebase_roundtrip_matrix.c',
        note='pointer byte-rebase roundtrip and element ptrdiff scaling should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_float_nan_inf_order_chain',
        source=PROBE_DIR / 'runtime/14__probe_float_nan_inf_order_chain.c',
        note='NaN/infinity ordering and comparison chain should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_header_null_ptrdiff_bridge',
        source=PROBE_DIR / 'runtime/14__probe_header_null_ptrdiff_bridge.c',
        note='header NULL + ptrdiff bridge semantics should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_struct_union_array_overlay_roundtrip',
        source=PROBE_DIR / 'runtime/14__probe_struct_union_array_overlay_roundtrip.c',
        note='struct+union+array by-value roundtrip overlay should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_variadic_long_width_crosscheck',
        source=PROBE_DIR / 'runtime/14__probe_variadic_long_width_crosscheck.c',
        note='variadic long/unsigned-long/long-long width crosscheck should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_struct_ternary_by_value_select_chain',
        source=PROBE_DIR / 'runtime/14__probe_struct_ternary_by_value_select_chain.c',
        note='struct ternary by-value selection chain should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_header_offsetof_nested_matrix',
        source=PROBE_DIR / 'runtime/14__probe_header_offsetof_nested_matrix.c',
        note='nested offsetof header surface should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_switch_sparse_signed_case_ladder',
        source=PROBE_DIR / 'runtime/14__probe_switch_sparse_signed_case_ladder.c',
        note='sparse signed switch case ladder should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_bitwise_compound_recurrence_matrix',
        source=PROBE_DIR / 'runtime/14__probe_bitwise_compound_recurrence_matrix.c',
        note='bitwise compound recurrence matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_bool_scalar_conversion_matrix',
        source=PROBE_DIR / 'runtime/14__probe_bool_scalar_conversion_matrix.c',
        note='scalar-to-bool conversion matrix across int/float/pointer lanes should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_bitfield_signed_promotion_matrix',
        source=PROBE_DIR / 'runtime/14__probe_bitfield_signed_promotion_matrix.c',
        note='signed bitfield promotion/update matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_bitfield_compound_assign_bridge',
        source=PROBE_DIR / 'runtime/14__probe_bitfield_compound_assign_bridge.c',
        note='unsigned bitfield compound update bridge should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_bitfield_bool_bridge_matrix',
        source=PROBE_DIR / 'runtime/14__probe_bitfield_bool_bridge_matrix.c',
        note='bitfield and bool bridge paths should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_fnptr_table_state_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_fnptr_table_state_bridge_main.c',
        note='multi-TU function-pointer table state bridge should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_fnptr_table_state_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_fnptr_table_state_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_variadic_fold_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_variadic_fold_bridge_main.c',
        note='multi-TU mixed-width fold bridge should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_variadic_fold_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_variadic_fold_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_vla_window_reduce_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_vla_window_reduce_bridge_main.c',
        note='multi-TU VLA window reduction bridge should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_vla_window_reduce_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_vla_window_reduce_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_struct_union_route_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_struct_union_route_bridge_main.c',
        note='multi-TU struct/union route bridge should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_struct_union_route_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_struct_union_route_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_control_switch_do_for_state_machine',
        source=PROBE_DIR / 'runtime/14__probe_control_switch_do_for_state_machine.c',
        note='control-flow state machine across for/do/switch should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_layout_offset_stride_bridge',
        source=PROBE_DIR / 'runtime/14__probe_layout_offset_stride_bridge.c',
        note='layout offsetof/stride bridge should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_pointer_stride_rebase_control_mix',
        source=PROBE_DIR / 'runtime/14__probe_pointer_stride_rebase_control_mix.c',
        note='pointer-stride rebasing with mixed control flow should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_bool_bitmask_control_chain',
        source=PROBE_DIR / 'runtime/14__probe_bool_bitmask_control_chain.c',
        note='bool-bitmask control chain should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_smoke_expr_eval_driver',
        source=PROBE_DIR / 'runtime/14__probe_smoke_expr_eval_driver.c',
        note='deterministic expression-evaluator mini-driver should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_smoke_dispatch_table_driver',
        source=PROBE_DIR / 'runtime/14__probe_smoke_dispatch_table_driver.c',
        note='deterministic function-pointer dispatch mini-driver should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_smoke_multitu_config_driver',
        source=PROBE_DIR / 'runtime/14__probe_smoke_multitu_config_driver_main.c',
        note='deterministic multi-TU config mini-driver should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_smoke_multitu_config_driver_main.c', PROBE_DIR / 'runtime/14__probe_smoke_multitu_config_driver_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_repeatable_output_hash_matrix',
        source=PROBE_DIR / 'runtime/14__probe_repeatable_output_hash_matrix.c',
        note='repeated same-input executions should produce stable runtime output hash matrix',
    ),
    RuntimeProbe(
        probe_id='14__probe_repeatable_diagjson_hash_matrix',
        source=PROBE_DIR / 'runtime/14__probe_repeatable_diagjson_hash_matrix.c',
        note='diagnostic-record modeling hash matrix should be stable across repeated builds',
    ),
    RuntimeProbe(
        probe_id='14__probe_repeatable_multitu_link_hash_matrix',
        source=PROBE_DIR / 'runtime/14__probe_repeatable_multitu_link_hash_matrix_main.c',
        note='multi-TU link-path hash matrix should remain stable across repeated calls',
        inputs=[PROBE_DIR / 'runtime/14__probe_repeatable_multitu_link_hash_matrix_main.c', PROBE_DIR / 'runtime/14__probe_repeatable_multitu_link_hash_matrix_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_link_order_static_init_crc_matrix',
        source=PROBE_DIR / 'runtime/14__probe_multitu_link_order_static_init_crc_matrix_main.c',
        note='multi-TU static-init and call-order CRC matrix should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_link_order_static_init_crc_matrix_main.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_static_init_crc_matrix_lib_a.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_static_init_crc_matrix_lib_b.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_repeatable_multitu_symbol_permutation_hash',
        source=PROBE_DIR / 'runtime/14__probe_repeatable_multitu_symbol_permutation_hash_main.c',
        note='multi-TU symbol permutation dispatch hash should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_repeatable_multitu_symbol_permutation_hash_main.c', PROBE_DIR / 'runtime/14__probe_repeatable_multitu_symbol_permutation_hash_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_repeatable_runtime_stdout_hash_matrix',
        source=PROBE_DIR / 'runtime/14__probe_repeatable_runtime_stdout_hash_matrix.c',
        note='text-output hash matrix should remain deterministic across repeated runs and match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_abi_long_double_variadic_regstack_hardening',
        source=PROBE_DIR / 'runtime/14__probe_abi_long_double_variadic_regstack_hardening.c',
        note='long-double variadic ABI mix should be repeatable and match clang at reg/stack boundaries',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_static_init_order_depth_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_init_order_depth_bridge_main.c',
        note='multi-TU static init/order depth bridge should remain deterministic and match clang',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_init_order_depth_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_order_depth_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_static_init_replay_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_init_replay_mesh_main.c',
        note='multi-TU static-init replay mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_init_replay_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_replay_mesh_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_link_order_checkpoint_feedback',
        source=PROBE_DIR / 'runtime/14__probe_multitu_link_order_checkpoint_feedback_main.c',
        note='multi-TU link-order checkpoint feedback should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_link_order_checkpoint_feedback_main.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_checkpoint_feedback_lib_a.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_checkpoint_feedback_lib_b.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_link_order_resalt_feedback_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_mesh_main.c',
        note='multi-TU link-order resalt feedback mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_mesh_lib_a.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_mesh_lib_b.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_static_init_epoch_feedback_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_mesh_main.c',
        note='multi-TU static-init epoch feedback mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_mesh_lib_a.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_mesh_lib_b.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_link_order_resalt_feedback_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_braid_main.c',
        note='multi-TU link-order resalt feedback braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_mesh_lib_a.c', PROBE_DIR / 'runtime/14__probe_multitu_link_order_resalt_feedback_mesh_lib_b.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_static_init_epoch_feedback_weave',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_weave_main.c',
        note='multi-TU static-init epoch feedback weave should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_weave_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_mesh_lib_a.c', PROBE_DIR / 'runtime/14__probe_multitu_static_init_epoch_feedback_mesh_lib_b.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_import_collapse_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_import_collapse_bridge_main.c',
        note='multi-TU token-generation import-collapse bridge should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_import_collapse_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_latest_commit_collapse',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_commit_collapse_main.c',
        note='multi-TU reserve/latest-commit collapse bridge should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_commit_collapse_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_dual_slot_replay_fence',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_dual_slot_replay_fence_main.c',
        note='multi-TU token-generation dual-slot replay fence should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_dual_slot_replay_fence_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reseed_wave_collapse',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reseed_wave_collapse_main.c',
        note='multi-TU token-generation reseed-wave collapse should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reseed_wave_collapse_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_generation_reclaim_collapse',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_generation_reclaim_collapse_main.c',
        note='multi-TU reserve generation-reclaim collapse should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_generation_reclaim_collapse_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_wraparound_latest_wins',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_wraparound_latest_wins_main.c',
        note='multi-TU reserve wraparound latest-wins collapse should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_wraparound_latest_wins_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_import_order_latest_wins',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_import_order_latest_wins_main.c',
        note='multi-TU token-generation import-order latest-wins arbitration should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_import_order_latest_wins_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_peer_shadow_reseed_collapse',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_peer_shadow_reseed_collapse_main.c',
        note='multi-TU token-generation peer-shadow reseed collapse should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_peer_shadow_reseed_collapse_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_reclaim_latest_wins',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_reclaim_latest_wins_main.c',
        note='multi-TU reserve abort-reclaim latest-wins collapse should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_reclaim_latest_wins_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_commit_reimport_collapse',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_commit_reimport_collapse_main.c',
        note='multi-TU reserve shadow-commit reimport collapse should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_commit_reimport_collapse_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_cross_slot_shadow_elimination',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_cross_slot_shadow_elimination_main.c',
        note='multi-TU token-generation cross-slot shadow elimination should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_cross_slot_shadow_elimination_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_shadow_recommit_handoff',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_recommit_handoff_main.c',
        note='multi-TU reserve abort-shadow recommit handoff should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_recommit_handoff_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reimport_wave_prune_latest',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_wave_prune_latest_main.c',
        note='multi-TU token-generation reimport-wave prune/latest arbitration should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_wave_prune_latest_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_wraparound_import_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wraparound_import_braid_main.c',
        note='multi-TU token-generation wraparound/import braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wraparound_import_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_reclaim_reimport_fence',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_reclaim_reimport_fence_main.c',
        note='multi-TU reserve shadow-reclaim reimport fence should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_reclaim_reimport_fence_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_wrap_shadow_recommit_latest',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_wrap_shadow_recommit_latest_main.c',
        note='multi-TU reserve wrap-shadow recommit latest-state arbitration should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_wrap_shadow_recommit_latest_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_wrap_latest',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_latest_main.c',
        note='multi-TU token-generation shadow-wrap latest-state braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_latest_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_reimport_abort_wrap_matrix',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_abort_wrap_matrix_main.c',
        note='multi-TU reserve reimport/abort wrap matrix should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_abort_wrap_matrix_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reimport_shadow_prune_wrap',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_shadow_prune_wrap_main.c',
        note='multi-TU token-generation reimport-shadow prune wrap should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_shadow_prune_wrap_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_latest_reimport_fanout',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_reimport_fanout_main.c',
        note='multi-TU token-generation latest reimport fanout should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_reimport_fanout_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_wrap_reclaim_matrix',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_wrap_reclaim_matrix_main.c',
        note='multi-TU reserve shadow-wrap reclaim matrix should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_wrap_reclaim_matrix_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_recommit_reimport_latest_chain',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_recommit_reimport_latest_chain_main.c',
        note='multi-TU reserve recommit/reimport latest chain should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_recommit_reimport_latest_chain_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_reimport_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_reimport_arc_main.c',
        note='multi-TU token-generation shadow reimport arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_reimport_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_wrap_shadow_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_wrap_shadow_arc_main.c',
        note='multi-TU reserve abort-wrap shadow arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_wrap_shadow_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_wrap_reimport_latest_spoke',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_reimport_latest_spoke_main.c',
        note='multi-TU token-generation wrap/reimport latest-state spoke should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_reimport_latest_spoke_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_fanout_wrap_chain',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_fanout_wrap_chain_main.c',
        note='multi-TU token-generation shadow-fanout wrap chain should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_fanout_wrap_chain_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_reclaim_wrap_latest_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_reclaim_wrap_latest_braid_main.c',
        note='multi-TU reserve shadow-reclaim wrap latest-state braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_reclaim_wrap_latest_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_reimport_shadow_abort_latest_fanout',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_shadow_abort_latest_fanout_main.c',
        note='multi-TU reserve reimport-shadow abort latest-state fanout should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_shadow_abort_latest_fanout_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_wrap_reimport_spoke',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_reimport_spoke_main.c',
        note='multi-TU token-generation shadow-wrap reimport spoke should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_reimport_spoke_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_shadow_reclaim_latest_spoke',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_reclaim_latest_spoke_main.c',
        note='multi-TU reserve abort-shadow reclaim latest-state spoke should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_reclaim_latest_spoke_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_latest_shadow_reimport_lattice',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_shadow_reimport_lattice_main.c',
        note='multi-TU token-generation latest-shadow reimport lattice should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_shadow_reimport_lattice_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_wrap_shadow_prune_fanout',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_shadow_prune_fanout_main.c',
        note='multi-TU token-generation wrap-shadow prune fanout should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_shadow_prune_fanout_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_latest_shadow_wrap_replay_lattice',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_wrap_replay_lattice_main.c',
        note='multi-TU reserve latest-shadow wrap replay lattice should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_wrap_replay_lattice_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_reimport_shadow_wrap_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_reimport_shadow_wrap_braid_main.c',
        note='multi-TU reserve abort-reimport shadow-wrap braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_reimport_shadow_wrap_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_latest_wrap_fanout',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_latest_wrap_fanout_main.c',
        note='multi-TU token-generation shadow-latest wrap fanout should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_latest_wrap_fanout_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_latest_abort_reclaim_chain',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_latest_abort_reclaim_chain_main.c',
        note='multi-TU reserve shadow-latest abort reclaim chain should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_latest_abort_reclaim_chain_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reimport_latest_shadow_spine',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_latest_shadow_spine_main.c',
        note='multi-TU token-generation reimport-latest shadow spine should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_latest_shadow_spine_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_wrap_shadow_latest_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_shadow_latest_arc_main.c',
        note='multi-TU token-generation wrap-shadow latest arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_shadow_latest_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_reimport_latest_shadow_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_latest_shadow_mesh_main.c',
        note='multi-TU reserve reimport-latest shadow mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_latest_shadow_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_wrap_latest_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_wrap_latest_arc_main.c',
        note='multi-TU reserve shadow-wrap latest arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_wrap_latest_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_reimport_latest_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_reimport_latest_braid_main.c',
        note='multi-TU token-generation shadow-reimport latest braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_reimport_latest_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_shadow_latest_weave',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_latest_weave_main.c',
        note='multi-TU reserve abort-shadow latest weave should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_latest_weave_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_latest_wrap_shadow_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_wrap_shadow_mesh_main.c',
        note='multi-TU token-generation latest-wrap shadow mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_wrap_shadow_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reimport_shadow_latest_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_shadow_latest_arc_main.c',
        note='multi-TU token-generation reimport-shadow latest arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_shadow_latest_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_latest_reimport_shadow_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_reimport_shadow_braid_main.c',
        note='multi-TU reserve latest-reimport shadow braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_reimport_shadow_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_abort_latest_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_abort_latest_arc_main.c',
        note='multi-TU reserve shadow-abort latest arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_abort_latest_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_wrap_latest_spine',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_latest_spine_main.c',
        note='multi-TU token-generation shadow-wrap latest spine should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_latest_spine_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_latest_shadow_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_latest_shadow_mesh_main.c',
        note='multi-TU reserve abort-latest shadow mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_latest_shadow_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_latest_reimport_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_latest_reimport_mesh_main.c',
        note='multi-TU token-generation shadow-latest reimport mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_latest_reimport_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_wrap_latest_shadow_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_latest_shadow_braid_main.c',
        note='multi-TU token-generation wrap-latest shadow braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_latest_shadow_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_latest_reimport_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_latest_reimport_arc_main.c',
        note='multi-TU reserve shadow-latest reimport arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_latest_reimport_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_latest_shadow_abort_braid',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_abort_braid_main.c',
        note='multi-TU reserve latest-shadow abort braid should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_abort_braid_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reimport_wrap_latest_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_wrap_latest_mesh_main.c',
        note='multi-TU token-generation reimport-wrap latest mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_wrap_latest_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_shadow_latest_lattice',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_latest_lattice_main.c',
        note='multi-TU reserve abort-shadow latest lattice should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_shadow_latest_lattice_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_latest_shadow_wrap_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_shadow_wrap_arc_main.c',
        note='multi-TU token-generation latest-shadow wrap arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_shadow_wrap_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_reimport_shadow_latest_lattice',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_shadow_latest_lattice_main.c',
        note='multi-TU token-generation reimport-shadow latest lattice should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_reimport_shadow_latest_lattice_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_latest_shadow_reimport_spine',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_reimport_spine_main.c',
        note='multi-TU reserve latest-shadow reimport spine should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_reimport_spine_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_wrap_latest_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_wrap_latest_mesh_main.c',
        note='multi-TU reserve shadow-wrap latest mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_wrap_latest_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_latest_wrap_lattice',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_latest_wrap_lattice_main.c',
        note='multi-TU token-generation shadow-latest wrap lattice should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_latest_wrap_lattice_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_abort_latest_shadow_spine',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_latest_shadow_spine_main.c',
        note='multi-TU reserve abort-latest shadow spine should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_abort_latest_shadow_spine_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_latest_reimport_shadow_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_reimport_shadow_arc_main.c',
        note='multi-TU token-generation latest-reimport shadow arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_latest_reimport_shadow_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_wrap_latest_shadow_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_latest_shadow_mesh_main.c',
        note='multi-TU token-generation wrap-latest shadow mesh should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_wrap_latest_shadow_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_latest_shadow_reclaim_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_reclaim_arc_main.c',
        note='multi-TU reserve latest-shadow reclaim arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_latest_shadow_reclaim_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_shadow_abort_latest_spine',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_abort_latest_spine_main.c',
        note='multi-TU reserve shadow-abort latest spine should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_shadow_abort_latest_spine_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_shadow_wrap_latest_lattice',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_latest_lattice_main.c',
        note='multi-TU token-generation shadow-wrap latest lattice should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_shadow_wrap_latest_lattice_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_reimport_latest_shadow_arc',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_latest_shadow_arc_main.c',
        note='multi-TU reserve reimport-latest shadow arc should remain deterministic and match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_reimport_latest_shadow_arc_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_queue_push_fail_preserves_committed_slot',
        source=PROBE_DIR / 'runtime/14__probe_queue_push_fail_preserves_committed_slot.c',
        note='queue push-fail path should preserve committed slot state and match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_generation_stale_drop',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_main.c',
        note='multi-TU token generation stale-drop path should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_generation_stale_drop_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_owner_transfer_release_once',
        source=PROBE_DIR / 'runtime/14__probe_multitu_owner_transfer_release_once_main.c',
        note='multi-TU owner-transfer release-once path should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_owner_transfer_release_once_main.c', PROBE_DIR / 'runtime/14__probe_multitu_owner_transfer_release_once_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_queue_pop_fail_preserves_window_state',
        source=PROBE_DIR / 'runtime/14__probe_queue_pop_fail_preserves_window_state.c',
        note='queue pop-fail path should preserve read window state and match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_token_reserve_commit_abort',
        source=PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_main.c',
        note='multi-TU token reserve/commit/abort transitions should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_main.c', PROBE_DIR / 'runtime/14__probe_multitu_token_reserve_commit_abort_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_layer_budget_trim_generation',
        source=PROBE_DIR / 'runtime/14__probe_multitu_layer_budget_trim_generation_main.c',
        note='multi-TU layer-budget trim and generation transitions should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_layer_budget_trim_generation_main.c', PROBE_DIR / 'runtime/14__probe_multitu_layer_budget_trim_generation_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_layer_toggle_residency_trim_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_layer_toggle_residency_trim_runtime.c',
        note='reduced map_forge layer-toggle and residency trim behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_tile_queue_generation_guard_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_tile_queue_generation_guard_runtime.c',
        note='reduced map_forge tile-queue generation guard behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_transfer_single_release_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_transfer_single_release_runtime.c',
        note='reduced map_forge owner-transfer single-release behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_layer_commit_abort_budget_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_layer_commit_abort_budget_runtime.c',
        note='reduced map_forge layer commit/abort budget behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_ttl_replay_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_ttl_replay_runtime.c',
        note='reduced map_forge owner/ttl replay behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_fnptr_owner_guard_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_fnptr_owner_guard_runtime.c',
        note='reduced map_forge function-pointer owner/guard behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_stale_residency_reclaim_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_stale_residency_reclaim_runtime.c',
        note='reduced map_forge stale residency reclaim behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_mask_dispatch_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_mask_dispatch_runtime.c',
        note='reduced map_forge owner-mask dispatch behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_guard_reclaim_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_guard_reclaim_runtime.c',
        note='reduced map_forge epoch/guard reclaim behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_commit_trim_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_commit_trim_runtime.c',
        note='reduced map_forge epoch commit/trim behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_replay_guard_trim_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_replay_guard_trim_runtime.c',
        note='map_forge epoch/replay/guard trim behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_shadow_abort_reclaim_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_shadow_abort_reclaim_runtime.c',
        note='map_forge epoch/shadow abort/reclaim behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_checkpoint_budget_reseed_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_checkpoint_budget_reseed_runtime.c',
        note='map_forge checkpoint/budget reseed behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_replay_window_guard_handoff_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_replay_window_guard_handoff_runtime.c',
        note='map_forge replay-window guard/handoff behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_static_local_replay_handoff_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_local_replay_handoff_mesh_main.c',
        note='multi-TU static-local replay handoff mesh should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_local_replay_handoff_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_local_replay_handoff_mesh_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_static_storage_alias_reseed_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_static_storage_alias_reseed_mesh_main.c',
        note='multi-TU static-storage alias reseed mesh should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_static_storage_alias_reseed_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_static_storage_alias_reseed_mesh_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_ttl_dispatch_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_ttl_dispatch_runtime.c',
        note='reduced map_forge owner/ttl dispatch behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_stale_drop_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_stale_drop_runtime.c',
        note='reduced map_forge epoch/stale drop behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_guard_dispatch_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_guard_dispatch_runtime.c',
        note='reduced map_forge owner/guard dispatch behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_cleanup_double_call_guard_matrix',
        source=PROBE_DIR / 'runtime/14__probe_cleanup_double_call_guard_matrix.c',
        note='cleanup double-call guard matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_queue_trim_idempotent_window_matrix',
        source=PROBE_DIR / 'runtime/14__probe_queue_trim_idempotent_window_matrix.c',
        note='queue trim idempotent-window matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_generation_gate_stale_entry_drop_matrix',
        source=PROBE_DIR / 'runtime/14__probe_generation_gate_stale_entry_drop_matrix.c',
        note='generation-gate stale-entry drop matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_fnptr_struct_return_long_double_bridge',
        source=PROBE_DIR / 'runtime/14__probe_fnptr_struct_return_long_double_bridge.c',
        note='function-pointer selected long-double struct return bridge should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_variadic_fnptr_struct_payload_bridge',
        source=PROBE_DIR / 'runtime/14__probe_variadic_fnptr_struct_payload_bridge.c',
        note='variadic function-pointer struct payload fold bridge should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_fnptr_variadic_state_pipeline',
        source=PROBE_DIR / 'runtime/14__probe_multitu_fnptr_variadic_state_pipeline_main.c',
        note='multi-TU variadic function-pointer state pipeline should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_fnptr_variadic_state_pipeline_main.c', PROBE_DIR / 'runtime/14__probe_multitu_fnptr_variadic_state_pipeline_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_restrict_char_alias_rebase_matrix',
        source=PROBE_DIR / 'runtime/14__probe_restrict_char_alias_rebase_matrix.c',
        note='restrict copy with char-alias rebasing matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_ptrdiff_roundtrip_through_uintptr_matrix',
        source=PROBE_DIR / 'runtime/14__probe_ptrdiff_roundtrip_through_uintptr_matrix.c',
        note='ptrdiff roundtrip through uintptr bridge matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_ptr_alias_window_stability',
        source=PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_window_stability_main.c',
        note='multi-TU pointer alias window stability path should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_window_stability_main.c', PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_window_stability_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_ptr_alias_owner_replay_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_owner_replay_mesh_main.c',
        note='multi-TU pointer alias owner replay mesh should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_owner_replay_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_owner_replay_mesh_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_ptr_alias_route_shadow_reclaim',
        source=PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_route_shadow_reclaim_main.c',
        note='multi-TU pointer alias route shadow reclaim should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_route_shadow_reclaim_main.c', PROBE_DIR / 'runtime/14__probe_multitu_ptr_alias_route_shadow_reclaim_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_rollback_guard_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_rollback_guard_runtime.c',
        note='map_forge owner rollback/guard carry should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_transfer_rollback_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_transfer_rollback_runtime.c',
        note='map_forge epoch transfer/rollback carry should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_owner_window_borrow_replay_mesh',
        source=PROBE_DIR / 'runtime/14__probe_multitu_owner_window_borrow_replay_mesh_main.c',
        note='multi-TU owner-window borrow replay mesh should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_owner_window_borrow_replay_mesh_main.c', PROBE_DIR / 'runtime/14__probe_multitu_owner_window_borrow_replay_mesh_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_owner_window_stale_handoff_reclaim',
        source=PROBE_DIR / 'runtime/14__probe_multitu_owner_window_stale_handoff_reclaim_main.c',
        note='multi-TU owner-window stale handoff reclaim should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_owner_window_stale_handoff_reclaim_main.c', PROBE_DIR / 'runtime/14__probe_multitu_owner_window_stale_handoff_reclaim_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_borrow_epoch_residency_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_borrow_epoch_residency_runtime.c',
        note='map_forge borrow/epoch residency carry should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_owner_window_stale_rollback_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_owner_window_stale_rollback_runtime.c',
        note='map_forge owner-window stale rollback carry should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_pointer_lifetime_epoch_bridge',
        source=PROBE_DIR / 'runtime/14__probe_multitu_pointer_lifetime_epoch_bridge_main.c',
        note='multi-TU pointer-lifetime epoch bridge should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_pointer_lifetime_epoch_bridge_main.c', PROBE_DIR / 'runtime/14__probe_multitu_pointer_lifetime_epoch_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_multitu_pointer_lifetime_window_feedback',
        source=PROBE_DIR / 'runtime/14__probe_multitu_pointer_lifetime_window_feedback_main.c',
        note='multi-TU pointer-lifetime window feedback should match clang runtime behavior',
        inputs=[PROBE_DIR / 'runtime/14__probe_multitu_pointer_lifetime_window_feedback_main.c', PROBE_DIR / 'runtime/14__probe_multitu_pointer_lifetime_window_feedback_lib.c'],
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_epoch_rollback_plane_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_epoch_rollback_plane_runtime.c',
        note='map_forge epoch rollback/plane carry should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='14__probe_realproj_map_forge_borrow_trim_rollback_runtime',
        source=PROBE_DIR / 'runtime/14__probe_realproj_map_forge_borrow_trim_rollback_runtime.c',
        note='map_forge borrow/trim rollback carry should match clang runtime behavior',
    ),
]

DIAG_PROBES = []

DIAG_JSON_PROBES = []
