// SPDX-License-Identifier: Apache-2.0

#ifndef AST_NODE_TYPE_H
#define AST_NODE_TYPE_H

typedef enum {
    AST_PROGRAM,
    AST_BLOCK,
    AST_STATEMENT_EXPRESSION,
    AST_HEAP_ALLOCATION,

    AST_INCLUDE_DIRECTIVE,
    AST_DEFINE_DIRECTIVE,
    AST_CONDITIONAL_DIRECTIVE,
    AST_ENDIF_DIRECTIVE,

    AST_TYPEDEF,
    AST_VARIABLE_DECLARATION,
    AST_UNION_DEFINITION,
    AST_STRUCT_DEFINITION,
    AST_STRUCT_FIELD_ACCESS,
    AST_ENUM_DEFINITION,

    AST_ARRAY_ACCESS,
    AST_POINTER_ACCESS,
    AST_DOT_ACCESS,
    AST_POINTER_DEREFERENCE,

    AST_TERNARY_EXPRESSION,
    AST_BINARY_EXPRESSION,
    AST_UNARY_EXPRESSION,
    AST_COMMA_EXPRESSION,
    AST_CAST_EXPRESSION,

    AST_BASIC_TYPE,
    AST_PARSED_TYPE,
    AST_NUMBER_LITERAL,
    AST_CHAR_LITERAL,
    AST_STRING_LITERAL,
    AST_IDENTIFIER,
    AST_SIZEOF,
    AST_COMPOUND_LITERAL,

    AST_ASSIGNMENT,

    AST_IF_STATEMENT,
    AST_ALIGNOF,
    AST_SEQUENCE,
    AST_WHILE_LOOP,
    AST_FOR_LOOP,

    AST_RETURN,
    AST_BREAK,
    AST_CONTINUE,
    AST_GOTO_STATEMENT,
    AST_LABEL_DECLARATION,

    AST_FUNCTION_DECLARATION,
    AST_FUNCTION_DEFINITION,
    AST_FUNCTION_CALL,
    AST_FUNCTION_POINTER,

    AST_SWITCH,
    AST_CASE,
    AST_STATIC_ASSERT,

    AST_ASM
} ASTNodeType;

typedef struct ASTNode ASTNode;

ASTNodeType astNodeGetType(const ASTNode* node);

#endif // AST_NODE_TYPE_H
