#include "04__probe_diag_line_directive_multitu_include_object_qualifier_conflict_spelling_strict.h"

#line 17202 "virtual_decl_multitu_include_object_qualifier_conflict_probe_diag_text_lib.c"
int wave15_mt_decl_object_const_conflict = 7;
