#line 6351 "virtual_types_include_nested_designator_array_negative_probe_host.c"
#include "07__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.h"

int main(void) { return probe_wave48_include_nested_designator_array_negative(); }
