#include "07__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.h"

int main(void) { return probe_wave54_diag_text_include_nested_designator_array_negative(); }
