#ifndef PROBE_MALFORMED_INCLUDE_GRAPH_MACRO_ARITY_CHAIN_A_H
#define PROBE_MALFORMED_INCLUDE_GRAPH_MACRO_ARITY_CHAIN_A_H

#include "15__probe_diag_malformed_include_graph_macro_arity_chain_no_crash_b.h"

#endif
