#ifndef PROBE_MALFORMED_HEADER_GUARD_TAIL_MISMATCH_CHAIN_A_EXPECTED_H
#define PROBE_MALFORMED_HEADER_GUARD_TAIL_MISMATCH_CHAIN_A_ACTUAL_H

#include "15__probe_diag_malformed_header_guard_tail_mismatch_chain_no_crash_b.h"
static int probe_header_guard_tail_chain_value(void) { return 41; }

#endif
