from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='11__probe_function_param_function_type_adjust_ok',
        source=PROBE_DIR / 'runtime/11__probe_function_param_function_type_adjust_ok.c',
        note='function parameter declared as function type should adjust to pointer and accept matching function argument',
    ),
    RuntimeProbe(
        probe_id='11__probe_external_small_struct_byval_pointer_bridge',
        source=PROBE_DIR / 'runtime/11__probe_external_small_struct_byval_pointer_bridge_main.c',
        note='small struct by-value call into clang-built external callee should preserve trailing pointer argument on arm64',
        mixed_clang_inputs=[PROBE_DIR / 'runtime/11__probe_external_small_struct_byval_pointer_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='11__probe_external_large_struct_sret_bridge',
        source=PROBE_DIR / 'runtime/11__probe_external_large_struct_sret_bridge_main.c',
        note='large struct return from clang-built external callee should use hidden sret and preserve trailing arguments on arm64',
        mixed_clang_inputs=[PROBE_DIR / 'runtime/11__probe_external_large_struct_sret_bridge_lib.c'],
    ),
    RuntimeProbe(
        probe_id='11__probe_small_struct_byval_multitu_definition',
        source=PROBE_DIR / 'runtime/11__probe_small_struct_byval_multitu_definition_main.c',
        note='separate-TU declaration and definition should agree on arm64 small-struct by-value parameter ABI',
        inputs=[
            PROBE_DIR / 'runtime/11__probe_small_struct_byval_multitu_definition_main.c',
            PROBE_DIR / 'runtime/11__probe_small_struct_byval_multitu_definition_lib.c',
        ],
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='11__probe_duplicate_param_name_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_duplicate_param_name_reject.c',
        note='duplicate parameter names in one function declarator should be rejected',
    ),
    DiagnosticProbe(
        probe_id='11__probe_param_auto_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_param_auto_reject.c',
        note='function parameter should reject auto storage class',
    ),
    DiagnosticProbe(
        probe_id='11__probe_param_void_plus_other_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_param_void_plus_other_reject.c',
        note="parameter list must reject 'void' combined with additional parameters",
    ),
    DiagnosticProbe(
        probe_id='11__probe_param_incomplete_type_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_param_incomplete_type_reject.c',
        note='function parameter declared with incomplete struct type should be rejected',
    ),
    DiagnosticProbe(
        probe_id='11__probe_return_void_expr_in_int_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_return_void_expr_in_int_reject.c',
        note='int-returning function should reject returning void expression',
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_nonvoid_missing_return_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_nonvoid_missing_return_text_strict.c',
        note='text diagnostics should preserve remapped line for #line non-void-missing-return',
        required_substrings=["Error at (7501:5): Control reaches end of non-void function 'f_text'"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_include_nonvoid_missing_return_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_include_nonvoid_missing_return_text_strict.c',
        note='text diagnostics should preserve remapped line for include #line non-void-missing-return',
        required_substrings=["Error at (7601:5): Control reaches end of non-void function 'f_inc_text'"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_too_many_args_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_too_many_args_text_strict.c',
        note='text diagnostics should preserve remapped line for #line prototype-too-many-args',
        required_substrings=["Error at (7706:12): Too many arguments in call to 'add1_text' (expected 1, got 2)"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_include_too_many_args_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_include_too_many_args_text_strict.c',
        note='text diagnostics should preserve remapped line for include #line prototype-too-many-args',
        required_substrings=["Error at (7802:34): Too many arguments in call to 'add1_inc_text' (expected 1, got 2)"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_too_few_args_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_too_few_args_text_strict.c',
        note='text diagnostics should preserve remapped line for #line prototype-too-few-args',
        required_substrings=["Error at (8906:12): Too few arguments in call to 'add2_text' (expected 2, got 1)"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_include_too_few_args_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_include_too_few_args_text_strict.c',
        note='text diagnostics should preserve remapped line for include #line prototype-too-few-args',
        required_substrings=["Error at (9002:34): Too few arguments in call to 'add2_inc_text' (expected 2, got 1)"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_argument_type_mismatch_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_argument_type_mismatch_text_strict.c',
        note='text diagnostics should preserve remapped line for #line argument-type-mismatch',
        required_substrings=["Error at (9106:27): Argument 1 of 'takes_ptr_text' has incompatible type"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_include_argument_type_mismatch_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_include_argument_type_mismatch_text_strict.c',
        note='text diagnostics should preserve remapped line for include #line argument-type-mismatch',
        required_substrings=["Error at (9202:53): Argument 1 of 'takes_ptr_inc_text' has incompatible type"],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_return_type_mismatch_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_return_type_mismatch_text_strict.c',
        note='text diagnostics should preserve remapped line for #line return-type-mismatch',
        required_substrings=['Error at (10102:'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_include_return_type_mismatch_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_include_return_type_mismatch_text_strict.c',
        note='text diagnostics should preserve remapped line for include #line return-type-mismatch',
        required_substrings=['Error at (10201:'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_void_return_value_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_void_return_value_text_strict.c',
        note='text diagnostics should preserve remapped line for #line void-return-value rejection',
        required_substrings=['Error at (10302:'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_include_void_return_value_text_strict',
        source=PROBE_DIR / 'diagnostics/11__probe_diag_line_directive_include_void_return_value_text_strict.c',
        note='text diagnostics should preserve remapped line for include #line void-return-value rejection',
        required_substrings=['Error at (10401:'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_multitu_too_many_args_text_threshold_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_too_many_args_file_presence.c',
        note='text parity guard: multi-TU #line too-many-args remains stable in text diagnostics',
        required_substrings=["Error at (13304:12): Too many arguments in call to 'probe_mt_add1' (expected 1, got 2)"],
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_too_many_args_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_too_many_args_file_presence_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_multitu_include_too_many_args_text_threshold_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence.c',
        note='text parity guard: multi-TU include #line too-many-args remains stable in text diagnostics',
        required_substrings=["Error at (13402:49): Too many arguments in call to 'probe_mt_add1_inc' (expected 1, got 2)"],
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_multitu_parserdiag_decl_missing_rparen_text_threshold_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence.c',
        note='text parity guard: multi-TU #line parser declarator recovery remains stable in text diagnostics',
        required_substrings=['virtual_probe_fn_multitu_parserdiag_decl_missing_rparen_main.c:13501'],
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='11__probe_diag_line_directive_multitu_include_parserdiag_decl_missing_rparen_text_threshold_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence.c',
        note='text parity guard: multi-TU include #line parser declarator recovery remains stable in text diagnostics',
        required_substrings=['virtual_probe_fn_multitu_include_parserdiag_decl_missing_rparen.h:13601'],
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence_lib.c'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_nonvoid_missing_return_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_nonvoid_missing_return_file_presence.c',
        note='strict frontier: #line non-void-missing-return diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=7101,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_nonvoid_missing_return_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_nonvoid_missing_return_file_presence.c',
        note='reduced threshold: #line non-void-missing-return diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=7101,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_nonvoid_missing_return_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_nonvoid_missing_return_file_presence.c',
        note='strict frontier: include #line non-void-missing-return diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=7201,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_nonvoid_missing_return_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_nonvoid_missing_return_file_presence.c',
        note='reduced threshold: include #line non-void-missing-return diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=7201,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_too_many_args_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_too_many_args_file_presence.c',
        note='strict frontier: #line prototype-too-many-args diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=7306,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_too_many_args_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_too_many_args_file_presence.c',
        note='reduced threshold: #line prototype-too-many-args diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=7306,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_too_many_args_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_too_many_args_file_presence.c',
        note='strict frontier: include #line prototype-too-many-args diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=7402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_too_many_args_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_too_many_args_file_presence.c',
        note='reduced threshold: include #line prototype-too-many-args diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=7402,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_too_few_args_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_too_few_args_file_presence.c',
        note='strict frontier: #line prototype-too-few-args diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=8506,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_too_few_args_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_too_few_args_file_presence.c',
        note='reduced threshold: #line prototype-too-few-args diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=8506,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_too_few_args_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_too_few_args_file_presence.c',
        note='strict frontier: include #line prototype-too-few-args diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=8602,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_too_few_args_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_too_few_args_file_presence.c',
        note='reduced threshold: include #line prototype-too-few-args diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=8602,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_argument_type_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_argument_type_mismatch_file_presence.c',
        note='strict frontier: #line argument-type-mismatch diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=8706,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_argument_type_mismatch_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_argument_type_mismatch_file_presence.c',
        note='reduced threshold: #line argument-type-mismatch diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=8706,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_argument_type_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_argument_type_mismatch_file_presence.c',
        note='strict frontier: include #line argument-type-mismatch diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=8802,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_argument_type_mismatch_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_argument_type_mismatch_file_presence.c',
        note='reduced threshold: include #line argument-type-mismatch diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=8802,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_return_type_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_return_type_mismatch_file_presence.c',
        note='strict frontier: #line return-type-mismatch diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=9302,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_return_type_mismatch_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_return_type_mismatch_file_presence.c',
        note='reduced threshold: #line return-type-mismatch diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=9302,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_return_type_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_return_type_mismatch_file_presence.c',
        note='strict frontier: include #line return-type-mismatch diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=9501,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_return_type_mismatch_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_return_type_mismatch_file_presence.c',
        note='reduced threshold: include #line return-type-mismatch diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=9501,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_void_return_value_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_void_return_value_file_presence.c',
        note='strict frontier: #line void-return-value diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=9402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_void_return_value_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_void_return_value_file_presence.c',
        note='reduced threshold: #line void-return-value diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=9402,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_void_return_value_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_void_return_value_file_presence.c',
        note='strict frontier: include #line void-return-value diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=9601,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_void_return_value_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_void_return_value_file_presence.c',
        note='reduced threshold: include #line void-return-value diagjson preserves remapped line with sparse location metadata',
        expected_codes=[2000],
        expected_line=9601,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_fnptr_assign_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_fnptr_assign_file_presence.c',
        note='strict frontier: #line function-pointer assignment diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=12317,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_include_fnptr_assign_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_include_fnptr_assign_file_presence.c',
        note='strict frontier: include #line function-pointer assignment diagjson should preserve file presence',
        expected_codes=[2000],
        expected_line=12416,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_too_many_args_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_too_many_args_file_presence.c',
        note='strict frontier: multi-TU #line too-many-args diagjson should preserve remapped line and file presence',
        expected_codes=[2000],
        expected_line=13304,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_too_many_args_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_too_many_args_file_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence.c',
        note='strict frontier: multi-TU include #line too-many-args diagjson should preserve remapped line and file presence',
        expected_codes=[2000],
        expected_line=13402,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_too_many_args_file_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence.c',
        note='strict frontier: multi-TU #line parser-declarator recovery should preserve parser diagjson presence',
        expected_codes=[1000],
        expected_line=13501,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_parserdiag_decl_missing_rparen_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence.c',
        note='strict frontier: multi-TU include #line parser-declarator recovery should preserve parser diagjson presence',
        expected_codes=[1000],
        expected_line=13601,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_parserdiag_decl_missing_rparen_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_fnptr_assign_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_fnptr_assign_file_presence.c',
        note='strict frontier: multi-TU #line function-pointer assignment diagjson should preserve remapped line and file presence',
        expected_codes=[2000],
        expected_line=14507,
        expected_column=5,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_fnptr_assign_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_fnptr_assign_file_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_include_fnptr_assign_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_fnptr_assign_file_presence.c',
        note='strict frontier: multi-TU include #line function-pointer assignment diagjson should preserve remapped line and file presence',
        expected_codes=[2000],
        expected_line=14606,
        expected_column=5,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_fnptr_assign_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_fnptr_assign_file_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_return_type_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_return_type_mismatch_file_presence.c',
        note='strict frontier: multi-TU #line return-type-mismatch diagjson should preserve remapped line and file presence',
        expected_codes=[2000],
        expected_line=14752,
        expected_column=12,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_return_type_mismatch_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_return_type_mismatch_file_presence_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='11__probe_diagjson_line_directive_multitu_include_return_type_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_return_type_mismatch_file_presence.c',
        note='strict frontier: multi-TU include #line return-type-mismatch diagjson should preserve remapped line and file presence',
        expected_codes=[2000],
        expected_line=14852,
        expected_column=12,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_return_type_mismatch_file_presence.c', PROBE_DIR / 'diagnostics/11__probe_diagjson_line_directive_multitu_include_return_type_mismatch_file_presence_lib.c'],
    ),
]
