from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='02__probe_wave23_ucn_short_long_initial_internal_equivalence_strict',
        source=PROBE_DIR / 'runtime/02__probe_wave23_ucn_short_long_initial_internal_equivalence_strict.c',
        note='wave23 strict: short and long UCN spellings denote the same identifier in both initial and internal positions',
        promoted_test_id='02__runtime_wave23_ucn_short_long_initial_internal_equivalence_strict',
    ),
    RuntimeProbe(
        probe_id='02__probe_wave23_ucn_utf8_source_spelling_equivalence_strict',
        source=PROBE_DIR / 'runtime/02__probe_wave23_ucn_utf8_source_spelling_equivalence_strict.c',
        note='wave23 strict: an escaped UCN declaration and its literal UTF-8 source spelling denote the same identifier',
        promoted_test_id='02__runtime_wave23_ucn_utf8_source_spelling_equivalence_strict',
    ),
    RuntimeProbe(
        probe_id='02__probe_wave23_ucn_macro_name_canonical_transport_strict',
        source=PROBE_DIR / 'runtime/02__probe_wave23_ucn_macro_name_canonical_transport_strict.c',
        note='wave23 strict: macro lookup canonicalizes short and long UCN spellings of the same identifier',
        promoted_test_id='02__runtime_wave23_ucn_macro_name_canonical_transport_strict',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_invalid_dollar_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_invalid_dollar_diagjson_current_physical_line.c',
        note="fixed baseline: include-header lexer invalid '$' diagnostic now reports remapped virtual line",
        required_substrings=[':1831:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_unterminated_string_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_unterminated_string_diagjson_current_physical_line.c',
        note='fixed baseline: include-header lexer unterminated-string diagnostic now reports remapped virtual line',
        required_substrings=[':1721:21'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_char_invalid_hex_escape_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_char_invalid_hex_escape_diagjson_current_physical_line.c',
        note='fixed baseline: include-header lexer invalid \\x escape diagnostic now reports remapped virtual line',
        required_substrings=[':1911:14'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_string_invalid_escape_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_string_invalid_escape_diagjson_current_physical_line.c',
        note='fixed baseline: include-header lexer invalid string-escape diagnostic now reports remapped virtual line',
        required_substrings=[':1941:21'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_invalid_at_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_invalid_at_diagjson_current_physical_line.c',
        note="fixed baseline: include-header lexer invalid '@' diagnostic now reports remapped virtual line",
        required_substrings=[':1971:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_invalid_backtick_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_invalid_backtick_diagjson_current_physical_line.c',
        note="fixed baseline: include-header lexer invalid '`' diagnostic now reports remapped virtual line",
        required_substrings=[':1981:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_unterminated_char_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_unterminated_char_diagjson_current_physical_line.c',
        note='fixed baseline: include-header lexer unterminated-char diagnostic now reports remapped virtual line',
        required_substrings=[':1991:14'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_malformed_float_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_malformed_float_current_physical_line.c',
        note='fixed baseline: lexer malformed-float exponent diagnostic now reports remapped virtual line',
        required_substrings=['virtual_lexer_malformed_float_case.c:2210:12'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_float_hex_no_exponent_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_float_hex_no_exponent_current_physical_line.c',
        note="fixed baseline: lexer hex-float-without-p diagnostic now reports remapped virtual line",
        required_substrings=["virtual_lexer_hex_no_exponent_case.c:2310:12"],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_ucn_identifier_unsupported_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_ucn_identifier_unsupported_current_physical_line.c',
        note='current threshold: direct UCN policy lane still reports the physical source line under #line remap',
        required_substrings=['02__line_directive_ucn_identifier_unsupported_current_physical_line.c:2'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_include_ucn_identifier_unsupported_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_ucn_identifier_unsupported_current_physical_line.c',
        note='current threshold: include-header UCN policy lane falls through to remapped parser diagnostics after the initial lexer rejection',
        required_substrings=['virtual_lexer_include_ucn_identifier_case.h:2130'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_invalid_dollar_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_dollar_location_reject.c',
        note="lexer diagnostic should honor #line remap for invalid '$' token",
        required_substrings=[':831:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_invalid_dollar_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_dollar_current_physical_line.c',
        note="fixed baseline: lexer invalid '$' diagnostic now reports remapped virtual line",
        required_substrings=[':831:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_unterminated_string_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_string_location_reject.c',
        note='lexer diagnostic should honor #line remap for unterminated string literal',
        required_substrings=[':721:21'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_unterminated_string_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_string_current_physical_line.c',
        note='fixed baseline: lexer unterminated-string diagnostic now reports remapped virtual line',
        required_substrings=[':721:21'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_char_invalid_hex_escape_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_char_invalid_hex_escape_location_reject.c',
        note='lexer diagnostic should honor #line remap for invalid \\x escape in character literal',
        required_substrings=[':911:14'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_char_invalid_hex_escape_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_char_invalid_hex_escape_current_physical_line.c',
        note='fixed baseline: lexer invalid \\x escape diagnostic now reports remapped virtual line',
        required_substrings=[':911:14'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_string_invalid_escape_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_string_invalid_escape_location_reject.c',
        note='lexer diagnostic should honor #line remap for invalid string escape',
        required_substrings=[':941:21'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_string_invalid_escape_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_string_invalid_escape_current_physical_line.c',
        note='fixed baseline: lexer invalid string-escape diagnostic now reports remapped virtual line',
        required_substrings=[':941:21'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_invalid_at_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_at_location_reject.c',
        note="lexer diagnostic should honor #line remap for invalid '@' token",
        required_substrings=[':971:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_invalid_at_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_at_current_physical_line.c',
        note="fixed baseline: lexer invalid '@' diagnostic now reports remapped virtual line",
        required_substrings=[':971:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_invalid_backtick_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_backtick_location_reject.c',
        note="lexer diagnostic should honor #line remap for invalid '`' token",
        required_substrings=[':981:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_invalid_backtick_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_backtick_current_physical_line.c',
        note="fixed baseline: lexer invalid '`' diagnostic now reports remapped virtual line",
        required_substrings=[':981:9'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_unterminated_char_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_char_location_reject.c',
        note='lexer diagnostic should honor #line remap for unterminated character literal',
        required_substrings=[':991:14'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_lexer_line_directive_unterminated_char_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_char_current_physical_line.c',
        note='fixed baseline: lexer unterminated-char diagnostic now reports remapped virtual line',
        required_substrings=[':991:14'],
    ),
    DiagnosticProbe(
        probe_id='02__probe_wave22_direct_ucn_nonbasic_identifier_strict',
        source=PROBE_DIR / 'runtime/02__probe_wave22_direct_ucn_nonbasic_identifier_strict.c',
        note='strict C99 boundary: a nonbasic universal character name is a valid identifier spelling and must compile without diagnostics like Clang',
        expect_any_diagnostic=False,
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_invalid_dollar_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_invalid_dollar_diagjson_current_physical_line.c',
        note="fixed baseline: diagnostics JSON reports remapped line for include-header lexer invalid '$' token",
        expected_codes=[1],
        expected_line=1831,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_unterminated_string_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_unterminated_string_diagjson_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for include-header lexer unterminated string',
        expected_codes=[1],
        expected_line=1721,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_char_invalid_hex_escape_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_char_invalid_hex_escape_diagjson_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for include-header lexer invalid \\x char escape',
        expected_codes=[1],
        expected_line=1911,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_string_invalid_escape_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_string_invalid_escape_diagjson_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for include-header lexer invalid string escape',
        expected_codes=[1],
        expected_line=1941,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_invalid_at_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_invalid_at_diagjson_current_physical_line.c',
        note="fixed baseline: diagnostics JSON reports remapped line for include-header lexer invalid '@' token",
        expected_codes=[1],
        expected_line=1971,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_invalid_backtick_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_invalid_backtick_diagjson_current_physical_line.c',
        note="fixed baseline: diagnostics JSON reports remapped line for include-header lexer invalid '`' token",
        expected_codes=[1],
        expected_line=1981,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_unterminated_char_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_unterminated_char_diagjson_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for include-header lexer unterminated character literal',
        expected_codes=[1],
        expected_line=1991,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_malformed_float_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_malformed_float_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for lexer malformed-float exponent diagnostic',
        expected_codes=[1],
        expected_line=2210,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_float_hex_no_exponent_current_physical_line',
        source=PROBE_DIR.parent / 'cases/02__line_directive_float_hex_no_exponent_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for lexer hex-float-without-p diagnostic',
        expected_codes=[1],
        expected_line=2310,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_include_ucn_identifier_unsupported_current_parser_only',
        source=PROBE_DIR.parent / 'cases/02__line_directive_include_ucn_identifier_unsupported_current_physical_line.c',
        note='current threshold: include-header UCN policy lane exports remapped parser diagnostics JSON rather than a lexer-policy payload',
        expected_codes=[1000],
        expected_line=2130,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_ucn_identifier_unsupported_current_empty',
        source=PROBE_DIR.parent / 'cases/02__line_directive_ucn_identifier_unsupported_current_physical_line.c',
        note='post-fix threshold: direct UCN policy lane exports a populated diagnostics JSON payload',
        expected_codes=[1],
        expected_line=2030,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_invalid_dollar_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_dollar_location_reject.c',
        note="diagnostics JSON should honor #line remap for lexer invalid '$' token",
        expected_codes=[1],
        expected_line=831,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_invalid_dollar_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_dollar_current_physical_line.c',
        note="fixed baseline: diagnostics JSON reports remapped line for lexer invalid '$' token",
        expected_codes=[1],
        expected_line=831,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_unterminated_string_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_string_location_reject.c',
        note='diagnostics JSON should honor #line remap for lexer unterminated string literal',
        expected_codes=[1],
        expected_line=721,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_unterminated_string_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_string_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for lexer unterminated string',
        expected_codes=[1],
        expected_line=721,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_char_invalid_hex_escape_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_char_invalid_hex_escape_location_reject.c',
        note='diagnostics JSON should honor #line remap for lexer invalid \\x char escape',
        expected_codes=[1],
        expected_line=911,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_char_invalid_hex_escape_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_char_invalid_hex_escape_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for lexer invalid \\x char escape',
        expected_codes=[1],
        expected_line=911,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_string_invalid_escape_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_string_invalid_escape_location_reject.c',
        note='diagnostics JSON should honor #line remap for lexer invalid string escape',
        expected_codes=[1],
        expected_line=941,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_string_invalid_escape_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_string_invalid_escape_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for lexer invalid string escape',
        expected_codes=[1],
        expected_line=941,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_invalid_at_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_at_location_reject.c',
        note="diagnostics JSON should honor #line remap for lexer invalid '@' token",
        expected_codes=[1],
        expected_line=971,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_invalid_at_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_at_current_physical_line.c',
        note="fixed baseline: diagnostics JSON reports remapped line for lexer invalid '@' token",
        expected_codes=[1],
        expected_line=971,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_invalid_backtick_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_backtick_location_reject.c',
        note="diagnostics JSON should honor #line remap for lexer invalid '`' token",
        expected_codes=[1],
        expected_line=981,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_invalid_backtick_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_invalid_backtick_current_physical_line.c',
        note="fixed baseline: diagnostics JSON reports remapped line for lexer invalid '`' token",
        expected_codes=[1],
        expected_line=981,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_unterminated_char_location_reject',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_char_location_reject.c',
        note='diagnostics JSON should honor #line remap for lexer unterminated character literal',
        expected_codes=[1],
        expected_line=991,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_directive_unterminated_char_current_physical_line',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_directive_unterminated_char_current_physical_line.c',
        note='fixed baseline: diagnostics JSON reports remapped line for lexer unterminated character literal',
        expected_codes=[1],
        expected_line=991,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_splice_comment_invalid_at_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_splice_comment_invalid_at.c',
        note="strict frontier: line-spliced block-comment boundary should match clang's post-splice invalid-token line",
        expected_codes=[1],
        expected_line=2522,
        expected_column=42,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_lexer_line_splice_hex_float_no_exponent_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_lexer_line_splice_hex_float_no_exponent.c',
        note="strict frontier: line-spliced hex-float diagnostic should match clang's post-splice exponent location",
        expected_codes=[1],
        expected_line=2411,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave13_line_splice_string_escape_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave13_line_splice_string_escape_diagjson_strict.c',
        note='strict frontier: line-spliced invalid string escape should export the virtual post-splice location',
        expected_codes=[1],
        expected_line=2611,
        expected_column=21,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave13_line_splice_ucn_identifier_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave13_line_splice_ucn_identifier_diagjson_strict.c',
        note='strict frontier: line-spliced UCN identifier rejection should export a populated diagnostics JSON payload',
        expected_codes=[1],
        expected_line=2711,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave13_line_splice_ucn_identifier_current_empty',
        source=PROBE_DIR / 'diagnostics/02__probe_wave13_line_splice_ucn_identifier_diagjson_strict.c',
        note='post-fix threshold: line-spliced UCN identifier rejection exports a populated diagnostics JSON payload',
        expected_codes=[1],
        expected_line=2711,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave13_spliced_adjacent_string_invalid_token_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave13_spliced_adjacent_string_invalid_token_diagjson_strict.c',
        note='strict frontier: invalid token after spliced adjacent strings should export the virtual token location',
        expected_codes=[1],
        expected_line=2812,
        expected_column=29,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave14_line_splice_decimal_exponent_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave14_line_splice_decimal_exponent_diagjson_strict.c',
        note='strict frontier: spliced decimal exponent diagnostic should export the virtual post-splice location',
        expected_codes=[1],
        expected_line=3011,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave14_line_splice_decimal_exponent_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave14_line_splice_decimal_exponent_diagjson_strict.c',
        note='post-fix guard: spliced decimal exponent diagnostic exports the virtual post-splice location',
        expected_codes=[1],
        expected_line=3011,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave14_line_splice_hex_digit_boundary_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave14_line_splice_hex_digit_boundary_diagjson_strict.c',
        note='strict frontier: spliced hex-prefix recovery should export the virtual boundary location',
        expected_codes=[1],
        expected_line=3021,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave14_line_splice_hex_digit_boundary_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave14_line_splice_hex_digit_boundary_diagjson_strict.c',
        note='post-fix guard: spliced hex-prefix diagnostic exports the virtual boundary location',
        expected_codes=[1],
        expected_line=3021,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_diagjson_wave14_line_directive_numeric_then_invalid_token_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave14_line_directive_numeric_then_invalid_token_diagjson_strict.c',
        note="strict frontier: invalid token after a spliced numeric literal should keep the #line virtual location",
        expected_codes=[1],
        expected_line=3031,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave15_line_splice_char_escape_diagjson_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave15_line_splice_char_escape_diagjson_strict.c',
        note='strict frontier: line-spliced invalid char escape should export the virtual post-splice location',
        expected_codes=[1],
        expected_line=4011,
        expected_column=14,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave15_spliced_line_directive_string_escape_diagjson_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave15_spliced_line_directive_string_escape_diagjson_strict.c',
        note='fixed baseline: escaped-newline #line remap applies to following invalid string escape',
        expected_codes=[1],
        expected_line=4021,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave15_spliced_line_directive_ucn_identifier_diagjson_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave15_spliced_line_directive_ucn_identifier_diagjson_strict.c',
        note='fixed baseline: escaped-newline #line remap applies to following UCN identifier diagnostic',
        expected_codes=[1],
        expected_line=4030,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave15_include_spliced_invalid_token_diagjson_strict',
        source=PROBE_DIR / 'diagnostics/02__probe_wave15_include_spliced_invalid_token_diagjson_strict.c',
        note='strict frontier: included header spliced invalid token should preserve current header virtual location',
        expected_codes=[1],
        expected_line=4041,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave16_spliced_line_directive_numeric_suffix_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave16_spliced_line_directive_numeric_suffix_diagjson_current.c',
        note='current guard: escaped-newline #line remap carries through a spliced numeric suffix boundary',
        expected_codes=[1],
        expected_line=5010,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave16_spliced_line_directive_adjacent_string_escape_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave16_spliced_line_directive_adjacent_string_escape_diagjson_current.c',
        note='current guard: adjacent string lexing after spliced #line keeps invalid escape provenance',
        expected_codes=[1],
        expected_line=5021,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave16_include_spliced_ucn_identifier_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave16_include_spliced_ucn_identifier_diagjson_current.c',
        note='current threshold: include-header spliced UCN identifier lane exports a remapped lexer diagnostic',
        expected_codes=[1],
        expected_line=5031,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave16_spliced_line_directive_clean_string_numeric_diagjson_current_empty',
        source=PROBE_DIR / 'diagnostics/02__probe_wave16_spliced_line_directive_clean_string_numeric_diagjson_current_empty.c',
        note='runtime-neutral clean lexing companion for spliced #line, adjacent string, escape, and numeric tokens',
        require_any_diagnostic=False,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave17_spliced_line_comment_escape_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave17_spliced_line_comment_escape_diagjson_current.c',
        note='wave17 current threshold: phase-2 spliced #line plus comment/adjacent-string boundary keeps invalid escape provenance',
        expected_codes=[1],
        expected_line=6011,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave17_spliced_line_ucn_comment_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave17_spliced_line_ucn_comment_diagjson_current.c',
        note='wave17 current threshold: spliced #line and block-comment boundary preserve UCN identifier diagnostic provenance',
        expected_codes=[1],
        expected_line=6021,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave17_adjacent_string_comment_invalid_token_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave17_adjacent_string_comment_invalid_token_diagjson_current.c',
        note='wave17 current threshold: adjacent string/comment boundary reports following invalid token at remapped line',
        expected_codes=[1],
        expected_line=6031,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave17_spliced_line_clean_comment_string_diagjson_current_empty',
        source=PROBE_DIR / 'diagnostics/02__probe_wave17_spliced_line_clean_comment_string_diagjson_current_empty.c',
        note='wave17 clean companion: phase-2 splice, #line remap, comment boundary, adjacent strings, and numeric suffix lex without diagnostics',
        require_any_diagnostic=False,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave18_spliced_comment_ucn_invalid_token_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave18_spliced_comment_ucn_invalid_token_diagjson_current.c',
        note='wave18 current threshold: spliced #line, comment, UCN rejection, and following invalid token keep a remapped diagnostics JSON surface',
        expected_codes=[1],
        expected_line=7011,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave18_spliced_block_comment_string_escape_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave18_spliced_block_comment_string_escape_diagjson_current.c',
        note='wave18 current threshold: spliced #line plus block-comment/adjacent-string boundary keeps invalid string escape provenance',
        expected_codes=[1],
        expected_line=7021,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave18_line_splice_comment_numeric_invalid_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave18_line_splice_comment_numeric_invalid_diagjson_current.c',
        note='wave18 current threshold: numeric invalid-token recovery after phase-2 splice and trailing comment keeps virtual line provenance',
        expected_codes=[1],
        expected_line=7031,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave18_spliced_comment_clean_diagjson_current_empty',
        source=PROBE_DIR / 'diagnostics/02__probe_wave18_spliced_comment_clean_diagjson_current_empty.c',
        note='wave18 clean companion: spliced #line, comment, adjacent strings, and numeric tokens lex without diagnostics',
        require_any_diagnostic=False,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave19_splice_comment_ucn_invalid_order_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave19_splice_comment_ucn_invalid_order_diagjson_current.c',
        note='wave19 current threshold: splice plus comment boundary reports UCN rejection before the following invalid token on remapped lines',
        expected_codes=[1],
        expected_line=8011,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave19_numeric_suffix_escape_recovery_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave19_numeric_suffix_escape_recovery_diagjson_current.c',
        note='wave19 current threshold: invalid numeric suffix recovery still reaches the following invalid string escape with remapped provenance',
        expected_codes=[1],
        expected_line=8021,
        expected_column=38,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave19_adjacent_string_invalid_token_recovery_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave19_adjacent_string_invalid_token_recovery_diagjson_current.c',
        note='wave19 current threshold: invalid token between adjacent string literals reports at the remapped token column and recovers to trailing input',
        expected_codes=[1],
        expected_line=8030,
        expected_column=59,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave19_line_remap_splice_numeric_escape_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave19_line_remap_splice_numeric_escape_diagjson_current.c',
        note='wave19 current threshold: #line remap provenance survives spliced numeric recovery and a following invalid escape diagnostic',
        expected_codes=[1],
        expected_line=8042,
        expected_column=40,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave20_splice_comment_ucn_invalid_order_recovery_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave20_splice_comment_ucn_invalid_order_recovery_diagjson_current.c',
        note='wave20 current threshold: splice plus comment boundary reports UCN rejection before following invalid-token recovery on remapped lines',
        expected_codes=[1],
        expected_line=9011,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave20_adjacent_string_invalid_token_tail_recovery_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave20_adjacent_string_invalid_token_tail_recovery_diagjson_current.c',
        note='wave20 current threshold: adjacent-string invalid-token recovery reaches a following invalid escape under #line provenance',
        expected_codes=[1],
        expected_line=9020,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave20_numeric_suffix_escape_pair_recovery_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave20_numeric_suffix_escape_pair_recovery_diagjson_current.c',
        note='wave20 current threshold: invalid numeric suffix recovery reaches adjacent invalid string escapes with remapped provenance',
        expected_codes=[1],
        expected_line=9030,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave20_line_remap_provenance_escape_invalid_token_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave20_line_remap_provenance_escape_invalid_token_diagjson_current.c',
        note='wave20 current threshold: #line remap provenance survives spliced numeric recovery, invalid escape, and trailing invalid-token recovery',
        expected_codes=[1],
        expected_line=9041,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave21_char_hex_escape_invalid_token_tail_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave21_char_hex_escape_invalid_token_tail_diagjson_current.c',
        note='wave21 current threshold: remapped character-literal escape recovery reaches a following invalid token',
        expected_codes=[1],
        expected_line=10011,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave21_unterminated_char_invalid_token_tail_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave21_unterminated_char_invalid_token_tail_diagjson_current.c',
        note='wave21 current threshold: unterminated character literal and following invalid token retain remapped provenance',
        expected_codes=[1],
        expected_line=10020,
        expected_column=28,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave21_spliced_line_directive_token_paste_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave21_spliced_line_directive_token_paste_diagjson_current.c',
        note='wave21 current threshold: spliced line directive preserves token-paste invocation provenance for invalid token recovery',
        expected_codes=[1],
        expected_line=10031,
        expected_column=31,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave22_direct_ucn_incomplete_short_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave22_direct_ucn_incomplete_short_diagjson_current.c',
        note='wave22 measurement: an incomplete direct UCN retains remapped diagnostic provenance while semantic classification remains generic',
        expected_codes=[1],
        expected_line=11010,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='02__probe_wave22_direct_ucn_surrogate_diagjson_current',
        source=PROBE_DIR / 'diagnostics/02__probe_wave22_direct_ucn_surrogate_diagjson_current.c',
        note='wave22 measurement: an invalid surrogate UCN retains remapped diagnostic provenance while semantic classification remains generic',
        expected_codes=[1],
        expected_line=11020,
        expected_column=5,
        expected_has_file=True,
    ),
]
