from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='10__probe_static_function_then_extern_decl_ok',
        source=PROBE_DIR / 'runtime/10__probe_static_function_then_extern_decl_ok.c',
        note='file-scope static function followed by extern declaration should remain valid',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='10__probe_block_extern_different_type_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_block_extern_different_type_reject.c',
        note='block-scope extern should reject redeclaration with conflicting type',
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_type_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_type_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for extern type mismatch under #line',
        required_substrings=['Spelling: virtual_scope_extern_type_mismatch_probe_diag_text.c:6402:14'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_function_redecl_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_function_redecl_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for function redeclaration conflict under #line',
        required_substrings=['Spelling: virtual_scope_function_redecl_conflict_probe_diag_text.c:6502:7'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_type_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_type_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header extern type mismatch under #line',
        required_substrings=['Spelling: virtual_scope_include_extern_type_mismatch_probe_diag_text.h:6602:14'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_function_redecl_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_function_redecl_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header function redeclaration conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_function_redecl_conflict_probe_diag_text.h:6702:7'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_static_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_static_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for extern/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_extern_static_mismatch_probe_diag_text.c:7202:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_tentative_static_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_tentative_static_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for tentative/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_tentative_static_conflict_probe_diag_text.c:7302:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_static_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_static_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header extern/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_extern_static_mismatch_probe_diag_text.h:7402:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_tentative_static_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_tentative_static_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header tentative/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_tentative_static_conflict_probe_diag_text.h:7502:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_block_extern_different_type_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_block_extern_different_type_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for block-scope extern type-conflict under #line',
        required_substrings=['Spelling: virtual_scope_block_extern_type_conflict_probe_diag_text.c:8204:18'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_block_extern_different_type_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_block_extern_different_type_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header block-scope extern type-conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_block_extern_type_conflict_probe_diag_text.h:8304:18'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c',
        note='strict frontier: multi-TU extern type-conflict should preserve source spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_extern_type_conflict_probe_lib_diag_text.c:9902:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c',
        note='regression guard: multi-TU extern type-conflict should keep semantic spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_extern_type_conflict_probe_lib_diag_text.c:9902:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c',
        note='strict frontier: multi-TU include extern type-conflict should preserve source spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_include_extern_type_conflict_probe_header_diag_text.h:10002:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_include_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c',
        note='regression guard: multi-TU include extern type-conflict should keep semantic spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_include_extern_type_conflict_probe_header_diag_text.h:10002:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: extern-array mismatch should emit linkage conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_array_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array mismatch should emit linkage conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_mismatch_first_decl_line_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_first_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch with first declaration remapped by #line should emit conflict diagnostics',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_mismatch_second_decl_line_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_second_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch with second declaration remapped by #line should emit conflict diagnostics',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_vs_scalar_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_vs_scalar_conflict_spelling_strict.c',
        note='control lane: extern array-vs-scalar redeclaration should still emit conflict diagnostics under #line',
        required_substrings=['Spelling: virtual_scope_extern_array_vs_scalar_conflict_probe_diag_text.c:15302:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict_main.c',
        note='strict frontier: multi-TU extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict_main.c',
        note='strict frontier: multi-TU include extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict_lib.c'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_type_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_extern_type_mismatch_rich_strict.c',
        note='control lane: extern type-mismatch diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6002,
        expected_column=14,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_function_redecl_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_function_redecl_conflict_rich_strict.c',
        note='control lane: function redeclaration-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6102,
        expected_column=7,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_type_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_extern_type_mismatch_rich_strict.c',
        note='control lane: include-header extern type-mismatch diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6202,
        expected_column=14,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_function_redecl_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_function_redecl_conflict_rich_strict.c',
        note='control lane: include-header function redeclaration-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6302,
        expected_column=7,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_static_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_extern_static_mismatch_rich_strict.c',
        note='frontier lane: extern/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6802,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_tentative_static_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_tentative_static_conflict_rich_strict.c',
        note='frontier lane: tentative/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6902,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_static_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_extern_static_mismatch_rich_strict.c',
        note='frontier lane: include-header extern/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7002,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_tentative_static_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_tentative_static_conflict_rich_strict.c',
        note='frontier lane: include-header tentative/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7102,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_block_extern_different_type_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_block_extern_different_type_rich_strict.c',
        note='frontier lane: block-scope extern type-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7804,
        expected_column=18,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_block_extern_different_type_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_block_extern_different_type_rich_strict.c',
        note='frontier lane: include-header block-scope extern type-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7904,
        expected_column=18,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c',
        note='frontier lane: multi-TU extern type-conflict diagnostics JSON should preserve remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9502,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c',
        note='regression guard: multi-TU extern type-conflict should keep semantic remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9502,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c',
        note='frontier lane: multi-TU include extern type-conflict diagnostics JSON should preserve remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9602,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c',
        note='regression guard: multi-TU include extern type-conflict should keep semantic remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9602,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: extern-array mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=11502,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_array_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=11602,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_def_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: extern-array declaration/definition mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=12902,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_array_def_mismatch_current_physical_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_def_mismatch_spelling_strict.c',
        note='reduced threshold: include extern-array declaration/definition mismatch diagnostics JSON currently anchors to physical C file line',
        expected_codes=[2000],
        expected_line=3,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_mismatch_first_decl_line_current_physical_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_first_decl_line_spelling_strict.c',
        note='reduced threshold: extern-array mismatch first-decl placement diagnostics JSON currently anchors to physical remapped redeclaration line',
        expected_codes=[2000],
        expected_line=3,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_mismatch_second_decl_line_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_second_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch second-decl placement diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=15201,
        expected_column=12,
        expected_has_file=True,
    ),
]
