from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='09__probe_do_while_runtime_codegen_crash',
        source=PROBE_DIR / 'runtime/09__probe_do_while_runtime_codegen_crash.c',
        note='minimal do-while runtime executable path should compile/run and match clang',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='09__probe_goto_into_vla_scope_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_goto_into_vla_scope_reject.c',
        note='goto into VLA scope should be rejected',
    ),
    DiagnosticProbe(
        probe_id='09__probe_switch_float_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_switch_float_condition_reject.c',
        note='switch controlling expression must be integer type (float should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_switch_pointer_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_switch_pointer_condition_reject.c',
        note='switch controlling expression must be integer type (pointer should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_switch_string_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_switch_string_condition_reject.c',
        note='switch controlling expression must be integer type (string should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_switch_double_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_switch_double_condition_reject.c',
        note='switch controlling expression must be integer type (double should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_switch_pointer_condition_spelling_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_switch_pointer_condition_spelling_strict.c',
        note='strict frontier: #line pointer switch-condition text diagnostics should preserve remapped line',
        required_substrings=['Error at (7805:0): switch controlling expression must be integer'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_switch_pointer_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_switch_pointer_condition_spelling_strict.c',
        note='reduced threshold: #line pointer switch-condition text diagnostics should emit control-type rejection',
        required_substrings=['switch controlling expression must be integer'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_include_switch_pointer_condition_spelling_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_pointer_condition_spelling_strict.c',
        note='strict frontier: include-header #line pointer switch-condition text diagnostics should preserve remapped line',
        required_substrings=['Error at (7815:0): switch controlling expression must be integer'],
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_pointer_condition_spelling_strict.c', PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_pointer_condition_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_include_switch_pointer_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_pointer_condition_spelling_strict.c',
        note='reduced threshold: include-header #line pointer switch-condition text diagnostics should emit control-type rejection',
        required_substrings=['switch controlling expression must be integer'],
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_pointer_condition_spelling_strict.c', PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_pointer_condition_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_switch_string_condition_spelling_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_switch_string_condition_spelling_strict.c',
        note='strict frontier: #line string-literal switch-condition text diagnostics should preserve remapped line',
        required_substrings=['Error at (7823:0): switch controlling expression must be integer'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_switch_string_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_switch_string_condition_spelling_strict.c',
        note='reduced threshold: #line string-literal switch-condition text diagnostics should emit control-type rejection',
        required_substrings=['switch controlling expression must be integer'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_include_switch_string_condition_spelling_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_string_condition_spelling_strict.c',
        note='strict frontier: include-header #line string-literal switch-condition text diagnostics should preserve remapped line',
        required_substrings=['Error at (7833:0): switch controlling expression must be integer'],
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_string_condition_spelling_strict.c', PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_string_condition_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_include_switch_string_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_string_condition_spelling_strict.c',
        note='reduced threshold: include-header #line string-literal switch-condition text diagnostics should emit control-type rejection',
        required_substrings=['switch controlling expression must be integer'],
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_string_condition_spelling_strict.c', PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_string_condition_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_switch_double_condition_spelling_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_switch_double_condition_spelling_strict.c',
        note='strict frontier: #line double switch-condition text diagnostics should preserve remapped line',
        required_substrings=['Error at (7844:0): switch controlling expression must be integer'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_switch_double_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_switch_double_condition_spelling_strict.c',
        note='reduced threshold: #line double switch-condition text diagnostics should emit control-type rejection',
        required_substrings=['switch controlling expression must be integer'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_include_switch_double_condition_spelling_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_double_condition_spelling_strict.c',
        note='strict frontier: include-header #line double switch-condition text diagnostics should preserve remapped line',
        required_substrings=['Error at (7854:0): switch controlling expression must be integer'],
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_double_condition_spelling_strict.c', PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_double_condition_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_diag_line_directive_include_switch_double_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_double_condition_spelling_strict.c',
        note='reduced threshold: include-header #line double switch-condition text diagnostics should emit control-type rejection',
        required_substrings=['switch controlling expression must be integer'],
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_double_condition_spelling_strict.c', PROBE_DIR / 'diagnostics/09__probe_diag_line_directive_include_switch_double_condition_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='09__probe_if_void_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_if_void_condition_reject.c',
        note='if controlling expression must be scalar (void expression should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_if_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_if_struct_condition_reject.c',
        note='if controlling expression must be scalar (struct expression should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_while_void_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_while_void_condition_reject.c',
        note='while controlling expression must be scalar (void expression should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_do_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_do_struct_condition_reject.c',
        note='do-while controlling expression must be scalar (struct expression should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_for_void_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_for_void_condition_reject.c',
        note='for controlling expression must be scalar (void expression should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_for_struct_condition_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_for_struct_condition_reject.c',
        note='for controlling expression must be scalar (struct expression should reject)',
    ),
    DiagnosticProbe(
        probe_id='09__probe_if_missing_then_stmt_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_if_missing_then_stmt_reject.c',
        note='if statement missing required controlled statement should be rejected',
    ),
    DiagnosticProbe(
        probe_id='09__probe_else_missing_stmt_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_else_missing_stmt_reject.c',
        note='else arm missing required statement should be rejected',
    ),
    DiagnosticProbe(
        probe_id='09__probe_switch_missing_rparen_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_switch_missing_rparen_reject.c',
        note="switch controlling expression missing ')' should be rejected",
    ),
    DiagnosticProbe(
        probe_id='09__probe_for_missing_first_semicolon_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_for_missing_first_semicolon_reject.c',
        note="for header missing first ';' separator should be rejected",
    ),
    DiagnosticProbe(
        probe_id='09__probe_goto_undefined_label_nested_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_goto_undefined_label_nested_reject.c',
        note='goto to undefined label in nested control flow should be rejected',
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_break_outside_loop_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_break_outside_loop_rich_presence.c',
        note='strict frontier: break-outside-loop diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5002,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_break_outside_loop_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_break_outside_loop_rich_presence.c',
        note='reduced threshold: break-outside-loop diagnostics JSON under #line remap emits semantic diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_continue_outside_loop_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_continue_outside_loop_rich_presence.c',
        note='strict frontier: continue-outside-loop diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5102,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_continue_outside_loop_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_continue_outside_loop_rich_presence.c',
        note='reduced threshold: continue-outside-loop diagnostics JSON under #line remap emits semantic diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_break_outside_loop_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_break_outside_loop_rich_presence.c',
        note='strict frontier: include-header break-outside-loop diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_break_outside_loop_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_break_outside_loop_rich_presence.c',
        note='reduced threshold: include-header break-outside-loop diagnostics JSON under #line remap emits semantic diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_continue_outside_loop_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_continue_outside_loop_rich_presence.c',
        note='strict frontier: include-header continue-outside-loop diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_continue_outside_loop_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_continue_outside_loop_rich_presence.c',
        note='reduced threshold: include-header continue-outside-loop diagnostics JSON under #line remap emits semantic diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_multiple_default_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_multiple_default_rich_presence.c',
        note='strict frontier: previous-default warning location in diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5604,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_multiple_default_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_multiple_default_rich_presence.c',
        note='reduced threshold: switch-multiple-default diagnostics JSON under #line remap emits diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_duplicate_case_folded_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_duplicate_case_folded_rich_presence.c',
        note='strict frontier: previous-case warning location in diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5704,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_duplicate_case_folded_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_duplicate_case_folded_rich_presence.c',
        note='reduced threshold: switch-duplicate-case-folded diagnostics JSON under #line remap emits diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_pointer_condition_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_pointer_condition_file_presence_reject.c',
        note='strict frontier: #line pointer switch-condition diagnostics JSON should include has_file',
        expected_codes=[2000],
        expected_line=7905,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_pointer_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_pointer_condition_file_presence_reject.c',
        note='reduced threshold: #line pointer switch-condition diagnostics JSON should emit diagnostic payload at remapped line',
        expected_codes=[2000],
        expected_line=7905,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject.c',
        note='strict frontier: include-header #line pointer switch-condition diagnostics JSON should include has_file',
        expected_codes=[2000],
        expected_line=7915,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject.c', PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_switch_pointer_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject.c',
        note='reduced threshold: include-header #line pointer switch-condition diagnostics JSON should emit diagnostic payload at remapped line',
        expected_codes=[2000],
        expected_line=7915,
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject.c', PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_pointer_condition_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_string_condition_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_string_condition_file_presence_reject.c',
        note='strict frontier: #line string-literal switch-condition diagnostics JSON should include has_file',
        expected_codes=[2000],
        expected_line=7923,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_string_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_string_condition_file_presence_reject.c',
        note='reduced threshold: #line string-literal switch-condition diagnostics JSON should emit diagnostic payload at remapped line',
        expected_codes=[2000],
        expected_line=7923,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject.c',
        note='strict frontier: include-header #line string-literal switch-condition diagnostics JSON should include has_file',
        expected_codes=[2000],
        expected_line=7933,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject.c', PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_switch_string_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject.c',
        note='reduced threshold: include-header #line string-literal switch-condition diagnostics JSON should emit diagnostic payload at remapped line',
        expected_codes=[2000],
        expected_line=7933,
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject.c', PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_string_condition_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_double_condition_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_double_condition_file_presence_reject.c',
        note='strict frontier: #line double switch-condition diagnostics JSON should include has_file',
        expected_codes=[2000],
        expected_line=7944,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_switch_double_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_switch_double_condition_file_presence_reject.c',
        note='reduced threshold: #line double switch-condition diagnostics JSON should emit diagnostic payload at remapped line',
        expected_codes=[2000],
        expected_line=7944,
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject.c',
        note='strict frontier: include-header #line double switch-condition diagnostics JSON should include has_file',
        expected_codes=[2000],
        expected_line=7954,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject.c', PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='09__probe_diagjson_line_directive_include_switch_double_condition_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject.c',
        note='reduced threshold: include-header #line double switch-condition diagnostics JSON should emit diagnostic payload at remapped line',
        expected_codes=[2000],
        expected_line=7954,
        inputs=[PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject.c', PROBE_DIR / 'diagnostics/09__probe_diagjson_line_directive_include_switch_double_condition_file_presence_reject.h'],
    ),
]
