from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='08__probe_runtime_designated_override_zero_fill',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designated_override_zero_fill.c',
        note='designated initializer override order and implicit zero-fill should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_brace_elision_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_brace_elision_matrix.c',
        note='nested aggregate brace elision should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_designator_selection',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_designator_selection.c',
        note='union designated-member selection inside aggregate initializers should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_sparse_designator_checksum_grid',
        source=PROBE_DIR / 'runtime/08__probe_runtime_sparse_designator_checksum_grid.c',
        note='sparse array designated initializers and implicit zero-fill should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_designator_override_chain',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_designator_override_chain.c',
        note='nested designated initializer override chains should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_designator_bridge',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_designator_bridge.c',
        note='bitfield-bearing aggregate designated initializers should preserve values and implicit zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_sparse_zero_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_sparse_zero_mesh.c',
        note='sparse designated bitfield array initializers should preserve zero-fill and runtime layout behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_string_zero_tail_checksum',
        source=PROBE_DIR / 'runtime/08__probe_runtime_string_zero_tail_checksum.c',
        note='char array string initializers should preserve trailing zero-fill and exact-length payload semantics',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_struct_string_designator_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_struct_string_designator_matrix.c',
        note='struct-contained char-array designated initializers should preserve trailing zero bytes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_sparse_inferred_bound_extent',
        source=PROBE_DIR / 'runtime/08__probe_runtime_sparse_inferred_bound_extent.c',
        note='highest-index sparse array designators should infer correct array bounds and zero-fill gaps',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_struct_array_inferred_bound_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_struct_array_inferred_bound_mesh.c',
        note='sparse designated arrays of aggregates should infer bounds and preserve nested zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_padding_checksum_lattice',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_padding_checksum_lattice.c',
        note='bitfield-bearing aggregates with padding-sensitive sparse stores should preserve zero-fill and checksum stability',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_string_member_switch',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_string_member_switch.c',
        note='union char-array members inside aggregates should preserve designated string payloads and trailing zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_sparse_row_checksum',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_sparse_row_checksum.c',
        note='nested sparse aggregate rows should infer outer bounds correctly and preserve nested zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_last_write_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_last_write_matrix.c',
        note='repeated nested designators should obey last-write-wins semantics across aggregate subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_address_constant_bridge',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_address_constant_bridge.c',
        note='file-scope aggregate initializers should accept address constants for objects, functions, and sparse zero-filled entries',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_overlay_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_overlay_mesh.c',
        note='nested union string payloads inside aggregate arrays should preserve trailing zero-fill and designated payload ordering',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_nested_designator_fanout',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_nested_designator_fanout.c',
        note='nested bitfield array designators inside aggregates should preserve sparse writes, padding, and zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_last_write_overlap_lattice',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_last_write_overlap_lattice.c',
        note='broader overlapping nested designators should preserve last-write-wins behavior across array-of-struct subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_nested_address_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_nested_address_matrix.c',
        note='nested file-scope aggregate address-constant initializers should preserve function and object references across sparse subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_feedback_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_feedback_mesh.c',
        note='deeper nested union string overlays should preserve trailing zero-fill and char-member rewrites inside aggregate arrays',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_mixed_designator_replay',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_mixed_designator_replay.c',
        note='mixed whole-element and subfield bitfield designators should preserve replay order and zero-fill semantics',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_last_write_chain_grid',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_last_write_chain_grid.c',
        note='broader nested array-of-struct overlap chains should preserve last-write-wins behavior under repeated designator rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_pointer_fanout_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_pointer_fanout_mesh.c',
        note='file-scope nested pointer and function-pointer aggregates should preserve sparse address-constant fanout across subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_rewrite_lattice',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_rewrite_lattice.c',
        note='deeper nested union string rewrites should preserve whole-string initialization followed by subfield character overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_padding_relay_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_padding_relay_mesh.c',
        note='padding-sensitive nested bitfield relays should preserve mixed element and subfield designator stores',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_cascade_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_cascade_matrix.c',
        note='broader overlap cascades across nested array-of-struct rows should preserve last-write-wins behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_pointer_label_fanout_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_pointer_label_fanout_mesh.c',
        note='deeper file-scope pointer and string-label fanout should preserve sparse address constants and function-pointer payloads across nested subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_multiswitch_lattice',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_multiswitch_lattice.c',
        note='nested union string payloads with repeated member switches should preserve whole-union override semantics across later char-field rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_padding_relay_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_padding_relay_cube.c',
        note='denser nested bitfield padding relays across three-dimensional arrays should preserve sparse writes and zero-fill stability',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_cube.c',
        note='broader three-dimensional overlap cascades should preserve last-write-wins behavior across nested array-of-struct chains',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_callback_alias_grid',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_callback_alias_grid.c',
        note='deeper file-scope callback and alias grids should preserve sparse pointer and function-pointer fanout across nested aggregates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_feedback_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_feedback_cube.c',
        note='nested union string grids with feedback rewrites should preserve whole-union override semantics and trailing zero-fill stability',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_sparse_replay_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_sparse_replay_cube.c',
        note='sparser three-dimensional bitfield replay grids should preserve zero-fill and repeated subfield override ordering',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_shadow_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_shadow_cube.c',
        note='broader designator shadow cubes should preserve last-write-wins behavior across nested repeated rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_subaggregate_rewrite_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_subaggregate_rewrite_mesh.c',
        note='file-scope subaggregate rewrites should preserve later whole-element replacement after earlier nested pointer and callback writes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_whole_element_rewrite_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_whole_element_rewrite_mesh.c',
        note='whole-union element rewrites should override earlier nested member writes and preserve final active-member bytes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_whole_element_rewrite_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_whole_element_rewrite_mesh.c',
        note='whole-element bitfield rewrites should override earlier subfield writes and preserve later sparse element payloads',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_plane_rewrite_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_plane_rewrite_mesh.c',
        note='whole-plane designator rewrites should override earlier cell writes while preserving later writes in other planes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_pointer_subaggregate_relay_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_pointer_subaggregate_relay_cube.c',
        note='deeper file-scope pointer and address-constant subaggregate relays should preserve later whole-subaggregate rewrites across nested arrays',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_member_switch_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_member_switch_cube.c',
        note='nested union string payloads with repeated member switches should preserve whole-union rewrites and later character overrides across deeper grids',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_padding_rewrite_lattice',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_padding_rewrite_lattice.c',
        note='denser padding-sensitive bitfield rewrites should preserve sparse whole-element and subfield override ordering across nested arrays',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_hypercube.c',
        note='larger overlap chains should preserve last-write-wins behavior across nested array-of-struct hypercube rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_pointer_callback_plane_rewrite_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_pointer_callback_plane_rewrite_hypercube.c',
        note='deeper file-scope pointer and callback plane rewrites should preserve whole-plane replacement semantics across nested aggregates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_address_alias_reseed_lattice',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_address_alias_reseed_lattice.c',
        note='file-scope address-constant alias reseeds should preserve later whole-subaggregate rewrites across nested pointer tables',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_reswitch_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_reswitch_hypercube.c',
        note='nested union string hypercubes should preserve repeated member switches and later char overrides in reused subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_row_reseed_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_row_reseed_cube.c',
        note='nested union string row reseeds should preserve whole-row rewrites and later per-cell character overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_padding_plane_rewrite_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_padding_plane_rewrite_hypercube.c',
        note='bitfield padding plane rewrites should preserve whole-plane replacement semantics and later sparse subfield updates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_padding_row_reseed_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_padding_row_reseed_hypercube.c',
        note='bitfield padding row reseeds should preserve repeated row rewrites and later subfield replay ordering',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_union_struct_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_union_struct_hypercube.c',
        note='overlap hypercubes across union-bearing structs should preserve last-write-wins behavior under nested row and cell rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_union_rowplane_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_union_rowplane_cube.c',
        note='union-bearing row and plane rewrites should preserve later overlap dominance across nested aggregate cubes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_pointer_subobject_ladder_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_pointer_subobject_ladder_hypercube.c',
        note='file-scope pointer ladder hypercubes should preserve repeated whole-subobject rewrites and later callback reseeds across nested aggregates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_address_plane_rewrite_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_address_plane_rewrite_ladder.c',
        note='file-scope address-constant plane rewrite ladders should preserve whole-plane reseeds and later sparse pointer overrides across nested tables',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_member_reswitch_plane',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_member_reswitch_plane.c',
        note='nested union string member reswitch planes should preserve repeated active-member switching in reused subobjects with later char overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_member_feedback_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_member_feedback_hypercube.c',
        note='nested union string feedback hypercubes should preserve whole-row and whole-cell rewrites across reused union-bearing subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_struct_relay_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_struct_relay_hypercube.c',
        note='array-of-struct bitfield relay hypercubes should preserve dense whole-cell and subfield rewrite ordering across nested planes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_struct_row_rewrite_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_struct_row_rewrite_ladder.c',
        note='array-of-struct bitfield row rewrite ladders should preserve repeated whole-row resets and later sparse relay overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_subobject_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_subobject_ladder.c',
        note='subobject overlap ladders should preserve last-write-wins behavior across repeated whole-struct and nested-cell rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_union_feedback_plane',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_union_feedback_plane.c',
        note='union-bearing overlap feedback planes should preserve dominance of later rewrites across mixed row, plane, and cell-level updates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_callback_address_feedback_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_callback_address_feedback_hypercube.c',
        note='file-scope callback/address feedback hypercubes should preserve repeated whole-subobject rewrites with later callback and alias overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_pointer_plane_reset_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_pointer_plane_reset_ladder.c',
        note='file-scope pointer plane reset ladders should preserve whole-plane resets and later sparse pointer reseeds across nested aggregates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_union_string_bitfield_feedback_mesh',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_union_string_bitfield_feedback_mesh.c',
        note='strict frontier: file-scope nested initializers should preserve string-byte overrides, whole-union rewrites, sparse zero-fill, and later separate bitfield-field writes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_file_scope_union_string_bitfield_current_sparse_pass',
        source=PROBE_DIR / 'runtime/08__probe_runtime_file_scope_union_string_bitfield_current_sparse_pass.c',
        note='reduced threshold: file-scope nested initializers should preserve string-byte overrides, whole-union rewrites, sparse zero-fill, and whole-bitfield-subobject layout',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_member_multireset_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_member_multireset_cube.c',
        note='nested union string multireset cubes should preserve repeated active-member switching and later char overrides in reused cells',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_string_member_plane_feedback_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_string_member_plane_feedback_hypercube.c',
        note='nested union string plane feedback hypercubes should preserve whole-plane and whole-cell rewrites across reused union-bearing subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_struct_plane_reset_hypercube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_struct_plane_reset_hypercube.c',
        note='array-of-struct bitfield plane reset hypercubes should preserve dense whole-plane resets with later sparse relay overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_bitfield_struct_feedback_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_bitfield_struct_feedback_ladder.c',
        note='array-of-struct bitfield feedback ladders should preserve repeated row and cell rewrites with later subfield relay updates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_whole_subobject_feedback_cube',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_whole_subobject_feedback_cube.c',
        note='whole-subobject overlap feedback cubes should preserve last-write-wins behavior across mixed whole-struct and nested-cell rewrites',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_designator_overlap_union_struct_plane_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designator_overlap_union_struct_plane_ladder.c',
        note='union-bearing overlap plane ladders should preserve dominance of later rewrites across row, plane, and cell-level updates',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_zero_fill_ladder_wave71',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_zero_fill_ladder_wave71.c',
        note='nested aggregate sparse designators should preserve recursive zero-fill across omitted sibling subobjects',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_string_continuation_ladder_wave71',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_string_continuation_ladder_wave71.c',
        note='union string initializers with later byte continuations should preserve active-member bytes and zero-filled tail storage',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_bitfield_continuation_grid_wave71',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_bitfield_continuation_grid_wave71.c',
        note='union payload plus bitfield subobject continuations should preserve mixed sparse writes and zero-fill in reused aggregate cells',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_anonymous_union_struct_layout_checksum_wave72',
        source=PROBE_DIR / 'runtime/08__probe_runtime_anonymous_union_struct_layout_checksum_wave72.c',
        note='strict frontier: anonymous struct/union aggregate initializers should preserve recursive zero-fill, offsetof aliases, and runtime checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_named_union_struct_layout_checksum_wave72',
        source=PROBE_DIR / 'runtime/08__probe_runtime_named_union_struct_layout_checksum_wave72.c',
        note='reduced threshold: named struct/union aggregate initializers should preserve zero-fill, layout offsets, and runtime checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_array_union_zero_fill_checksum_wave72',
        source=PROBE_DIR / 'runtime/08__probe_runtime_array_union_zero_fill_checksum_wave72.c',
        note='arrays of unions with sparse designated aggregate initialization should preserve zero-fill, offsetof layout, and runtime checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_union_array_payload_wave73',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_union_array_payload_wave73.c',
        note='nested arrays of named-union payloads should preserve sparse designators, recursive zero-fill, offsetof layout, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_anonymous_union_layout_current_wave73',
        source=PROBE_DIR / 'runtime/08__probe_runtime_anonymous_union_layout_current_wave73.c',
        note='reduced threshold: anonymous struct/union aggregate initialization should preserve active-member byte layout, zero-fill, and checksum parity with clang before later member reseed',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_row_reseed_byte_offsets_wave73',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_row_reseed_byte_offsets_wave73.c',
        note='union string and byte-array row reseeds should preserve trailing zero-fill, later byte overrides, offsetof layout, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave74_designated_union_matrix_checksum',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave74_designated_union_matrix_checksum.c',
        note='nested designated union matrices should preserve sparse writes, recursive zero-fill, offsetof layout, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave74_partial_zero_fill_union_rows',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave74_partial_zero_fill_union_rows.c',
        note='partial aggregate initializers across named union rows should preserve omitted-byte zero-fill and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave74_nested_designator_reseed_payload',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave74_nested_designator_reseed_payload.c',
        note='nested union payload reseeds through later member designators should preserve final byte layout and zero-fill parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave74_union_array_member_override',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave74_union_array_member_override.c',
        note='fixed baseline: nested two-dimensional union array member overrides preserve active storage bytes, trailing zero-fill, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave74_union_array_member_override_current',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave74_union_array_member_override_current.c',
        note='reduced threshold: flat union array member overrides preserve active storage bytes, trailing zero-fill, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave75_compound_literal_union_grid',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave75_compound_literal_union_grid.c',
        note='current threshold: nested union grids should preserve later member overrides, omitted-byte zero-fill, offsetof layout, and checksum parity with clang after reducing blocked compound-literal designator form',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave75_union_row_override_zero_fill',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave75_union_row_override_zero_fill.c',
        note='nested union row overrides should preserve last-write active storage, recursive zero-fill, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave75_nested_array_designator_reseed',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave75_nested_array_designator_reseed.c',
        note='nested two-dimensional array designator reseeds should preserve union active-member layout and final checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave75_compound_literal_current_zero_fill',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave75_compound_literal_current_zero_fill.c',
        note='current threshold: compound literal union assignment should preserve active-member zero-fill and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave75_compound_literal_nested_designator_fixed',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave75_compound_literal_nested_designator_fixed.c',
        note='fixed baseline: compound literal chained field/index designators should preserve nested union array storage and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave76_compound_literal_nested_rows',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave76_compound_literal_nested_rows.c',
        note='wave76: nested compound literals inside aggregate rows should preserve union payload layout, omitted-byte zero-fill, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave76_union_row_designator_overrides',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave76_union_row_designator_overrides.c',
        note='strict blocker: union row designator overrides should preserve last-write active-member storage and zero-filled untouched rows after whole-row and later subobject initializers',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave76_union_row_designator_overrides_current',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave76_union_row_designator_overrides_current.c',
        note='wave76 current threshold: direct union row member designators preserve active-member storage and zero-filled untouched rows',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave76_zero_fill_layout_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave76_zero_fill_layout_ladder.c',
        note='wave76: nested aggregate zero-fill ladders should preserve layout offsets and omitted subobject bytes across union rows',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave76_nested_array_member_preservation',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave76_nested_array_member_preservation.c',
        note='wave76: nested array/member initializer preservation should keep member slot bytes and union storage layout stable',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave77_named_union_row_slot_ordering',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave77_named_union_row_slot_ordering.c',
        note='wave77: named union row/slot initializer ordering should preserve last-write storage, omitted-row zero-fill, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave77_compound_literal_zero_fill_slots',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave77_compound_literal_zero_fill_slots.c',
        note='wave77: compound literal union slots should preserve omitted-byte zero-fill and nested payload checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave77_anonymous_union_layout_checksum',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave77_anonymous_union_layout_checksum.c',
        note='wave77: anonymous struct/union layout checksums should preserve sparse designated initializer bytes and zero-fill parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave77_nested_union_array_designated_checksum',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave77_nested_union_array_designated_checksum.c',
        note='wave77: nested designated union arrays should preserve row/slot sparse writes, recursive zero-fill, and layout checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave78_nested_aggregate_override_payload',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave78_nested_aggregate_override_payload.c',
        note='wave78: nested aggregate override boundaries should preserve last-write payloads, omitted zero-fill, and layout checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave78_union_array_string_bitfield_payload',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave78_union_array_string_bitfield_payload.c',
        note='wave78: union arrays mixing string and bitfield payload designators should preserve active member values and zero-fill parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave78_designated_override_boundary_checksum',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave78_designated_override_boundary_checksum.c',
        note='wave78: designated initializer override boundaries across union member views should preserve final byte payload checksums',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave78_string_bitfield_nested_zero_fill',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave78_string_bitfield_nested_zero_fill.c',
        note='wave78: nested string and bitfield initializers should preserve recursive zero-fill and later subobject byte overrides',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave79_compound_literal_payload_reseed',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave79_compound_literal_payload_reseed.c',
        note='wave79: compound literal payload reseeds should preserve nested union bytes, recursive zero-fill, and checksum parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave79_designated_override_zero_fill_ladder',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave79_designated_override_zero_fill_ladder.c',
        note='wave79: designated whole-subobject overrides should preserve last-write payloads, omitted zero-fill, and nested layout checksums',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave79_union_array_bitfield_payload',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave79_union_array_bitfield_payload.c',
        note='wave79: union arrays mixing string and bitfield payloads should preserve active-member values and zero-fill parity with clang',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave79_nested_payload_ir_seed',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave79_nested_payload_ir_seed.c',
        note='wave79: nested payload shapes with compound literals and aggregate copies should preserve layout for later bucket 13 IR checks',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave80_nested_union_array_ir_payload_current',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave80_nested_union_array_ir_payload_current.c',
        note='wave80 current-threshold companion: nested union array payload copies should preserve byte payloads for later bucket 13 IR behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave80_block_scope_compound_literal_return_payload',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave80_block_scope_compound_literal_return_payload.c',
        note='wave80: block-scope compound literal return-slot copies should preserve later union payload reseeds and zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave80_designated_whole_subobject_union_array',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave80_designated_whole_subobject_union_array.c',
        note='wave80: designated whole-subobject replacement over nested union arrays should preserve final active payload bytes',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave80_bitfield_payload_checksum_ir_seed_current',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave80_bitfield_payload_checksum_ir_seed_current.c',
        note='wave80 current-threshold companion: logical bitfield payload checksums should preserve nested aggregate values for later bucket 13 IR payload behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave81_file_scope_compound_literal_pointer',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave81_file_scope_compound_literal_pointer.c',
        note='wave81: file-scope address-of compound literals should preserve nested designated union payloads',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave81_file_scope_compound_literal_pointer_current',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave81_file_scope_compound_literal_pointer_current.c',
        note='wave81 current-threshold companion: direct static aggregates preserve the same nested designated union payloads',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave81_union_byte_zero_fill_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave81_union_byte_zero_fill_matrix.c',
        note='wave81: nested union raw-byte overlays should retain designated stores and implicit zero-fill',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave81_bitfield_array_member_readback',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave81_bitfield_array_member_readback.c',
        note='wave81: bitfield array aggregate initializers should retain member values and zero-filled fields',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave81_nested_designated_brace_elision',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave81_nested_designated_brace_elision.c',
        note='wave81: nested designators and brace elision should agree on aggregate element and zero-fill placement',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave82_static_nested_union_array_overwrite',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave82_static_nested_union_array_overwrite.c',
        note='wave82: static nested union arrays should retain last-write-wins whole-cell and nested-member designator ordering',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave82_file_scope_array_subobject_addresses',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave82_file_scope_array_subobject_addresses.c',
        note='wave82: file-scope address constants through nested array subobjects should preserve pointer identity and stores',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave82_file_scope_array_subobject_addresses_current',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave82_file_scope_array_subobject_addresses_current.c',
        note='wave82 current-threshold companion: direct scalar-array elements preserve file-scope address constants and stores',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave82_nested_layout_offset_alignment',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave82_nested_layout_offset_alignment.c',
        note='wave82: nested union aggregate initialization should agree with offsetof, size, and alignment readback',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave83_initializer_identity_same_name_shadow',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave83_initializer_identity_same_name_shadow.c',
        note='wave83: local nested designated union-array initialization should use the exact inner same-name aggregate definition',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave83_initializer_identity_unique_name_control',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave83_initializer_identity_unique_name_control.c',
        note='wave83 alpha control: the same local nested initializer should retain its layout when the inner aggregate has a unique name',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave84_preserved_typedef_initializer_same_name_shadow',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave84_preserved_typedef_initializer_same_name_shadow.c',
        note='wave84 strict: a typedef frozen before same-name tag shadowing should preserve its outer aggregate definition for a later designated declaration initializer',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_wave84_preserved_typedef_initializer_unique_name_control',
        source=PROBE_DIR / 'runtime/08__probe_runtime_wave84_preserved_typedef_initializer_unique_name_control.c',
        note='wave84 alpha control: the same preserved-typedef declaration initializer should match when the inner tag has a unique name',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='08__probe_designator_unknown_field_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_designator_unknown_field_reject.c',
        note='designated initializer should reject unknown field names',
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_designator_array_nonconst_probe_diag_text.c:4802:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_designator_array_negative_probe_diag_text.c:4901:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: include-header non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_designator_array_nonconst_probe_diag_text.h:5002:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: include-header non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: include-header negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_designator_array_negative_probe_diag_text.h:5101:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: include-header negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: nested non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_nested_designator_array_nonconst_probe_diag_text.c:6402:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: nested non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: include-header nested non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_nested_designator_array_nonconst_probe_diag_text.h:6502:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: include-header nested non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: nested negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_nested_designator_array_negative_probe_diag_text.c:6601:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: nested negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: include-header nested negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_nested_designator_array_negative_probe_diag_text.h:6701:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: include-header nested negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_flex_not_last_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_flex_not_last_spelling_strict.c',
        note='strict frontier: flex-not-last text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_flex_not_last_probe_diag_text.c:5902:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_flex_not_last_spelling_strict.c',
        note='reduced threshold: flex-not-last text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array member must be the last field in a struct'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_flex_not_last_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c',
        note='strict frontier: include-header flex-not-last text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_flex_not_last_probe_diag_text.h:6002:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c',
        note='reduced threshold: include-header flex-not-last text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array member must be the last field in a struct'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_union_flex_member_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_union_flex_member_spelling_strict.c',
        note='strict frontier: union flexible-member text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_union_flex_member_probe_diag_text.c:6102:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_union_flex_member_spelling_strict.c',
        note='reduced threshold: union flexible-member text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array members are not allowed in unions'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_union_flex_member_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c',
        note='strict frontier: include-header union flexible-member text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_union_flex_member_probe_diag_text.h:6202:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c',
        note='reduced threshold: include-header union flexible-member text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array members are not allowed in unions'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_unknown_field_rich_presence.c',
        note='strict frontier: designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3006:39): Unknown field 'missing' in designated initializer for 'value'",
            'Spelling: virtual_init_designator_unknown_field_probe.c:3006:39',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_oob_rich_presence.c',
        note='strict frontier: designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3101:16): Array 'arr' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_designator_array_oob_probe.c:3101:16',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3406:39): Unknown field 'missing' in designated initializer for 'value'",
            'Spelling: virtual_init_include_designator_unknown_field_probe.h:3406:39',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_oob_rich_presence.c',
        note='strict frontier: include-header designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3501:16): Array 'arr' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_include_designator_array_oob_probe.h:3501:16',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_oob_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_oob_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: nested designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4006:20): Unknown field 'missing' in designated initializer for 'g'",
            'Spelling: virtual_init_nested_designator_unknown_field_probe.c:4006:20',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: nested designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4103:10): Array 'grid' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_nested_designator_array_oob_probe.c:4103:10',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header nested designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4206:20): Unknown field 'missing' in designated initializer for 'g'",
            'Spelling: virtual_init_include_nested_designator_unknown_field_probe.h:4206:20',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: include-header nested designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4303:10): Array 'grid' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_include_nested_designator_array_oob_probe.h:4303:10',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_designated_nonconst_reject.c',
        note='file-scope designated initializer should reject non-constant field expressions',
        required_substrings=["Initializer for static variable 'g' is not a constant expression"],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_include_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c',
        note='include-header file-scope designated initializer should reject non-constant field expressions',
        required_substrings=["Initializer for static variable 'g' is not a constant expression"],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_nested_designated_nonconst_reject.c',
        note='file-scope nested designated initializer should reject non-constant aggregate field expressions',
        required_substrings=["Initializer for static variable 'state' is not a constant expression"],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_include_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c',
        note='include-header file-scope nested designated initializer should reject non-constant aggregate field expressions',
        required_substrings=["Initializer for static variable 'state' is not a constant expression"],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_array_excess_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_array_excess_spelling_reject.c',
        note='strict frontier: excess array initializer diagnostics under #line remap should preserve spelling file/line',
        required_substrings=[
            "Error at (7201:0): Too many initializers for array 'a' (size 2)",
            'Spelling: virtual_init_array_excess_probe.c:7201:0',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_array_excess_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_array_excess_spelling_reject.c',
        note='reduced threshold: excess array initializer diagnostics should emit semantic rejection message',
        required_substrings=["Too many initializers for array 'a' (size 2)"],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_array_excess_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c',
        note='strict frontier: include-header excess array initializer diagnostics under #line remap should preserve spelling file/line',
        required_substrings=[
            "Error at (7211:0): Too many initializers for array 'a' (size 2)",
            'Spelling: virtual_init_include_array_excess_probe.h:7211:0',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_array_excess_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c',
        note='reduced threshold: include-header excess array initializer diagnostics should emit semantic rejection message',
        required_substrings=["Too many initializers for array 'a' (size 2)"],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_string_too_long_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_string_too_long_spelling_reject.c',
        note='strict frontier: string-too-long initializer diagnostics under #line remap should preserve spelling file/line',
        required_substrings=[
            "Error at (7301:0): String literal for array 'a' is too long (needs 4, size 2)",
            'Spelling: virtual_init_string_too_long_probe.c:7301:0',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_string_too_long_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_string_too_long_spelling_reject.c',
        note='reduced threshold: string-too-long initializer diagnostics should emit semantic rejection message',
        required_substrings=["String literal for array 'a' is too long (needs 4, size 2)"],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_string_too_long_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c',
        note='strict frontier: include-header string-too-long initializer diagnostics under #line remap should preserve spelling file/line',
        required_substrings=[
            "Error at (7311:0): String literal for array 'a' is too long (needs 4, size 2)",
            'Spelling: virtual_init_include_string_too_long_probe.h:7311:0',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_string_too_long_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c',
        note='reduced threshold: include-header string-too-long initializer diagnostics should emit semantic rejection message',
        required_substrings=["String literal for array 'a' is too long (needs 4, size 2)"],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.h'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_unknown_field_rich_presence.c',
        note='strict frontier: designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3006,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_unknown_field_rich_presence.c',
        note='reduced threshold: designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_oob_rich_presence.c',
        note='strict frontier: designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3101,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_oob_rich_presence.c',
        note='reduced threshold: designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3406,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c',
        note='reduced threshold: include-header designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_oob_rich_presence.c',
        note='strict frontier: include-header designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3501,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_oob_rich_presence.c',
        note='reduced threshold: include-header designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: nested designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4006,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_unknown_field_rich_presence.c',
        note='reduced threshold: nested designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: nested designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_oob_rich_presence.c',
        note='reduced threshold: nested designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header nested designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4206,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c',
        note='reduced threshold: include-header nested designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: include-header nested designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c',
        note='reduced threshold: include-header nested designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_negative_rich_presence.c',
        note='strict frontier: negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4501,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: include-header non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4602,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: include-header non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c',
        note='strict frontier: include-header negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4701,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: include-header negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: nested non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: nested non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: include-header nested non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6502,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: include-header nested non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_negative_rich_presence.c',
        note='strict frontier: nested negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6602,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: nested negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c',
        note='strict frontier: include-header nested negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6702,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: include-header nested negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_flex_not_last_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_flex_not_last_rich_presence.c',
        note='strict frontier: flex-not-last diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_flex_not_last_rich_presence.c',
        note='reduced threshold: flex-not-last diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_flex_not_last_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c',
        note='strict frontier: include-header flex-not-last diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5602,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c',
        note='reduced threshold: include-header flex-not-last diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_union_flex_member_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_union_flex_member_rich_presence.c',
        note='strict frontier: union flexible-member diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5702,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_union_flex_member_rich_presence.c',
        note='reduced threshold: union flexible-member diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_union_flex_member_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c',
        note='strict frontier: include-header union flexible-member diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5802,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c',
        note='reduced threshold: include-header union flexible-member diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_designated_nonconst_reject.c',
        note='diagnostics JSON should include file-scope designated non-constant initializer rejection',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_include_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c',
        note='diagnostics JSON should include include-header file-scope designated non-constant initializer rejection',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_nested_designated_nonconst_reject.c',
        note='diagnostics JSON should include file-scope nested designated non-constant initializer rejection',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_include_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c',
        note='diagnostics JSON should include include-header file-scope nested designated non-constant initializer rejection',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_array_excess_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_array_excess_spelling_reject.c',
        note='strict frontier: excess array initializer diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=7201,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_array_excess_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_array_excess_spelling_reject.c',
        note='reduced threshold: excess array initializer diagnostics JSON should emit semantic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_array_excess_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c',
        note='strict frontier: include-header excess array initializer diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=7211,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_array_excess_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c',
        note='reduced threshold: include-header excess array initializer diagnostics JSON should emit semantic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_array_excess_spelling_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_string_too_long_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_string_too_long_spelling_reject.c',
        note='strict frontier: string-too-long initializer diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=7301,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_string_too_long_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_string_too_long_spelling_reject.c',
        note='reduced threshold: string-too-long initializer diagnostics JSON should emit semantic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_string_too_long_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c',
        note='strict frontier: include-header string-too-long initializer diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=7311,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_string_too_long_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c',
        note='reduced threshold: include-header string-too-long initializer diagnostics JSON should emit semantic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_string_too_long_spelling_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_wave85_diagjson_factory_fnptr_array_initializer_tag_same_name_strict',
        source=PROBE_DIR / 'diagnostics/08__probe_wave85_diagjson_factory_fnptr_array_initializer_tag_same_name.c',
        note='wave85 strict: an array element initializer must reject a typedef-wrapped factory whose returned callback captures a distinct same-spelled aggregate tag',
        expected_codes=[2000],
        expected_line=18816,
        fisics_env={'DISABLE_CODEGEN': '1'},
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_wave85_diagjson_factory_fnptr_array_initializer_tag_alpha_name_strict',
        source=PROBE_DIR / 'diagnostics/08__probe_wave85_diagjson_factory_fnptr_array_initializer_tag_alpha_name.c',
        note='wave85 alpha control: renaming the nested callback parameter tag must preserve the incompatible factory array-element initializer diagnostic',
        expected_codes=[2000],
        expected_line=18816,
        fisics_env={'DISABLE_CODEGEN': '1'},
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_wave85_diagjson_factory_fnptr_array_initializer_compatible_control_clean',
        source=PROBE_DIR / 'diagnostics/08__probe_wave85_diagjson_factory_fnptr_array_initializer_compatible_control.c',
        note='wave85 clean control: typedef-wrapped factories remain compatible as array elements when returned callbacks share one aggregate parameter identity',
        require_any_diagnostic=False,
        fisics_env={'DISABLE_CODEGEN': '1'},
    ),
]
