from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='07__probe_agg_member_access_runtime',
        source=PROBE_DIR / 'runtime/07__probe_agg_member_access_runtime.c',
        note="nested struct member access via '.' and '->' should match clang runtime behavior",
    ),
    RuntimeProbe(
        probe_id='07__probe_agg_offsets_runtime',
        source=PROBE_DIR / 'runtime/07__probe_agg_offsets_runtime.c',
        note='offsetof ordering and stride invariants should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_signed_unsigned_compare_boundary_runtime',
        source=PROBE_DIR / 'runtime/07__probe_signed_unsigned_compare_boundary_runtime.c',
        note='signed/unsigned boundary comparison matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_agg_nested_offsets_runtime',
        source=PROBE_DIR / 'runtime/07__probe_agg_nested_offsets_runtime.c',
        note='nested aggregate offsetof/stride invariants should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_signed_unsigned_compare_long_boundary_runtime',
        source=PROBE_DIR / 'runtime/07__probe_signed_unsigned_compare_long_boundary_runtime.c',
        note='long/unsigned-long and long-long/unsigned-long-long comparison boundary matrix should match clang',
    ),
    RuntimeProbe(
        probe_id='07__probe_null_pointer_constant_runtime',
        source=PROBE_DIR / 'runtime/07__probe_null_pointer_constant_runtime.c',
        note='integer constant zero should act as null pointer constant in initialization and conditional expressions',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_array_size_positive_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_array_size_positive_runtime.c',
        note='file-scope array bounds with integer constant expressions should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_case_label_positive_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_case_label_positive_runtime.c',
        note='switch case labels using integer constant expressions should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_static_init_positive_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_static_init_positive_runtime.c',
        note='static-storage initializers using integer constant expressions should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_agg_union_nested_member_runtime',
        source=PROBE_DIR / 'runtime/07__probe_agg_union_nested_member_runtime.c',
        note='nested struct-in-union member paths should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_agg_union_copy_update_runtime',
        source=PROBE_DIR / 'runtime/07__probe_agg_union_copy_update_runtime.c',
        note='aggregate copy/update through nested union-member paths should match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_cast_ptr_uintptr_roundtrip_runtime',
        source=PROBE_DIR / 'runtime/07__probe_cast_ptr_uintptr_roundtrip_runtime.c',
        note='explicit pointer<->uintptr_t cast roundtrip should match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_enum_cast_sizeof_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_enum_cast_sizeof_runtime.c',
        note='nested enum/cast/sizeof constant-expression forms should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_large_bound_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_large_bound_runtime.c',
        note='large stress-sized constant-expression array bounds should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_impldef_ptr_ulong_roundtrip_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_impldef_ptr_ulong_roundtrip_runtime.c',
        note='implementation-defined pointer<->unsigned long cast roundtrip should compile and run deterministically on host',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_impldef_int_to_ptr_nonzero_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_impldef_int_to_ptr_nonzero_runtime.c',
        note='implementation-defined nonzero integer-to-pointer cast lane should compile and run without dereference',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_fold_ternary_bitwise_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_fold_ternary_bitwise_runtime.c',
        note='compound ternary/bitwise constant-expression folds should compile and match clang runtime output',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_impldef_ptr_slong_roundtrip_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_impldef_ptr_slong_roundtrip_runtime.c',
        note='implementation-defined pointer<->signed long cast roundtrip should compile and run deterministically on host',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_explicit_nonzero_int_cast_ptr_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_explicit_nonzero_int_cast_ptr_runtime.c',
        note='explicit nonzero integer-to-pointer cast lane should compile and run without dereference',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_multidim_fold_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_multidim_fold_runtime.c',
        note='multi-dimensional array bounds and designated array initializers using compound constant-expression chains should match clang',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_array_chain_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_array_chain_depth_runtime.c',
        note='deep chained integer-constant-expression array bounds should compile and match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_case_chain_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_case_chain_depth_runtime.c',
        note='deep chained integer-constant-expression case labels should compile and match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_zero_cast_matrix_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_zero_cast_matrix_runtime.c',
        note='strict policy-safe null-pointer constant and void*-roundtrip conversion matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_static_chain_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_static_chain_depth_runtime.c',
        note='deep chained integer-constant-expression static initializer forms should compile and match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_switch_cast_sizeof_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_switch_cast_sizeof_depth_runtime.c',
        note='mixed cast/sizeof integer-constant-expression switch-selector forms should compile and match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_fnptr_decay_null_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_fnptr_decay_null_runtime.c',
        note='strict function-pointer decay/null-check/call conversion matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_array_decay_ptrdiff_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_array_decay_ptrdiff_runtime.c',
        note='strict array-decay, void*-roundtrip, and in-array pointer-difference matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_static_ternary_bitcast_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_static_ternary_bitcast_depth_runtime.c',
        note='deeper chained static-initializer integer-constant-expression forms using ternary/bitwise/casts should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_const_ptr_roundtrip_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_const_ptr_roundtrip_runtime.c',
        note='strict const-qualified pointer-to-void roundtrip matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_null_conditional_matrix_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_null_conditional_matrix_runtime.c',
        note='strict null-pointer conditional conversion matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_fnptr_table_null_dispatch_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_fnptr_table_null_dispatch_runtime.c',
        note='strict function-pointer table null-dispatch conversion matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_array_static_shared_chain_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_array_static_shared_chain_depth_runtime.c',
        note='deeper chained ICEs shared between array bounds and static initializers should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_switch_nested_ternary_bitwise_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_switch_nested_ternary_bitwise_depth_runtime.c',
        note='nested ternary+bitwise ICE switch-label matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_static_cast_sizeof_ternary_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_static_cast_sizeof_ternary_depth_runtime.c',
        note='deep cast+sizeof+ternary static-initializer ICE matrix should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_const_compare_matrix_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_const_compare_matrix_runtime.c',
        note='strict const-qualified pointer comparison matrix over shared array domain should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_const_chain_assignment_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_const_chain_assignment_runtime.c',
        note='strict const-qualified pointer assignment/void-roundtrip chain should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_policy_strict_ptr_compare_one_past_runtime',
        source=PROBE_DIR / 'runtime/07__probe_policy_strict_ptr_compare_one_past_runtime.c',
        note='strict one-past pointer comparison and ptrdiff matrix should match clang+gcc runtime behavior',
        extra_differential_compiler='gcc',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_shared_ice_matrix_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_shared_ice_matrix_runtime.c',
        note='shared ICE matrix coupling array-size, switch labels, and static initializers should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_shared_ice_matrix_nested_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_shared_ice_matrix_nested_runtime.c',
        note='nested shared ICE matrix coupling array-size, switch labels, and static initializers should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='07__probe_constexpr_shared_ice_cross_surface_depth_runtime',
        source=PROBE_DIR / 'runtime/07__probe_constexpr_shared_ice_cross_surface_depth_runtime.c',
        note='cross-surface ICE depth matrix with coupled array bounds, switch labels, and static initializers should match clang runtime behavior',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='07__probe_assign_struct_to_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_assign_struct_to_int_reject.c',
        note='assignment from struct value to int object should be rejected',
    ),
    DiagnosticProbe(
        probe_id='07__probe_agg_invalid_member_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_invalid_member_reject.c',
        note='member access on a non-existent struct field should be rejected',
    ),
    DiagnosticProbe(
        probe_id='07__probe_constexpr_array_size_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_constexpr_array_size_reject.c',
        note='file-scope array size must be an integer constant expression',
        required_substrings=['constant'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_constexpr_case_label_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_constexpr_case_label_reject.c',
        note='case labels must be integer constant expressions',
        required_substrings=['Case label is not an integer constant expression'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_constexpr_static_init_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_constexpr_static_init_reject.c',
        note='static storage initializers must be constant expressions',
        required_substrings=['not a constant expression'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_conv_pointer_assign_float_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_assign_float_reject.c',
        note='pointer assignment from floating expression should be rejected',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_conv_pointer_init_struct_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_init_struct_reject.c',
        note='pointer initialization from struct expression should be rejected',
        required_substrings=['Incompatible initializer type'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_conv_pointer_init_nonzero_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_init_nonzero_int_reject.c',
        note='pointer initialization from nonzero integer constant should be rejected',
        required_substrings=['Incompatible initializer type'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_conv_assign_pointer_to_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_assign_pointer_to_int_reject.c',
        note='assignment from pointer expression to integer object should be rejected',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_void_pointer_arith_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_void_pointer_arith_reject.c',
        note='void-pointer arithmetic assignment should be rejected with operator and assignment diagnostics',
        required_substrings=['pointer arithmetic on void*', 'Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_agg_union_missing_nested_field_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_union_missing_nested_field_reject.c',
        note='nested aggregate member access should reject missing struct field within union variant',
        required_substrings=['Unknown field in member access'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_agg_union_arrow_nonptr_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_union_arrow_nonptr_reject.c',
        note='arrow operator on non-pointer aggregate member should be rejected',
        required_substrings=['pointer operand'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_cast_struct_to_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_cast_struct_to_int_reject.c',
        note='explicit cast from struct value to integer should be rejected',
        required_substrings=['Invalid cast between non-scalar types'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_cast_int_to_struct_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_cast_int_to_struct_reject.c',
        note='explicit cast from integer to struct value should be rejected',
        required_substrings=['Invalid cast between non-scalar types'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_agg_dot_scalar_base_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_dot_scalar_base_reject.c',
        note='dot access on scalar expression should be rejected at semantic stage',
        required_substrings=["Operator '.' requires struct/union operand"],
    ),
    DiagnosticProbe(
        probe_id='07__probe_agg_arrow_ptr_to_scalar_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_arrow_ptr_to_scalar_reject.c',
        note='arrow access on pointer-to-scalar expression should be rejected at semantic stage',
        required_substrings=["Operator '->' requires struct/union operand"],
    ),
    DiagnosticProbe(
        probe_id='07__probe_agg_dot_array_base_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_dot_array_base_reject.c',
        note='dot access on array expression should be rejected at semantic stage',
        required_substrings=["Operator '.' requires struct/union operand"],
    ),
    DiagnosticProbe(
        probe_id='07__probe_designator_array_index_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_nonconst_reject.c',
        note='array designated initializer index must be an integer constant expression',
        required_substrings=['designator index must be a constant expression'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_designator_array_index_negative_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_negative_reject.c',
        note='array designated initializer index must reject negative constants',
        required_substrings=['designator index -1 is negative'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_designator_array_index_oob_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_oob_reject.c',
        note='array designated initializer index must reject out-of-bounds constants',
        required_substrings=['designator index 3 is out of bounds'],
    ),
    DiagnosticProbe(
        probe_id='07__probe_designator_nested_unknown_field_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_nested_unknown_field_reject.c',
        note='nested designated initializer should reject unknown inner-aggregate field names',
        required_substrings=['Unknown field'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_conv_pointer_assign_float_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_conv_pointer_assign_float_rich_presence.c',
        note='strict frontier: pointer-assignment-from-float diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=2104,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_conv_pointer_assign_float_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_conv_pointer_assign_float_rich_presence.c',
        note='reduced threshold: pointer-assignment-from-float diagnostics JSON under #line remap emits conversion diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_void_pointer_arith_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_void_pointer_arith_rich_presence.c',
        note='strict frontier: void-pointer arithmetic diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=2203,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_void_pointer_arith_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_void_pointer_arith_rich_presence.c',
        note='reduced threshold: void-pointer arithmetic diagnostics JSON under #line remap emits conversion diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_include_conv_pointer_assign_float_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_include_conv_pointer_assign_float_rich_presence.c',
        note='strict frontier: include-header pointer-assignment-from-float diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=2514,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_include_conv_pointer_assign_float_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_include_conv_pointer_assign_float_rich_presence.c',
        note='reduced threshold: include-header pointer-assignment-from-float diagnostics JSON under #line remap emits conversion diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_include_void_pointer_arith_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_include_void_pointer_arith_rich_presence.c',
        note='strict frontier: include-header void-pointer arithmetic diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=2613,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_line_directive_include_void_pointer_arith_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/07__probe_diagjson_line_directive_include_void_pointer_arith_rich_presence.c',
        note='reduced threshold: include-header void-pointer arithmetic diagnostics JSON under #line remap emits conversion diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_assign_struct_to_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_assign_struct_to_int_reject.c',
        note='diagnostics JSON should include assignment incompatibility for struct-to-int assignment',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_invalid_member_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_invalid_member_reject.c',
        note='diagnostics JSON should include invalid aggregate member access rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_constexpr_array_size_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_constexpr_array_size_reject.c',
        note='diagnostics JSON should include non-constant array-size rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_constexpr_case_label_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_constexpr_case_label_reject.c',
        note='diagnostics JSON should include non-constant case-label rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_constexpr_static_init_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_constexpr_static_init_reject.c',
        note='diagnostics JSON should include non-constant static-initializer rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_pointer_assign_float_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_assign_float_reject.c',
        note='diagnostics JSON should include pointer-assignment conversion rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_pointer_init_struct_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_init_struct_reject.c',
        note='diagnostics JSON should include pointer-initializer conversion rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_pointer_init_nonzero_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_init_nonzero_int_reject.c',
        note='diagnostics JSON should include pointer-initializer nonzero-integer rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_assign_pointer_to_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_assign_pointer_to_int_reject.c',
        note='diagnostics JSON should include pointer-to-integer assignment rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_void_pointer_arith_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_void_pointer_arith_reject.c',
        note='diagnostics JSON should include void-pointer arithmetic assignment rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_union_missing_nested_field_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_union_missing_nested_field_reject.c',
        note='diagnostics JSON should include missing nested aggregate member rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_cast_struct_to_int_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_cast_struct_to_int_reject.c',
        note='diagnostics JSON should include explicit struct-to-int cast rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_cast_int_to_struct_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_cast_int_to_struct_reject.c',
        note='diagnostics JSON should include explicit int-to-struct cast rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_dot_scalar_base_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_dot_scalar_base_reject.c',
        note='diagnostics JSON should include dot-on-scalar member-access rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_arrow_ptr_to_scalar_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_arrow_ptr_to_scalar_reject.c',
        note='diagnostics JSON should include arrow-on-pointer-to-scalar member-access rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_designator_array_index_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_nonconst_reject.c',
        note='diagnostics JSON should include non-constant array-designator index rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_designator_array_index_oob_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_oob_reject.c',
        note='diagnostics JSON should include out-of-bounds array-designator index rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_designator_nested_unknown_field_reject',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_nested_unknown_field_reject.c',
        note='diagnostics JSON should include nested unknown-field designated-initializer rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_designator_array_index_nonconst_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_nonconst_reject.c',
        note='diagnostics JSON strict parity for non-constant array-designator index rejection',
        expected_codes=[2000],
        expected_line=2,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_designator_array_index_oob_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_array_index_oob_reject.c',
        note='diagnostics JSON strict parity for out-of-bounds array-designator index rejection',
        expected_codes=[2000],
        expected_line=1,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_designator_nested_unknown_field_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_designator_nested_unknown_field_reject.c',
        note='diagnostics JSON strict parity for nested unknown-field designated-initializer rejection',
        expected_codes=[2000],
        expected_line=10,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_dot_scalar_base_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_dot_scalar_base_reject.c',
        note='diagnostics JSON strict parity for dot-on-scalar member-access rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_arrow_ptr_to_scalar_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_arrow_ptr_to_scalar_reject.c',
        note='diagnostics JSON strict parity for arrow-on-pointer-to-scalar member-access rejection',
        expected_codes=[2000],
        expected_line=4,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_dot_array_base_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_dot_array_base_reject.c',
        note='diagnostics JSON strict parity for dot-on-array member-access rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_pointer_assign_float_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_assign_float_reject.c',
        note='diagnostics JSON strict parity for pointer-assignment-from-float rejection',
        expected_codes=[2000],
        expected_line=4,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_pointer_init_struct_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_init_struct_reject.c',
        note='diagnostics JSON strict parity for pointer-initializer-from-struct rejection',
        expected_codes=[2000],
        expected_line=7,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_pointer_init_nonzero_int_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_pointer_init_nonzero_int_reject.c',
        note='diagnostics JSON strict parity for pointer-initializer-from-nonzero-int rejection',
        expected_codes=[2000],
        expected_line=2,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_conv_assign_pointer_to_int_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_conv_assign_pointer_to_int_reject.c',
        note='diagnostics JSON strict parity for pointer-to-int assignment rejection',
        expected_codes=[2000],
        expected_line=5,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_void_pointer_arith_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_void_pointer_arith_reject.c',
        note='diagnostics JSON strict parity for void-pointer arithmetic assignment rejection',
        expected_codes=[2000],
        expected_line=3,
        expected_column=10,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_cast_struct_to_int_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_cast_struct_to_int_reject.c',
        note='diagnostics JSON strict parity for explicit struct-to-int cast rejection',
        expected_codes=[2000],
        expected_line=8,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_cast_int_to_struct_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_cast_int_to_struct_reject.c',
        note='diagnostics JSON strict parity for explicit int-to-struct cast rejection',
        expected_codes=[2000],
        expected_line=8,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_union_missing_nested_field_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_union_missing_nested_field_reject.c',
        note='diagnostics JSON strict parity for nested aggregate member rejection inside union variant',
        expected_codes=[2000],
        expected_line=14,
    ),
    DiagnosticJsonProbe(
        probe_id='07__probe_diagjson_agg_invalid_member_reject_strict',
        source=PROBE_DIR / 'diagnostics/07__probe_agg_invalid_member_reject.c',
        note='diagnostics JSON strict parity for aggregate unknown-member rejection',
        expected_codes=[2000],
        expected_line=8,
    ),
]
