from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = []

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='06__probe_line_directive_assign_incompatible_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_assign_incompatible_spelling_reject.c',
        note='strict frontier: assignment-incompatible diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_assign_incompat_diag_probe.c:1244:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_assign_incompatible_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_assign_incompatible_current_sparse_pass.c',
        note='fixed baseline: assignment-incompatible diagnostics under #line now include spelling payload',
        required_substrings=['Spelling: virtual_lv_assign_incompat_diag_probe.c:1244:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_assign_qualifier_loss_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_assign_qualifier_loss_spelling_reject.c',
        note='strict frontier: qualifier-loss assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_assign_qual_loss_diag_probe.c:1265:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_assign_qualifier_loss_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_assign_qualifier_loss_current_sparse_pass.c',
        note='fixed baseline: qualifier-loss assignment diagnostics under #line now include spelling payload',
        required_substrings=['Spelling: virtual_lv_assign_qual_loss_diag_probe.c:1265:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_assign_incompatible_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_incompatible_spelling_reject.c',
        note='strict frontier: include-header assignment-incompatible diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_assign_incompat_diag_probe.h:1564:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_incompatible_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_incompatible_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_assign_incompatible_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_incompatible_current_sparse_pass.c',
        note='fixed baseline: include-header assignment-incompatible diagnostics under #line now include spelling payload',
        required_substrings=['Spelling: virtual_lv_include_assign_incompat_diag_probe.h:1564:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_incompatible_current_sparse_pass.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_incompatible_current_sparse_pass.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_assign_qualifier_loss_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_qualifier_loss_spelling_reject.c',
        note='strict frontier: include-header qualifier-loss assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_assign_qual_loss_diag_probe.h:1585:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_qualifier_loss_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_qualifier_loss_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_assign_qualifier_loss_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_qualifier_loss_current_sparse_pass.c',
        note='fixed baseline: include-header qualifier-loss assignment diagnostics under #line now include spelling payload',
        required_substrings=['Spelling: virtual_lv_include_assign_qual_loss_diag_probe.h:1585:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_qualifier_loss_current_sparse_pass.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_assign_qualifier_loss_current_sparse_pass.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_nonmodifiable_lvalue_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_nonmodifiable_lvalue_spelling_reject.c',
        note='strict frontier: nonmodifiable-lvalue assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_nonmodifiable_assign_diag_probe.c:1803:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_nonmodifiable_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_nonmodifiable_lvalue_current_sparse_pass.c',
        note='fixed baseline: nonmodifiable-lvalue assignment diagnostics under #line now include spelling payload',
        required_substrings=['Spelling: virtual_lv_nonmodifiable_assign_diag_probe.c:1803:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_nonmodifiable_lvalue_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_nonmodifiable_lvalue_spelling_reject.c',
        note='strict frontier: include-header nonmodifiable-lvalue assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_nonmodifiable_assign_diag_probe.h:1823:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_nonmodifiable_lvalue_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_nonmodifiable_lvalue_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_nonmodifiable_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_nonmodifiable_lvalue_current_sparse_pass.c',
        note='fixed baseline: include-header nonmodifiable-lvalue assignment diagnostics under #line now include spelling payload',
        required_substrings=['Spelling: virtual_lv_include_nonmodifiable_assign_diag_probe.h:1823:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_nonmodifiable_lvalue_current_sparse_pass.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_nonmodifiable_lvalue_current_sparse_pass.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_bitfield_address_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_bitfield_address_spelling_reject.c',
        note='strict frontier: bitfield address-of diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_bitfield_address_diag_probe.c:2067:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_bitfield_address_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_bitfield_address_spelling_reject.c',
        note='current threshold: bitfield address-of diagnostics under #line include spelling payload',
        required_substrings=['Spelling: virtual_lv_bitfield_address_diag_probe.c:2067:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_bitfield_address_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_bitfield_address_spelling_reject.c',
        note='strict frontier: include-header bitfield address-of diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_bitfield_address_diag_probe.h:2077:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_bitfield_address_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_bitfield_address_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_bitfield_address_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_bitfield_address_spelling_reject.c',
        note='current threshold: include-header bitfield address-of diagnostics under #line include spelling payload',
        required_substrings=['Spelling: virtual_lv_include_bitfield_address_diag_probe.h:2077:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_bitfield_address_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_bitfield_address_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_temp_increment_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_temp_increment_spelling_reject.c',
        note='strict frontier: temporary increment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_temp_increment_diag_probe.c:2082:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_temp_increment_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_temp_increment_spelling_reject.c',
        note='current threshold: temporary increment diagnostics under #line include spelling payload',
        required_substrings=['Spelling: virtual_lv_temp_increment_diag_probe.c:2082:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_temp_increment_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_temp_increment_spelling_reject.c',
        note='strict frontier: include-header temporary increment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_temp_increment_diag_probe.h:2092:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_temp_increment_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_temp_increment_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_temp_increment_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_temp_increment_spelling_reject.c',
        note='current threshold: include-header temporary increment diagnostics under #line include spelling payload',
        required_substrings=['Spelling: virtual_lv_include_temp_increment_diag_probe.h:2092:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_temp_increment_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_temp_increment_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_compound_assign_pointer_plus_pointer_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_compound_assign_pointer_plus_pointer_spelling_reject.c',
        note='strict frontier: pointer-plus-pointer compound-assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_compound_assign_pointer_plus_pointer_diag_probe.c:2246:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_compound_assign_pointer_plus_pointer_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_compound_assign_pointer_plus_pointer_spelling_reject.c',
        note='reduced threshold: pointer-plus-pointer compound-assignment diagnostics should emit pointer-arithmetic rejection',
        required_substrings=["Operator '+' requires pointer arithmetic"],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject.c',
        note='strict frontier: include-header pointer-plus-pointer compound-assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_compound_assign_pointer_plus_pointer_diag_probe.h:2256:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_compound_assign_pointer_plus_pointer_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject.c',
        note='reduced threshold: include-header pointer-plus-pointer compound-assignment diagnostics should emit pointer-arithmetic rejection',
        required_substrings=["Operator '+' requires pointer arithmetic"],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_pointer_plus_pointer_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_compound_assign_const_lvalue_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_compound_assign_const_lvalue_spelling_reject.c',
        note='strict frontier: const-lvalue compound-assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_compound_assign_const_lvalue_diag_probe.c:2264:'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_compound_assign_const_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_compound_assign_const_lvalue_spelling_reject.c',
        note='reduced threshold: const-lvalue compound-assignment diagnostics should emit nonmodifiable-lvalue rejection',
        required_substrings=["Left operand of '+=' must be a modifiable lvalue"],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject.c',
        note='strict frontier: include-header const-lvalue compound-assignment diagnostics should preserve #line virtual spelling filename',
        required_substrings=['Spelling: virtual_lv_include_compound_assign_const_lvalue_diag_probe.h:2274:'],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='06__probe_line_directive_include_compound_assign_const_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject.c',
        note='reduced threshold: include-header const-lvalue compound-assignment diagnostics should emit nonmodifiable-lvalue rejection',
        required_substrings=["Left operand of '+=' must be a modifiable lvalue"],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject.c', PROBE_DIR / 'diagnostics/06__probe_line_directive_include_compound_assign_const_lvalue_spelling_reject.h'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_assign_incompatible_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_assign_incompatible_file_presence_reject.c',
        note='strict frontier: assignment-incompatible diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=1044,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_assign_incompatible_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_assign_incompatible_current_sparse_pass.c',
        note='fixed baseline: assignment-incompatible diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=1044,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_assign_qualifier_loss_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_assign_qualifier_loss_file_presence_reject.c',
        note='strict frontier: qualifier-loss assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=1065,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_assign_qualifier_loss_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_assign_qualifier_loss_current_sparse_pass.c',
        note='fixed baseline: qualifier-loss assignment diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=1065,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_assign_incompatible_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_assign_incompatible_file_presence_reject.c',
        note='strict frontier: include-header assignment-incompatible diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=1464,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_assign_incompatible_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_assign_incompatible_current_sparse_pass.c',
        note='fixed baseline: include-header assignment-incompatible diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=1464,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_assign_qualifier_loss_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_assign_qualifier_loss_file_presence_reject.c',
        note='strict frontier: include-header qualifier-loss assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=1485,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_assign_qualifier_loss_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_assign_qualifier_loss_current_sparse_pass.c',
        note='fixed baseline: include-header qualifier-loss assignment diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=1485,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_nonmodifiable_lvalue_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_nonmodifiable_lvalue_file_presence_reject.c',
        note='strict frontier: nonmodifiable-lvalue assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=1763,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_nonmodifiable_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_nonmodifiable_lvalue_current_sparse_pass.c',
        note='fixed baseline: nonmodifiable-lvalue assignment diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=1763,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_nonmodifiable_lvalue_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_nonmodifiable_lvalue_file_presence_reject.c',
        note='strict frontier: include-header nonmodifiable-lvalue assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=1783,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_nonmodifiable_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_nonmodifiable_lvalue_current_sparse_pass.c',
        note='fixed baseline: include-header nonmodifiable-lvalue assignment diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=1783,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_bitfield_address_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_bitfield_address_file_presence_reject.c',
        note='strict frontier: bitfield address-of diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2107,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_bitfield_address_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_bitfield_address_file_presence_reject.c',
        note='current threshold: bitfield address-of diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=2107,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject.c',
        note='strict frontier: include-header bitfield address-of diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2117,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_bitfield_address_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject.c',
        note='current threshold: include-header bitfield address-of diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=2117,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_bitfield_address_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_temp_increment_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_temp_increment_file_presence_reject.c',
        note='strict frontier: temporary increment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2122,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_temp_increment_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_temp_increment_file_presence_reject.c',
        note='current threshold: temporary increment diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=2122,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject.c',
        note='strict frontier: include-header temporary increment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2132,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_temp_increment_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject.c',
        note='current threshold: include-header temporary increment diagnostics JSON under #line remap includes file presence',
        expected_codes=[2000],
        expected_line=2132,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_temp_increment_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_compound_assign_pointer_plus_pointer_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_compound_assign_pointer_plus_pointer_file_presence_reject.c',
        note='strict frontier: pointer-plus-pointer compound-assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2346,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_compound_assign_pointer_plus_pointer_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_compound_assign_pointer_plus_pointer_file_presence_reject.c',
        note='reduced threshold: pointer-plus-pointer compound-assignment diagnostics JSON under #line remap emits diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject.c',
        note='strict frontier: include-header pointer-plus-pointer compound-assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2356,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject.c',
        note='reduced threshold: include-header pointer-plus-pointer compound-assignment diagnostics JSON under #line remap emits diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_pointer_plus_pointer_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_compound_assign_const_lvalue_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_compound_assign_const_lvalue_file_presence_reject.c',
        note='strict frontier: const-lvalue compound-assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2364,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_compound_assign_const_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_compound_assign_const_lvalue_file_presence_reject.c',
        note='reduced threshold: const-lvalue compound-assignment diagnostics JSON under #line remap emits diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject.c',
        note='strict frontier: include-header const-lvalue compound-assignment diagnostics JSON should include has_file under #line remap',
        expected_codes=[2000],
        expected_line=2374,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject.c',
        note='reduced threshold: include-header const-lvalue compound-assignment diagnostics JSON under #line remap emits diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject.c', PROBE_DIR / 'diagnostics/06__probe_diagjson_line_directive_include_compound_assign_const_lvalue_file_presence_reject.h'],
    ),
]
