from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = []

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='12__probe_invalid_shift_width',
        source=PROBE_DIR / 'diagnostics/12__probe_invalid_shift_width.c',
        note='should emit diagnostic for negative shift width',
        required_substrings=['Invalid shift width'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_incompatible_ptr_assign',
        source=PROBE_DIR / 'diagnostics/12__probe_incompatible_ptr_assign.c',
        note='should emit assignment/pointer incompatibility diagnostic',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_illegal_struct_to_int_cast',
        source=PROBE_DIR / 'diagnostics/12__probe_illegal_struct_to_int_cast.c',
        note='should emit invalid cast diagnostic',
        required_substrings=['Invalid cast between non-scalar types'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_while_missing_lparen_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_while_missing_lparen_reject.c',
        note="while statement missing '(' should emit a diagnostic (fail-closed parser recovery)",
    ),
    DiagnosticProbe(
        probe_id='12__probe_do_while_missing_semicolon_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_do_while_missing_semicolon_reject.c',
        note="do-while statement missing trailing ';' should emit a diagnostic",
    ),
    DiagnosticProbe(
        probe_id='12__probe_for_header_missing_semicolon_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_for_header_missing_semicolon_reject.c',
        note="for header missing first ';' should emit a diagnostic",
        required_substrings=['Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_for_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diag_line_directive_for_missing_semicolon_parser_text_strict.c',
        note='text diagnostics should preserve parser malformed-for-header line under #line remap',
        required_substrings=["Error: expected ';' after for-loop initializer at line 8402"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_for_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diag_line_directive_include_for_missing_semicolon_parser_text_strict.c',
        note='text diagnostics should preserve parser malformed-for-header line for include #line remap',
        required_substrings=["Error: expected ';' after for-loop initializer at line 8502"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_for_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' in for header under #line remap",
        required_substrings=["Error: expected ')' after for-loop increment at line 8922"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_for_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' in for header under include #line remap",
        required_substrings=["Error: expected ')' after for-loop increment at line 8932"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_if_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' line under #line remap for if",
        required_substrings=["Error: expected ')' after condition at line 8603"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_if_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' line under include #line remap for if",
        required_substrings=["Error: expected ')' after condition at line 8613"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_while_missing_lparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_lparen_parser_presence.c',
        note="text diagnostics should preserve parser missing '(' line under #line remap for while",
        required_substrings=["Error: expected '(' after 'while' at line 8703"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_while_missing_lparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence.c',
        note="text diagnostics should preserve parser missing '(' line under include #line remap for while",
        required_substrings=["Error: expected '(' after 'while' at line 8713"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_do_while_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence.c',
        note="text diagnostics should preserve parser missing ';' line under #line remap for do-while",
        required_substrings=["Error: expected ';' after 'do-while' statement at line 8806"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_do_while_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence.c',
        note="text diagnostics should preserve parser missing ';' line under include #line remap for do-while",
        required_substrings=["Error: expected ';' after 'do-while' statement at line 8816"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_switch_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note='text diagnostics should preserve parser switch-header parse failure line under #line remap',
        required_substrings=['Error: Failed to parse expression at line 8903'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_switch_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note='text diagnostics should preserve parser switch-header parse failure line under include #line remap',
        required_substrings=['Error: Failed to parse expression at line 8913'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_if_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for if',
        required_substrings=['line 9103'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_if_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for if',
        required_substrings=['line 9113'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for while',
        required_substrings=['line 9203'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for while',
        required_substrings=['line 9213'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for for',
        required_substrings=['line 9303'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for for',
        required_substrings=['line 9313'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_while_missing_lparen',
        source=PROBE_DIR / 'diagnostics/12__probe_while_missing_lparen_reject.c',
        note="diagnostics JSON export should include parser diagnostics for missing '(' after while",
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_do_while_missing_semicolon',
        source=PROBE_DIR / 'diagnostics/12__probe_do_while_missing_semicolon_reject.c',
        note="diagnostics JSON export should include parser diagnostics for missing ';' after do-while",
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_for_header_missing_semicolon',
        source=PROBE_DIR / 'diagnostics/12__probe_for_header_missing_semicolon_reject.c',
        note='diagnostics JSON export should include diagnostics for malformed for header',
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_semicolon_parser_presence.c',
        note='strict frontier: #line malformed for-header should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=8402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_semicolon_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_semicolon_parser_presence.c',
        note='post-fix lane: #line malformed for-header diagnostics JSON includes parser+semantic payload',
        expected_codes=[2000],
        expected_line=8402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_semicolon_parser_presence.c',
        note='strict frontier: include #line malformed for-header should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=8502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_semicolon_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_semicolon_parser_presence.c',
        note='post-fix lane: include #line malformed for-header diagnostics JSON includes parser+semantic payload',
        expected_codes=[2000],
        expected_line=8502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_rparen_parser_presence.c',
        note="strict frontier: #line for-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8922,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_rparen_parser_presence.c',
        note="reduced threshold: #line for-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8922,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence.c',
        note="strict frontier: include #line for-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8932,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence.c',
        note="reduced threshold: include #line for-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8932,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_rparen_parser_presence.c',
        note="strict frontier: #line if-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8603,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_rparen_parser_presence.c',
        note="reduced threshold: #line if-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8603,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence.c',
        note="strict frontier: include #line if-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8613,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence.c',
        note="reduced threshold: include #line if-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8613,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_lparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_lparen_parser_presence.c',
        note="strict frontier: #line while-missing-'(' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8703,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_lparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_lparen_parser_presence.c',
        note="reduced threshold: #line while-missing-'(' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8703,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence.c',
        note="strict frontier: include #line while-missing-'(' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8713,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_lparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence.c',
        note="reduced threshold: include #line while-missing-'(' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8713,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence.c',
        note="strict frontier: #line do-while-missing-';' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8806,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_do_while_missing_semicolon_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence.c',
        note="reduced threshold: #line do-while-missing-';' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8806,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence.c',
        note="strict frontier: include #line do-while-missing-';' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8816,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_do_while_missing_semicolon_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence.c',
        note="reduced threshold: include #line do-while-missing-';' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8816,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note="strict frontier: #line switch-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8903,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_switch_missing_rparen_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note="post-fix lane: #line switch-missing-')' diagnostics JSON includes parser+semantic payload",
        expected_codes=[2000],
        expected_line=8901,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note="strict frontier: include #line switch-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8913,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_switch_missing_rparen_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note="post-fix lane: include #line switch-missing-')' diagnostics JSON includes parser+semantic payload",
        expected_codes=[2000],
        expected_line=8911,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='strict frontier: #line if-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='reduced threshold: #line if-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='strict frontier: include #line if-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9113,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='reduced threshold: include #line if-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9113,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='strict frontier: #line while-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9203,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='reduced threshold: #line while-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9203,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='strict frontier: include #line while-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9213,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='reduced threshold: include #line while-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9213,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='strict frontier: #line for-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='reduced threshold: #line for-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='strict frontier: include #line for-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9313,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='reduced threshold: include #line for-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9313,
        expected_has_file=True,
    ),
]
