from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = []

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='12__probe_mixed_if_missing_rparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__if_missing_rparen_then_undeclared.c',
        note='mixed recovery should preserve downstream undeclared-identifier diagnostics after malformed if-condition recovery',
        required_substrings=['expected \')\' after condition', 'Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_mixed_bad_call_then_incompatible_ptr_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__bad_call_then_incompatible_ptr.c',
        note='mixed recovery should preserve downstream incompatible-pointer assignment diagnostics after malformed call recovery',
        required_substrings=["Expected ')' to close function call", 'Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_mixed_switch_case_missing_colon_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__switch_case_missing_colon_then_undeclared.c',
        note='mixed recovery should preserve downstream undeclared and control-flow diagnostics after malformed switch-case recovery',
        required_substrings=["':' after case value", 'Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_mixed_ternary_missing_colon_then_type_mismatch_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__ternary_missing_colon_then_type_mismatch.c',
        note='mixed recovery should preserve downstream type-mismatch diagnostics after malformed ternary recovery',
        required_substrings=["Expected ':' in ternary expression", 'Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_mixed_while_missing_lparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__while_missing_lparen_then_undeclared.c',
        note='mixed while recovery should preserve downstream undeclared-identifier diagnostics after malformed while-header recovery',
        required_substrings=["expected '(' after 'while'", 'Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_mixed_nested_while_missing_lparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__nested_while_missing_lparen_then_undeclared.c',
        note='nested mixed while recovery should preserve downstream undeclared-identifier diagnostics after malformed grouped condition recovery',
        required_substrings=["expected ')' after while condition", 'Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_mixed_do_while_missing_semicolon_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__do_while_missing_semicolon_then_undeclared.c',
        note="mixed do-while recovery should preserve downstream undeclared-identifier diagnostics after missing trailing ';'",
        required_substrings=["expected ';' after 'do-while' statement", 'Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_if_missing_rparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_if_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed if recovery should preserve downstream undeclared-identifier diagnostics after malformed condition recovery',
        required_substrings=["expected ')' after condition at line 9102", 'Error at (9106:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_if_missing_rparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_if_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed if recovery should preserve downstream undeclared-identifier diagnostics after malformed condition recovery',
        required_substrings=["expected ')' after condition at line 9112", 'Error at (9116:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_bad_call_then_incompatible_ptr_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_bad_call_then_incompatible_ptr_diag_text_semantic_followup.c',
        note='line-remapped mixed call recovery should preserve downstream incompatible-pointer diagnostics after malformed call recovery',
        required_substrings=["Expected ')' to close function call", 'Error at (9209:5): Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_bad_call_then_incompatible_ptr_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_bad_call_then_incompatible_ptr_diag_text_semantic_followup.c',
        note='include #line mixed call recovery should preserve downstream incompatible-pointer diagnostics after malformed call recovery',
        required_substrings=["Expected ')' to close function call", 'Error at (9219:5): Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_switch_case_missing_colon_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_switch_case_missing_colon_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed switch recovery should preserve downstream semantic cascade after malformed case recovery',
        required_substrings=["':' after case value", 'Error at (9305:17): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_switch_case_missing_colon_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_switch_case_missing_colon_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed switch recovery should preserve downstream semantic cascade after malformed case recovery',
        required_substrings=["':' after case value", 'Error at (9315:17): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_ternary_missing_colon_then_type_mismatch_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_ternary_missing_colon_then_type_mismatch_diag_text_semantic_followup.c',
        note='line-remapped mixed ternary recovery should preserve downstream semantic diagnostics after malformed ternary recovery',
        required_substrings=["Expected ':' in ternary expression", 'Error at (9405:5): Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_ternary_missing_colon_then_type_mismatch_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_ternary_missing_colon_then_type_mismatch_diag_text_semantic_followup.c',
        note='include #line mixed ternary recovery should preserve downstream semantic diagnostics after malformed ternary recovery',
        required_substrings=["Expected ':' in ternary expression", 'Error at (9415:5): Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_while_missing_lparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed while recovery should preserve downstream undeclared-identifier diagnostics after malformed while-header recovery',
        required_substrings=["expected '(' after 'while' at line 9603", 'Error at (9607:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_while_missing_lparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed while recovery should preserve downstream undeclared-identifier diagnostics after malformed while-header recovery',
        required_substrings=["expected '(' after 'while' at line 9613", 'Error at (9617:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_nested_while_missing_lparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_nested_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped nested mixed while recovery should preserve downstream undeclared-identifier diagnostics after malformed grouped condition recovery',
        required_substrings=["expected ')' after while condition at line 9903", 'Error at (9907:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_nested_while_missing_lparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_nested_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line nested mixed while recovery should preserve downstream undeclared-identifier diagnostics after malformed grouped condition recovery',
        required_substrings=["expected ')' after while condition at line 9913", 'Error at (9917:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_do_while_missing_semicolon_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_do_while_missing_semicolon_then_undeclared_diag_text_semantic_followup.c',
        note="line-remapped mixed do-while recovery should preserve downstream undeclared-identifier diagnostics after missing trailing ';'",
        required_substrings=["expected ';' after 'do-while' statement at line 9706", 'Error at (9707:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_do_while_missing_semicolon_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_do_while_missing_semicolon_then_undeclared_diag_text_semantic_followup.c',
        note="include #line mixed do-while recovery should preserve downstream undeclared-identifier diagnostics after missing trailing ';'",
        required_substrings=["expected ';' after 'do-while' statement at line 9716", 'Error at (9717:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_mixed_for_missing_rparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_for_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note="line-remapped mixed for recovery should preserve downstream undeclared-identifier diagnostics after missing ')' in header",
        required_substrings=["expected ')' after for-loop increment at line 9802", 'Error at (9806:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_line_directive_include_mixed_for_missing_rparen_then_undeclared_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_for_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note="include #line mixed for recovery should preserve downstream undeclared-identifier diagnostics after missing ')' in header",
        required_substrings=["expected ')' after for-loop increment at line 9812", 'Error at (9816:12): Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_invalid_shift_width',
        source=PROBE_DIR / 'diagnostics/12__probe_invalid_shift_width.c',
        note='should emit diagnostic for negative shift width',
        required_substrings=['Invalid shift width'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_incompatible_ptr_assign',
        source=PROBE_DIR / 'diagnostics/12__probe_incompatible_ptr_assign.c',
        note='should emit assignment/pointer incompatibility diagnostic',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_illegal_struct_to_int_cast',
        source=PROBE_DIR / 'diagnostics/12__probe_illegal_struct_to_int_cast.c',
        note='should emit invalid cast diagnostic',
        required_substrings=['Invalid cast between non-scalar types'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_while_missing_lparen_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_while_missing_lparen_reject.c',
        note="while statement missing '(' should emit a diagnostic (fail-closed parser recovery)",
    ),
    DiagnosticProbe(
        probe_id='12__probe_do_while_missing_semicolon_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_do_while_missing_semicolon_reject.c',
        note="do-while statement missing trailing ';' should emit a diagnostic",
    ),
    DiagnosticProbe(
        probe_id='12__probe_for_header_missing_semicolon_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_for_header_missing_semicolon_reject.c',
        note="for header missing first ';' should emit a diagnostic",
        required_substrings=['Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_for_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diag_line_directive_for_missing_semicolon_parser_text_strict.c',
        note='text diagnostics should preserve parser malformed-for-header line under #line remap',
        required_substrings=["Error: expected ';' after for-loop initializer at line 8402"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_for_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diag_line_directive_include_for_missing_semicolon_parser_text_strict.c',
        note='text diagnostics should preserve parser malformed-for-header line for include #line remap',
        required_substrings=["Error: expected ';' after for-loop initializer at line 8502"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_for_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' in for header under #line remap",
        required_substrings=["Error: expected ')' after for-loop increment at line 8922"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_for_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' in for header under include #line remap",
        required_substrings=["Error: expected ')' after for-loop increment at line 8932"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_if_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' line under #line remap for if",
        required_substrings=["Error: expected ')' after condition at line 8603"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_if_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence.c',
        note="text diagnostics should preserve parser missing ')' line under include #line remap for if",
        required_substrings=["Error: expected ')' after condition at line 8613"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_while_missing_lparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_lparen_parser_presence.c',
        note="text diagnostics should preserve parser missing '(' line under #line remap for while",
        required_substrings=["Error: expected '(' after 'while' at line 8703"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_while_missing_lparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence.c',
        note="text diagnostics should preserve parser missing '(' line under include #line remap for while",
        required_substrings=["Error: expected '(' after 'while' at line 8713"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_do_while_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence.c',
        note="text diagnostics should preserve parser missing ';' line under #line remap for do-while",
        required_substrings=["Error: expected ';' after 'do-while' statement at line 8806"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_do_while_missing_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence.c',
        note="text diagnostics should preserve parser missing ';' line under include #line remap for do-while",
        required_substrings=["Error: expected ';' after 'do-while' statement at line 8816"],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_switch_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note='text diagnostics should preserve parser switch-header parse failure line under #line remap',
        required_substrings=['Error: Failed to parse expression at line 8903'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_switch_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note='text diagnostics should preserve parser switch-header parse failure line under include #line remap',
        required_substrings=['Error: Failed to parse expression at line 8913'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_switch_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for switch',
        required_substrings=['line 9403'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_switch_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for switch',
        required_substrings=['line 9413'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_do_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for do-while',
        required_substrings=['line 9503'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_do_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for do-while',
        required_substrings=['line 9513'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_if_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for if',
        required_substrings=['line 9103'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_if_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for if',
        required_substrings=['line 9113'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for while',
        required_substrings=['line 9203'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for while',
        required_substrings=['line 9213'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for for',
        required_substrings=['line 9303'],
    ),
    DiagnosticProbe(
        probe_id='12__probe_diag_line_directive_include_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for for',
        required_substrings=['line 9313'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_if_missing_rparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__if_missing_rparen_then_undeclared.c',
        note='mixed if-condition recovery should still export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=6,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_bad_call_then_incompatible_ptr_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__bad_call_then_incompatible_ptr.c',
        note='mixed bad-call recovery should still export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_switch_case_missing_colon_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__switch_case_missing_colon_then_undeclared.c',
        note='mixed switch-case recovery should still export downstream semantic cascade in diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_ternary_missing_colon_then_type_mismatch_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__ternary_missing_colon_then_type_mismatch.c',
        note='mixed ternary recovery should still export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_while_missing_lparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__while_missing_lparen_then_undeclared.c',
        note='mixed while recovery should still export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=7,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_nested_while_missing_lparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__nested_while_missing_lparen_then_undeclared.c',
        note='nested mixed while recovery should still export downstream semantic diagnostics JSON after malformed grouped condition recovery',
        expected_codes=[2000],
        expected_line=7,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_mixed_do_while_missing_semicolon_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__parserdiag__mixed__do_while_missing_semicolon_then_undeclared.c',
        note='mixed do-while recovery should still export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=6,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_if_missing_rparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_if_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed if recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9106,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_if_missing_rparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_if_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed if recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9116,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_bad_call_then_incompatible_ptr_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_bad_call_then_incompatible_ptr_diag_text_semantic_followup.c',
        note='line-remapped mixed bad-call recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9209,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_bad_call_then_incompatible_ptr_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_bad_call_then_incompatible_ptr_diag_text_semantic_followup.c',
        note='include #line mixed bad-call recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9219,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_switch_case_missing_colon_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_switch_case_missing_colon_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed switch recovery should export downstream semantic cascade in diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9305,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_switch_case_missing_colon_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_switch_case_missing_colon_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed switch recovery should export downstream semantic cascade in diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9315,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_ternary_missing_colon_then_type_mismatch_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_ternary_missing_colon_then_type_mismatch_diag_text_semantic_followup.c',
        note='line-remapped mixed ternary recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9405,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_ternary_missing_colon_then_type_mismatch_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_ternary_missing_colon_then_type_mismatch_diag_text_semantic_followup.c',
        note='include #line mixed ternary recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9415,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_while_missing_lparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed while recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9607,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_while_missing_lparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed while recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9617,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_nested_while_missing_lparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_nested_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped nested mixed while recovery should export downstream semantic diagnostics JSON after malformed grouped condition recovery',
        expected_codes=[2000],
        expected_line=9907,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_nested_while_missing_lparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_nested_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line nested mixed while recovery should export downstream semantic diagnostics JSON after malformed grouped condition recovery',
        expected_codes=[2000],
        expected_line=9917,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_do_while_missing_semicolon_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_do_while_missing_semicolon_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed do-while recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9707,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_do_while_missing_semicolon_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_do_while_missing_semicolon_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed do-while recovery should export downstream semantic diagnostics JSON after parser failure',
        expected_codes=[2000],
        expected_line=9717,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_for_missing_rparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_for_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note="line-remapped mixed for recovery should export downstream semantic diagnostics JSON after missing ')' in header",
        expected_codes=[2000],
        expected_line=9806,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_for_missing_rparen_then_undeclared_semantic_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_for_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note="include #line mixed for recovery should export downstream semantic diagnostics JSON after missing ')' in header",
        expected_codes=[2000],
        expected_line=9816,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_if_missing_rparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_if_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed if recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9102,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_if_missing_rparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_if_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed if recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9112,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_bad_call_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_bad_call_then_incompatible_ptr_diag_text_semantic_followup.c',
        note='line-remapped mixed bad-call recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9206,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_bad_call_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_bad_call_then_incompatible_ptr_diag_text_semantic_followup.c',
        note='include #line mixed bad-call recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9216,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_switch_case_missing_colon_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_switch_case_missing_colon_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed switch recovery should preserve parser diagnostics JSON presence under remapped lines',
        expected_codes=[1000],
        expected_line=9305,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_switch_case_missing_colon_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_switch_case_missing_colon_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed switch recovery should preserve parser diagnostics JSON presence under remapped lines',
        expected_codes=[1000],
        expected_line=9315,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_ternary_missing_colon_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_ternary_missing_colon_then_type_mismatch_diag_text_semantic_followup.c',
        note='line-remapped mixed ternary recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000, 1001],
        expected_line=9402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_ternary_missing_colon_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_ternary_missing_colon_then_type_mismatch_diag_text_semantic_followup.c',
        note='include #line mixed ternary recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000, 1001],
        expected_line=9412,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_while_missing_lparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed while recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9603,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_while_missing_lparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed while recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9613,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_nested_while_missing_lparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_nested_while_missing_lparen_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped nested mixed while recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9903,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_do_while_missing_semicolon_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_do_while_missing_semicolon_then_undeclared_diag_text_semantic_followup.c',
        note='line-remapped mixed do-while recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9706,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_do_while_missing_semicolon_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_do_while_missing_semicolon_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed do-while recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9716,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_mixed_for_missing_rparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_mixed_for_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note="line-remapped mixed for recovery should preserve parser diagnostics JSON presence under remapped line",
        expected_codes=[1000],
        expected_line=9802,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_mixed_for_missing_rparen_parser_presence_followup',
        source=PROBE_DIR.parent / 'cases/12__line_directive_include_mixed_for_missing_rparen_then_undeclared_diag_text_semantic_followup.c',
        note='include #line mixed for recovery should preserve parser diagnostics JSON presence under remapped line',
        expected_codes=[1000],
        expected_line=9812,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_while_missing_lparen',
        source=PROBE_DIR / 'diagnostics/12__probe_while_missing_lparen_reject.c',
        note="diagnostics JSON export should include parser diagnostics for missing '(' after while",
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_do_while_missing_semicolon',
        source=PROBE_DIR / 'diagnostics/12__probe_do_while_missing_semicolon_reject.c',
        note="diagnostics JSON export should include parser diagnostics for missing ';' after do-while",
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_for_header_missing_semicolon',
        source=PROBE_DIR / 'diagnostics/12__probe_for_header_missing_semicolon_reject.c',
        note='diagnostics JSON export should include diagnostics for malformed for header',
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_semicolon_parser_presence.c',
        note='strict frontier: #line malformed for-header should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=8402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_semicolon_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_semicolon_parser_presence.c',
        note='post-fix lane: #line malformed for-header diagnostics JSON includes parser+semantic payload',
        expected_codes=[2000],
        expected_line=8402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_semicolon_parser_presence.c',
        note='strict frontier: include #line malformed for-header should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=8502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_semicolon_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_semicolon_parser_presence.c',
        note='post-fix lane: include #line malformed for-header diagnostics JSON includes parser+semantic payload',
        expected_codes=[2000],
        expected_line=8502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_rparen_parser_presence.c',
        note="strict frontier: #line for-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8922,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_rparen_parser_presence.c',
        note="reduced threshold: #line for-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8922,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence.c',
        note="strict frontier: include #line for-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8932,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_rparen_parser_presence.c',
        note="reduced threshold: include #line for-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8932,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_rparen_parser_presence.c',
        note="strict frontier: #line if-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8603,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_rparen_parser_presence.c',
        note="reduced threshold: #line if-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8603,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence.c',
        note="strict frontier: include #line if-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8613,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_rparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_rparen_parser_presence.c',
        note="reduced threshold: include #line if-missing-')' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8613,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_lparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_lparen_parser_presence.c',
        note="strict frontier: #line while-missing-'(' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8703,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_lparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_lparen_parser_presence.c',
        note="reduced threshold: #line while-missing-'(' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8703,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence.c',
        note="strict frontier: include #line while-missing-'(' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8713,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_lparen_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_lparen_parser_presence.c',
        note="reduced threshold: include #line while-missing-'(' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8713,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence.c',
        note="strict frontier: #line do-while-missing-';' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8806,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_do_while_missing_semicolon_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_semicolon_parser_presence.c',
        note="reduced threshold: #line do-while-missing-';' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8806,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence.c',
        note="strict frontier: include #line do-while-missing-';' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8816,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_do_while_missing_semicolon_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_semicolon_parser_presence.c',
        note="reduced threshold: include #line do-while-missing-';' diagnostics JSON preserves parser payload only",
        expected_codes=[1000],
        expected_line=8816,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note="strict frontier: #line switch-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8903,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_switch_missing_rparen_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note="post-fix lane: #line switch-missing-')' diagnostics JSON includes parser+semantic payload",
        expected_codes=[2000],
        expected_line=8901,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note="strict frontier: include #line switch-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=8913,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_switch_missing_rparen_current_semantic_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note="post-fix lane: include #line switch-missing-')' diagnostics JSON includes parser+semantic payload",
        expected_codes=[2000],
        expected_line=8911,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_switch_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_body_parser_presence.c',
        note='strict frontier: #line switch-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9403,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_switch_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_switch_missing_body_parser_presence.c',
        note='reduced threshold: #line switch-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9403,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_switch_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_body_parser_presence.c',
        note='strict frontier: include #line switch-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9413,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_switch_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_switch_missing_body_parser_presence.c',
        note='reduced threshold: include #line switch-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9413,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_do_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_body_parser_presence.c',
        note="strict frontier: #line do-while-missing-body should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=9503,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_do_while_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_do_while_missing_body_parser_presence.c',
        note='reduced threshold: #line do-while-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9503,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_do_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_body_parser_presence.c',
        note="strict frontier: include #line do-while-missing-body should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=9513,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_do_while_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_do_while_missing_body_parser_presence.c',
        note='reduced threshold: include #line do-while-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9513,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='strict frontier: #line if-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_if_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='reduced threshold: #line if-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='strict frontier: include #line if-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9113,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_if_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='reduced threshold: include #line if-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9113,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='strict frontier: #line while-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9203,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_while_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='reduced threshold: #line while-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9203,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='strict frontier: include #line while-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9213,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_while_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='reduced threshold: include #line while-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9213,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='strict frontier: #line for-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_for_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='reduced threshold: #line for-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='strict frontier: include #line for-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=9313,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='12__probe_diagjson_line_directive_include_for_missing_body_current_parser_only_pass',
        source=PROBE_DIR / 'diagnostics/12__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='reduced threshold: include #line for-missing-body diagnostics JSON preserves parser payload only',
        expected_codes=[1000],
        expected_line=9313,
        expected_has_file=True,
    ),
]
