from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='10__probe_static_function_then_extern_decl_ok',
        source=PROBE_DIR / 'runtime/10__probe_static_function_then_extern_decl_ok.c',
        note='file-scope static function followed by extern declaration should remain valid',
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_tentative_shared_state_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_tentative_shared_state_runtime_main.c',
        note='multi-TU tentative definition should share one backing object at runtime',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_shared_state_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_shared_state_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_extern_array_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_extern_array_bridge_runtime_main.c',
        note='header-declared extern array should link cleanly across TUs at runtime',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_extern_array_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_extern_array_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_static_global_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_static_global_partition_runtime_main.c',
        note='file-local static object should stay partitioned from same-spelling external object across TUs',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_static_global_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_global_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_static_global_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_static_global_partition_runtime_main.c',
        note='header-routed wrappers should preserve static-vs-external object partition across TUs',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_global_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_global_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_static_function_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_static_function_partition_runtime_main.c',
        note='file-local static function should stay partitioned from same-spelling external function across TUs',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_static_function_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_function_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_static_function_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_static_function_partition_runtime_main.c',
        note='header-routed wrappers should preserve static-vs-external function partition across TUs',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_function_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_function_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_tentative_header_strong_def_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_tentative_header_strong_def_bridge_runtime_main.c',
        note='header tentative declarations should resolve cleanly against strong definitions across TUs',
        clang_args=['-fcommon'],
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_header_strong_def_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_header_strong_def_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_linkorder_seed_fold_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_main.c',
        note='multi-TU linkage clean path should stay deterministic under canonical TU order',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_linkorder_seed_fold_bridge_runtime_permuted',
        source=PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_main.c',
        note='multi-TU linkage clean path should preserve runtime output when sibling TU order is permuted',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_libb.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_seed_fold_bridge_runtime_liba.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_tentative_array_coalescing_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_coalescing_runtime_main.c',
        note='compatible tentative array definitions across sibling translation units should coalesce into one shared object at runtime',
        clang_args=['-fcommon'],
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_coalescing_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_coalescing_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_coalescing_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_tentative_header_array_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_header_array_runtime_main.c',
        note='header-borne tentative definitions should still coalesce cleanly across translation units at runtime',
        clang_args=['-fcommon'],
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_header_array_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_header_array_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_internal_global_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_internal_global_twin_partition_runtime_main.c',
        note='same-spelling internal-linkage objects in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_internal_global_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_global_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_global_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_tentative_struct_coalescing_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_tentative_struct_coalescing_runtime_main.c',
        note='compatible tentative struct objects across sibling translation units should coalesce into one shared runtime object',
        clang_args=['-fcommon'],
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_struct_coalescing_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_struct_coalescing_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_struct_coalescing_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_extern_struct_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_extern_struct_bridge_runtime_main.c',
        note='header-declared extern struct objects should link and mutate cleanly across translation units at runtime',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_extern_struct_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_extern_struct_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_static_array_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_static_array_partition_runtime_main.c',
        note='same-spelling file-local static arrays in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_static_array_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_array_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_array_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_tentative_struct_coalescing_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_struct_coalescing_runtime_main.c',
        note='header-borne tentative struct objects should coalesce cleanly across translation units at runtime',
        clang_args=['-fcommon'],
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_struct_coalescing_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_struct_coalescing_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_struct_strong_def_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_struct_strong_def_bridge_runtime_main.c',
        note='strongly defined struct objects should bridge cleanly into sibling translation units through extern declarations',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_struct_strong_def_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_struct_strong_def_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_static_struct_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_static_struct_partition_runtime_main.c',
        note='same-spelling file-local static structs in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_static_struct_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_struct_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_struct_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_struct_strong_def_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_struct_strong_def_bridge_runtime_main.c',
        note='header-routed extern struct declarations should resolve cleanly against strong definitions across translation units at runtime',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_struct_strong_def_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_struct_strong_def_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_static_struct_array_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_static_struct_array_partition_runtime_main.c',
        note='same-spelling file-local static struct arrays in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_static_struct_array_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_struct_array_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_static_struct_array_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_linkorder_struct_trace_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_main.c',
        note='struct-based multi-TU linkage clean path should stay deterministic under canonical sibling TU order',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_linkorder_struct_trace_bridge_runtime_permuted',
        source=PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_main.c',
        note='struct-based multi-TU linkage clean path should preserve runtime output when sibling TU order is permuted',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_libb.c',
            PROBE_DIR / 'runtime/10__probe_multitu_linkorder_struct_trace_bridge_runtime_liba.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_static_struct_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_static_struct_partition_runtime_main.c',
        note='header-routed wrappers should preserve static-vs-external struct partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_struct_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_struct_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_static_struct_array_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_static_struct_array_partition_runtime_main.c',
        note='header-routed wrappers should preserve static-vs-external struct-array partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_struct_array_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_struct_array_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_static_array_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_static_array_partition_runtime_main.c',
        note='header-routed wrappers should preserve static-vs-external array partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_array_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_static_array_partition_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_internal_struct_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_twin_partition_runtime_main.c',
        note='same-spelling internal-linkage structs in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_internal_struct_array_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_array_twin_partition_runtime_main.c',
        note='same-spelling internal-linkage struct arrays in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_array_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_array_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_struct_array_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_internal_array_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_internal_array_twin_partition_runtime_main.c',
        note='same-spelling internal-linkage arrays in sibling translation units should keep isolated state behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_internal_array_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_array_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_array_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_internal_function_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_internal_function_twin_partition_runtime_main.c',
        note='same-spelling internal-linkage functions in sibling translation units should stay distinct behind exported wrappers',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_internal_function_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_function_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_internal_function_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_internal_function_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_internal_function_twin_partition_runtime_main.c',
        note='header-routed wrappers should preserve sibling internal-function partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_function_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_function_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_function_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_internal_array_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_internal_array_twin_partition_runtime_main.c',
        note='header-routed wrappers should preserve sibling internal-array partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_array_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_array_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_array_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_internal_struct_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_twin_partition_runtime_main.c',
        note='header-routed wrappers should preserve sibling internal-struct partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_internal_struct_array_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_array_twin_partition_runtime_main.c',
        note='header-routed wrappers should preserve sibling internal-struct-array partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_array_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_array_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_struct_array_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_internal_global_twin_partition_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_internal_global_twin_partition_runtime_main.c',
        note='header-routed wrappers should preserve sibling internal-global partition across translation units',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_global_twin_partition_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_global_twin_partition_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_internal_global_twin_partition_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_scalar_strong_def_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_scalar_strong_def_bridge_runtime_main.c',
        note='strongly defined scalar objects should bridge cleanly into sibling translation units through extern declarations',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_scalar_strong_def_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_scalar_strong_def_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_extern_scalar_bridge_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_extern_scalar_bridge_runtime_main.c',
        note='header-declared extern scalar objects should link and mutate cleanly across translation units at runtime',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_extern_scalar_bridge_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_extern_scalar_bridge_runtime_lib.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_tentative_array_current_strong_def_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_current_strong_def_runtime_main.c',
        note='tentative array declarations should resolve cleanly against one strong definition across sibling translation units at runtime',
        clang_args=['-fcommon'],
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_current_strong_def_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_current_strong_def_runtime_liba.c',
            PROBE_DIR / 'runtime/10__probe_multitu_tentative_array_current_strong_def_runtime_libb.c',
        ],
    ),
    RuntimeProbe(
        probe_id='10__probe_multitu_include_tentative_header_array_current_strong_def_runtime',
        source=PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_header_array_current_strong_def_runtime_main.c',
        note='header-routed extern array declarations should resolve cleanly against one strong definition across translation units at runtime',
        inputs=[
            PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_header_array_current_strong_def_runtime_main.c',
            PROBE_DIR / 'runtime/10__probe_multitu_include_tentative_header_array_current_strong_def_runtime_lib.c',
        ],
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='10__probe_block_extern_different_type_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_block_extern_different_type_reject.c',
        note='block-scope extern should reject redeclaration with conflicting type',
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_type_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_type_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for extern type mismatch under #line',
        required_substrings=['Spelling: virtual_scope_extern_type_mismatch_probe_diag_text.c:6402:14'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_function_redecl_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_function_redecl_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for function redeclaration conflict under #line',
        required_substrings=['Spelling: virtual_scope_function_redecl_conflict_probe_diag_text.c:6502:7'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_type_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_type_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header extern type mismatch under #line',
        required_substrings=['Spelling: virtual_scope_include_extern_type_mismatch_probe_diag_text.h:6602:14'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_function_redecl_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_function_redecl_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header function redeclaration conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_function_redecl_conflict_probe_diag_text.h:6702:7'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_static_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_static_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for extern/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_extern_static_mismatch_probe_diag_text.c:7202:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_tentative_static_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_tentative_static_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for tentative/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_tentative_static_conflict_probe_diag_text.c:7302:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_static_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_static_mismatch_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header extern/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_extern_static_mismatch_probe_diag_text.h:7402:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_tentative_static_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_tentative_static_conflict_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header tentative/static linkage conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_tentative_static_conflict_probe_diag_text.h:7502:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_block_extern_different_type_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_block_extern_different_type_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for block-scope extern type-conflict under #line',
        required_substrings=['Spelling: virtual_scope_block_extern_type_conflict_probe_diag_text.c:8204:18'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_block_extern_different_type_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_block_extern_different_type_spelling_strict.c',
        note='text diagnostics should preserve remapped spelling for include-header block-scope extern type-conflict under #line',
        required_substrings=['Spelling: virtual_scope_include_block_extern_type_conflict_probe_diag_text.h:8304:18'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c',
        note='strict frontier: multi-TU extern type-conflict should preserve source spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_extern_type_conflict_probe_lib_diag_text.c:9901:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c',
        note='regression guard: multi-TU extern type-conflict should keep semantic spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_extern_type_conflict_probe_lib_diag_text.c:9901:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c',
        note='strict frontier: multi-TU include extern type-conflict should preserve source spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_include_extern_type_conflict_probe_header_diag_text.h:10001:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_include_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c',
        note='regression guard: multi-TU include extern type-conflict should keep semantic spelling under #line',
        required_substrings=['Spelling: virtual_scope_multitu_include_extern_type_conflict_probe_header_diag_text.h:10001:7'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_type_conflict_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: extern-array mismatch should emit linkage conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_array_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array mismatch should emit linkage conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_mismatch_first_decl_line_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_first_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch with first declaration remapped by #line should emit conflict diagnostics',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_mismatch_second_decl_line_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_second_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch with second declaration remapped by #line should emit conflict diagnostics',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_vs_scalar_conflict_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_vs_scalar_conflict_spelling_strict.c',
        note='control lane: extern array-vs-scalar redeclaration should still emit conflict diagnostics under #line',
        required_substrings=['Spelling: virtual_scope_extern_array_vs_scalar_conflict_probe_diag_text.c:15302:12'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_include_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict_main.c',
        note='strict frontier: multi-TU extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_extern_array_def_mismatch_spelling_strict_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict_main.c',
        note='strict frontier: multi-TU include extern-array declaration/definition extent mismatch should emit conflict diagnostics under #line remap',
        required_substrings=['Conflicting types for variable'],
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_multitu_include_extern_array_def_mismatch_spelling_strict_lib.c'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_type_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_extern_type_mismatch_rich_strict.c',
        note='control lane: extern type-mismatch diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6002,
        expected_column=14,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_function_redecl_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_function_redecl_conflict_rich_strict.c',
        note='control lane: function redeclaration-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6102,
        expected_column=7,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_type_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_extern_type_mismatch_rich_strict.c',
        note='control lane: include-header extern type-mismatch diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6202,
        expected_column=14,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_function_redecl_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_function_redecl_conflict_rich_strict.c',
        note='control lane: include-header function redeclaration-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6302,
        expected_column=7,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_static_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_extern_static_mismatch_rich_strict.c',
        note='frontier lane: extern/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6802,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_tentative_static_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_tentative_static_conflict_rich_strict.c',
        note='frontier lane: tentative/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=6902,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_static_mismatch_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_extern_static_mismatch_rich_strict.c',
        note='frontier lane: include-header extern/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7002,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_tentative_static_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_tentative_static_conflict_rich_strict.c',
        note='frontier lane: include-header tentative/static linkage-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7102,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_block_extern_different_type_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_block_extern_different_type_rich_strict.c',
        note='frontier lane: block-scope extern type-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7804,
        expected_column=18,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_block_extern_different_type_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_include_block_extern_different_type_rich_strict.c',
        note='frontier lane: include-header block-scope extern type-conflict diagnostics JSON should carry remapped line/file/hint under #line',
        expected_codes=[2000],
        expected_line=7904,
        expected_column=18,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c',
        note='frontier lane: multi-TU extern type-conflict diagnostics JSON should preserve remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9501,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c',
        note='regression guard: multi-TU extern type-conflict should keep semantic remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9501,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c',
        note='frontier lane: multi-TU include extern type-conflict diagnostics JSON should preserve remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9601,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_current_linkstage_pass',
        source=PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c',
        note='regression guard: multi-TU include extern type-conflict should keep semantic remapped location richness under #line',
        expected_codes=[2000],
        expected_line=9601,
        expected_column=14,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_main.c', PROBE_DIR / 'diagnostics/10__probe_diagjson_line_directive_multitu_include_extern_type_conflict_rich_strict_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: extern-array mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=11502,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_array_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=11602,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_def_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: extern-array declaration/definition mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=12902,
        expected_column=5,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_include_extern_array_def_mismatch_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_include_extern_array_def_mismatch_spelling_strict.c',
        note='strict frontier: include extern-array declaration/definition mismatch diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=13001,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_mismatch_first_decl_line_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_first_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch first-decl placement diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=15101,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='10__probe_diagjson_line_directive_extern_array_mismatch_second_decl_line_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/10__probe_diag_line_directive_extern_array_mismatch_second_decl_line_spelling_strict.c',
        note='strict frontier: extern-array mismatch second-decl placement diagnostics JSON should preserve remapped file/line under #line',
        expected_codes=[2000],
        expected_line=15201,
        expected_column=12,
        expected_has_file=True,
    ),
]
