from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='13__probe_phi_continue_runtime',
        source=PROBE_DIR / 'runtime/13__probe_phi_continue_runtime.c',
        note='loop-carried accumulator with continue/break edges should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='13__probe_short_circuit_chain_runtime',
        source=PROBE_DIR / 'runtime/13__probe_short_circuit_chain_runtime.c',
        note='nested short-circuit chain side effects should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='13__probe_struct_copy_runtime',
        source=PROBE_DIR / 'runtime/13__probe_struct_copy_runtime.c',
        note='struct return and by-value copy/update path should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='13__probe_ptr_stride_runtime',
        source=PROBE_DIR / 'runtime/13__probe_ptr_stride_runtime.c',
        note='pointer-difference scaling and indexed pointer loads should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='13__probe_global_init_runtime',
        source=PROBE_DIR / 'runtime/13__probe_global_init_runtime.c',
        note='global partial initializer and zero-fill behavior should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='13__probe_fnptr_ternary_decay_runtime',
        source=PROBE_DIR / 'runtime/13__probe_fnptr_ternary_decay_runtime.c',
        note='function designators in ternary should decay to compatible function pointers',
    ),
    RuntimeProbe(
        probe_id='13__probe_fnptr_struct_return_select_runtime',
        source=PROBE_DIR / 'runtime/13__probe_fnptr_struct_return_select_runtime.c',
        note='ternary-selected function designators returning structs should preserve by-value call lowering and copy updates',
    ),
    RuntimeProbe(
        probe_id='13__probe_global_zero_fill_ptr_stride_runtime',
        source=PROBE_DIR / 'runtime/13__probe_global_zero_fill_ptr_stride_runtime.c',
        note='partial global initializers should zero-fill while pointer-difference and indexed loads remain stable across control edges',
    ),
    RuntimeProbe(
        probe_id='13__probe_struct_return_phi_copy_mesh_runtime',
        source=PROBE_DIR / 'runtime/13__probe_struct_return_phi_copy_mesh_runtime.c',
        note='struct-return selection and aggregate copy across loop-carried merges should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='13__probe_aggregate_phi_union_branch_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_aggregate_phi_union_branch_payload_runtime.c',
        note='branch-selected aggregate returns should preserve nested union arms and array fields through struct assignment',
    ),
    RuntimeProbe(
        probe_id='13__probe_aggregate_phi_union_ternary_loop_runtime',
        source=PROBE_DIR / 'runtime/13__probe_aggregate_phi_union_ternary_loop_runtime.c',
        note='ternary and loop-carried aggregate merges should preserve nested union payload copies and typed reads',
    ),
    RuntimeProbe(
        probe_id='13__probe_ptr_stride_call_lowering_mesh_runtime',
        source=PROBE_DIR / 'runtime/13__probe_ptr_stride_call_lowering_mesh_runtime.c',
        note='pointer-stride helper calls should preserve by-reference lowering and scaled row indexing',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave40_compound_literal_phi_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave40_compound_literal_phi_runtime.c',
        note='wave40 aggregate phi stress: compound literals, ternary-selected structs, and loop-carried copies should preserve field payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave41_switch_loop_aggregate_copy_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave41_switch_loop_aggregate_copy_runtime.c',
        note='wave41 aggregate/control-flow stress: switch-selected union payload copies through loop-carried struct assignment should preserve active-arm fields',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave41_ternary_nested_union_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave41_ternary_nested_union_payload_runtime.c',
        note='wave41 aggregate/control-flow stress: ternary-selected nested union/struct payload copies should preserve selected payload after mutation',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave41_union_array_switch_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave41_union_array_switch_payload_runtime.c',
        note='wave41 aggregate/control-flow stress: array-held union payloads copied through switch dispatch should preserve payload bytes',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave42_compound_literal_branch_phi_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave42_compound_literal_branch_phi_runtime.c',
        note='wave42 aggregate/control-flow stress: compound literals and branch-selected union payloads should preserve copied aggregate fields across loop joins',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave42_switch_loop_nested_union_array_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave42_switch_loop_nested_union_array_runtime.c',
        note='wave42 aggregate/control-flow stress: switch-selected rows with nested union arrays should preserve payloads through loop-carried copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave42_switch_continue_compound_literal_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave42_switch_continue_compound_literal_runtime.c',
        note='wave42 aggregate/control-flow stress: switch/continue edges and compound literal aggregate assignments should preserve nested union payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave43_branch_compound_literal_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave43_branch_compound_literal_payload_runtime.c',
        note='wave43 aggregate/control-flow stress: branch-selected compound literals and fallback aggregate copies should preserve union payload fields',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave43_switch_loop_union_array_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave43_switch_loop_union_array_payload_runtime.c',
        note='wave43 aggregate/control-flow stress: switch-selected nested union array rows should preserve payloads through loop-carried copies and continue edges',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave43_phi_copy_returned_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave43_phi_copy_returned_payload_runtime.c',
        note='wave43 aggregate/control-flow stress: returned aggregate payloads copied through ternary phi-like joins should preserve active union arms',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave43_returned_aggregate_checksum_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave43_returned_aggregate_checksum_runtime.c',
        note='wave43 aggregate/control-flow stress: switch-returned aggregate payload checksums should match clang after loop-carried updates',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave44_short_circuit_aggregate_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave44_short_circuit_aggregate_payload_runtime.c',
        note='wave44 aggregate/control-flow stress: short-circuit selected union payload copies should preserve active-arm fields and side-effect order',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave44_loop_return_slot_copy_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave44_loop_return_slot_copy_runtime.c',
        note='wave44 aggregate/control-flow stress: loop-carried aggregate copies and returned packet slots should preserve union payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave44_switch_short_circuit_union_array_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave44_switch_short_circuit_union_array_runtime.c',
        note='wave44 aggregate/control-flow stress: switch and short-circuit edges should preserve nested union-array payloads through continue paths',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave45_switch_aggregate_return_boundary_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave45_switch_aggregate_return_boundary_runtime.c',
        note='wave45 aggregate/control-flow IR runtime boundary stress: switch-returned union payloads should survive return slots and loop-carried copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave45_loop_compound_literal_union_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave45_loop_compound_literal_union_runtime.c',
        note='wave45 aggregate/control-flow IR runtime boundary stress: compound literal aggregate assignments should preserve nested union rows through branch joins',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave45_switch_continue_nested_array_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave45_switch_continue_nested_array_runtime.c',
        note='wave45 aggregate/control-flow IR runtime boundary stress: switch and continue edges should preserve nested union array payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave46_nested_return_slot_array_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave46_nested_return_slot_array_runtime.c',
        note='wave46 codegen/IR runtime stress: nested return-slot aggregate values and array fields should survive loop-carried copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave46_pointer_array_compound_assign_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave46_pointer_array_compound_assign_runtime.c',
        note='wave46 codegen/IR runtime stress: pointer-array lowering and compound assignment through cursor-derived indexes should match clang',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave46_phi_compound_assignment_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave46_phi_compound_assignment_payload_runtime.c',
        note='wave46 codegen/IR runtime stress: phi-like aggregate copies with union payload compound assignment should preserve active fields',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave46_cross_block_struct_abi_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave46_cross_block_struct_abi_runtime.c',
        note='wave46 codegen/IR runtime stress: cross-basic-block struct return ABI through a function pointer should preserve by-value payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave47_switch_loop_payload_copy_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave47_switch_loop_payload_copy_runtime.c',
        note='wave47 codegen/IR runtime stress: switch-selected union payload copies through loop-carried joins should preserve aggregate fields',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave47_compound_literal_branch_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave47_compound_literal_branch_payload_runtime.c',
        note='wave47 codegen/IR runtime stress: compound literal aggregate payloads crossing branch joins should preserve nested fields',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave47_nested_return_slot_phi_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave47_nested_return_slot_phi_runtime.c',
        note='wave47 codegen/IR runtime stress: nested return-slot aggregate values should survive phi-like branch selection and copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave47_pointer_array_compound_phi_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave47_pointer_array_compound_phi_runtime.c',
        note='wave47 codegen/IR runtime stress: pointer-array compound assignments through phi-like cursor updates should match clang',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave48_phi_union_compound_literal_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave48_phi_union_compound_literal_runtime.c',
        note='wave48 codegen/IR runtime stress: union payloads selected through phi-like compound literal joins should match clang',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave48_switch_return_slot_union_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave48_switch_return_slot_union_runtime.c',
        note='wave48 codegen/IR runtime stress: switch-returned union payloads should survive return-slot copies and mode-dependent reads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave48_pointer_phi_compound_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave48_pointer_phi_compound_runtime.c',
        note='wave48 codegen/IR runtime stress: pointer-derived writes and compound literal row replacement should match clang',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave48_nested_phi_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave48_nested_phi_payload_runtime.c',
        note='wave48 codegen/IR runtime stress: nested aggregate payloads should survive branch-selected phi-like copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave49_phi_switch_nested_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave49_phi_switch_nested_payload_runtime.c',
        note='wave49 codegen/IR runtime stress: switch and phi-like joins should preserve nested union/aggregate payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave49_compound_literal_copy_layout_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave49_compound_literal_copy_layout_runtime.c',
        note='wave49 codegen/IR runtime stress: compound literal aggregate copies should preserve layout-sensitive row payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave49_pointer_member_conversion_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave49_pointer_member_conversion_payload_runtime.c',
        note='wave49 codegen/IR runtime stress: pointer/member conversions and aggregate copies should preserve selected record payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave49_return_slot_loop_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave49_return_slot_loop_payload_runtime.c',
        note='wave49 codegen/IR runtime stress: return-slot payloads should survive loop-carried aggregate copies and union-mode reads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave50_loop_phi_continue_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave50_loop_phi_continue_payload_runtime.c',
        note='wave50 codegen/IR runtime stress: loop-carried phi-like joins and continue edges should preserve nested aggregate payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave50_switch_fallthrough_continue_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave50_switch_fallthrough_continue_payload_runtime.c',
        note='wave50 codegen/IR runtime stress: switch fallthrough and continue edges should preserve aggregate copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave50_compound_literal_return_slot_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave50_compound_literal_return_slot_runtime.c',
        note='wave50 codegen/IR runtime stress: compound literal aggregate copies should survive return-slot selection and rewrite chains',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave50_pointer_member_lvalue_payload_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave50_pointer_member_lvalue_payload_runtime.c',
        note='wave50 codegen/IR runtime stress: pointer/member lvalue conversions should preserve copied record payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave53_callback_aggregate_return_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave53_callback_aggregate_return_runtime.c',
        note='wave53 codegen/IR runtime stress: callbacks carrying by-value aggregate parameters and returns should preserve payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave53_switch_braced_join_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave53_switch_braced_join_runtime.c',
        note='wave53 codegen/IR runtime stress: fully-braced aggregate initializers through switch/loop joins should preserve copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave53_union_selected_conversion_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave53_union_selected_conversion_runtime.c',
        note='wave53 codegen/IR runtime stress: selected union members should remain valid through tag-directed conversion copies',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave53_pointer_member_writeback_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave53_pointer_member_writeback_runtime.c',
        note='wave53 codegen/IR runtime stress: pointer/member writes after aggregate copies should preserve returned payloads',
    ),
    RuntimeProbe(
        probe_id='13__probe_wave56_array_element_nested_union_struct_copy_runtime',
        source=PROBE_DIR / 'runtime/13__probe_wave56_array_element_nested_union_struct_copy_runtime.c',
        note='wave56 codegen/IR regression: array-element assignment from a pointer-dereferenced large nested-union struct must copy the full materialized ABI object',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_if_missing_lparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_if_missing_lparen_parser_presence.c',
        note="text diagnostics should preserve parser missing '(' line under #line remap for if",
        required_substrings=["Error: expected '(' after 'if' at line 132003"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_if_missing_lparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_if_missing_lparen_parser_presence.c',
        note="text diagnostics should preserve parser missing '(' line under include #line remap for if",
        required_substrings=["Error: expected '(' after 'if' at line 132053"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_switch_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note='text diagnostics should preserve parser switch-header parse failure line under #line remap',
        required_substrings=["Error: expected ')' after switch condition at virtual_probe_ir_parser_switch_missing_rparen_diagjson.c:132103"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_switch_missing_rparen_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note='text diagnostics should preserve parser switch-header parse failure line under include #line remap',
        required_substrings=["Error: expected ')' after switch condition at virtual_probe_ir_include_parser_switch_missing_rparen_diagjson.h:132153"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_for_missing_first_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_for_missing_first_semicolon_parser_presence.c',
        note="text diagnostics should preserve parser missing first ';' in for-header under #line remap",
        required_substrings=["line 135004"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_for_missing_first_semicolon_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_for_missing_first_semicolon_parser_presence.c',
        note="text diagnostics should preserve parser missing first ';' in include for-header under #line remap",
        required_substrings=["line 135054"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_if_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for if',
        required_substrings=['line 134003'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_if_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for if',
        required_substrings=['line 134053'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for while',
        required_substrings=['line 134103'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for while',
        required_substrings=['line 134153'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for for',
        required_substrings=['line 134203'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for for',
        required_substrings=['line 134253'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_switch_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_switch_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under #line remap for switch',
        required_substrings=['line 134303'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_switch_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_switch_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser missing-body line under include #line remap for switch',
        required_substrings=['line 134353'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_nested_if_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_nested_if_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser nested if->while missing-body line under #line remap',
        required_substrings=['line 134404'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_nested_if_while_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_nested_if_while_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser nested if->while missing-body line under include #line remap',
        required_substrings=['line 134454'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_nested_switch_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_nested_switch_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser nested switch->for missing-body line under #line remap',
        required_substrings=['line 134504'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_line_directive_include_nested_switch_for_missing_body_parser_text_strict',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_nested_switch_for_missing_body_parser_presence.c',
        note='text diagnostics should preserve parser nested switch->for missing-body line under include #line remap',
        required_substrings=['line 134554'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_too_many_args_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_too_many_args_reject.c',
        note='function-pointer call should reject too many arguments for fixed-arity target',
        required_substrings=['Too many arguments'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_too_few_args_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_too_few_args_reject.c',
        note='function-pointer call should reject too few arguments for fixed-arity target',
        required_substrings=['Too few arguments'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_mod_float_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_mod_float_reject.c',
        note='modulo with floating operand should be rejected',
        required_substrings=["Operator '%'"],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_assign_incompatible_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_assign_incompatible_reject.c',
        note='function-pointer assignment with incompatible signature should be rejected',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_nested_qualifier_loss_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_nested_qualifier_loss_reject.c',
        note='nested function-pointer assignment should reject qualifier loss at pointee depth',
        required_substrings=['discards qualifiers'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_voidptr_to_fnptr_assign_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_voidptr_to_fnptr_assign_reject.c',
        note='assignment from void* to function pointer should be rejected',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_to_voidptr_assign_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_to_voidptr_assign_reject.c',
        note='assignment from function pointer to void* should be rejected',
        required_substrings=['Incompatible assignment operands'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_nested_volatile_qualifier_loss_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_nested_volatile_qualifier_loss_reject.c',
        note='nested function-pointer assignment should reject volatile qualifier loss at pointee depth',
        required_substrings=['discards qualifiers'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_fnptr_deep_const_qualifier_loss_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_fnptr_deep_const_qualifier_loss_reject.c',
        note='multi-level function-pointer assignment should reject deep const qualifier loss',
        required_substrings=['discards qualifiers'],
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_if_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_if_missing_lparen.c',
        note="parser should emit diagnostics for missing '(' in if statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_while_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_while_missing_lparen.c',
        note="parser should emit diagnostics for missing '(' in while statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_lparen.c',
        note="parser should emit diagnostics for missing '(' in do-while condition",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_for_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_for_missing_lparen.c',
        note="parser should emit diagnostics for missing '(' in for statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_if_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_if_missing_rparen.c',
        note="parser should emit diagnostics for missing ')' in if statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_while_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_while_missing_rparen.c',
        note="parser should emit diagnostics for missing ')' in while statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_rparen.c',
        note="parser should emit diagnostics for missing ')' in do-while condition",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_for_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_for_missing_rparen.c',
        note="parser should emit diagnostics for missing ')' in for statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_for_missing_first_semicolon',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_for_missing_first_semicolon.c',
        note="parser should emit diagnostics for missing first ';' in for header",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_for_missing_second_semicolon',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_for_missing_second_semicolon.c',
        note="parser should emit diagnostics for missing second ';' in for header",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_for_missing_second_semicolon_simple',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_for_missing_second_semicolon_simple.c',
        note="parser should emit diagnostics for missing second ';' in minimal for-header form",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_if_missing_condition',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_if_missing_condition.c',
        note='parser should emit diagnostics for missing condition expression in if statement',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_while',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_while.c',
        note="parser should emit diagnostics for missing 'while' in do-while statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_while_simple',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_while_simple.c',
        note="parser should emit diagnostics for missing 'while' in reduced do-while form",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_condition',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_condition.c',
        note='parser should emit diagnostics for missing condition expression in do-while statement',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_semicolon',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_semicolon.c',
        note="parser should emit diagnostics for missing ';' after do-while condition",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_for_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_for_missing_body.c',
        note='parser should emit diagnostics for missing for-loop body statement',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_while_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_while_missing_body.c',
        note='parser should emit diagnostics for missing while-loop body statement',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_body.c',
        note='parser should emit diagnostics for missing do-while loop body statement',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_do_while_missing_body_simple',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_do_while_missing_body_simple.c',
        note='parser should emit diagnostics for minimal missing do-while loop body statement',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_switch_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_switch_missing_body.c',
        note='parser should emit diagnostics for missing switch statement body',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_switch_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_switch_missing_lparen.c',
        note="parser should emit diagnostics for missing '(' in switch statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_while_empty_condition',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_while_empty_condition.c',
        note='parser should emit diagnostics for missing while condition expression',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_switch_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_switch_missing_rparen.c',
        note="parser should emit diagnostics for missing ')' in switch statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_if_missing_then_stmt',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_if_missing_then_stmt.c',
        note='parser should emit diagnostics for missing then-statement in if',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_else_missing_stmt_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_else_missing_stmt_reject.c',
        note='parser should emit diagnostics for missing statement in else',
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_switch_missing_lbrace',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_switch_missing_lbrace.c',
        note="parser should emit diagnostics for missing '{' in switch statement",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_switch_case_missing_colon',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_switch_case_missing_colon.c',
        note="parser should emit diagnostics for missing ':' in switch case label",
    ),
    DiagnosticProbe(
        probe_id='13__probe_diag_parser_switch_default_missing_colon_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diag_parser_switch_default_missing_colon.c',
        note="parser should emit diagnostics for missing ':' in switch default label",
    ),
]

DIAG_PROBES.extend([
    DiagnosticProbe(
        probe_id='13__probe_wave54_if_missing_condition_then_aggregate_return',
        source=PROBE_DIR.parent / 'cases/13__ir_reject_wave54_if_missing_rparen_then_aggregate_return.c',
        note='wave54 recovery/lowering boundary: malformed if header should recover before a valid aggregate-return tail',
    ),
    DiagnosticProbe(
        probe_id='13__probe_wave54_for_missing_semicolon_then_union_switch',
        source=PROBE_DIR.parent / 'cases/13__ir_reject_wave54_for_missing_semicolon_then_union_switch.c',
        note='wave54 recovery/lowering boundary: malformed for header should recover before a valid union/switch tail',
    ),
    DiagnosticProbe(
        probe_id='13__probe_wave54_switch_missing_rparen_then_loop_copy',
        source=PROBE_DIR.parent / 'cases/13__ir_reject_wave54_switch_missing_rparen_then_loop_copy.c',
        note='wave54 recovery/lowering boundary: malformed switch header should recover before a valid aggregate-copy loop tail',
    ),
    DiagnosticProbe(
        probe_id='13__probe_wave55_initializer_missing_semicolon_then_aggregate_return',
        source=PROBE_DIR.parent / 'cases/13__ir_reject_wave55_initializer_missing_semicolon_then_aggregate_return.c',
        note='wave55 recovery/lowering boundary: malformed aggregate-initializer declaration should recover before a valid aggregate-return tail',
    ),
    DiagnosticProbe(
        probe_id='13__probe_wave55_declarator_missing_rparen_then_vla_pointer',
        source=PROBE_DIR.parent / 'cases/13__ir_reject_wave55_declarator_missing_rparen_then_vla_pointer.c',
        note='wave55 recovery/lowering boundary: malformed declarator should recover before a valid VLA-pointer lowering tail',
    ),
    DiagnosticProbe(
        probe_id='13__probe_wave55_label_missing_colon_then_union_copy',
        source=PROBE_DIR.parent / 'cases/13__ir_reject_wave55_label_missing_colon_then_union_copy.c',
        note='wave55 recovery/lowering boundary: malformed case label should recover before a valid union-copy lowering tail',
    ),
])

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_if_missing_lparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_if_missing_lparen_parser_presence.c',
        note="reduced threshold: #line if-missing-'(' currently emits semantic-only diagjson payload at remapped function location",
        expected_codes=[2000],
        expected_line=132001,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_if_missing_lparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_if_missing_lparen_parser_presence.c',
        note="reduced threshold: include #line if-missing-'(' currently emits semantic-only diagjson payload at remapped function location",
        expected_codes=[2000],
        expected_line=132051,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_switch_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_switch_missing_rparen_parser_presence.c',
        note="strict frontier: #line switch-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=132103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_switch_missing_rparen_parser_presence.c',
        note="strict frontier: include #line switch-missing-')' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=132153,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_for_missing_first_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_for_missing_first_semicolon_parser_presence.c',
        note="strict frontier: #line for-missing-first-';' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=135004,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_for_missing_first_semicolon_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_for_missing_first_semicolon_parser_presence.c',
        note="strict frontier: include #line for-missing-first-';' should preserve parser diagnostics JSON presence",
        expected_codes=[1000],
        expected_line=135054,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_if_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_if_missing_body_parser_presence.c',
        note='strict frontier: #line if-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134003,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_if_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_if_missing_body_parser_presence.c',
        note='strict frontier: include #line if-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134053,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_while_missing_body_parser_presence.c',
        note='strict frontier: #line while-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_while_missing_body_parser_presence.c',
        note='strict frontier: include #line while-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134153,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_for_missing_body_parser_presence.c',
        note='strict frontier: #line for-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134203,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_for_missing_body_parser_presence.c',
        note='strict frontier: include #line for-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134253,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_switch_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_switch_missing_body_parser_presence.c',
        note='strict frontier: #line switch-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_switch_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_switch_missing_body_parser_presence.c',
        note='strict frontier: include #line switch-missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134353,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_nested_if_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_nested_if_while_missing_body_parser_presence.c',
        note='strict frontier: nested #line if->while missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134404,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_nested_if_while_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_nested_if_while_missing_body_parser_presence.c',
        note='strict frontier: include nested #line if->while missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134454,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_nested_switch_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_nested_switch_for_missing_body_parser_presence.c',
        note='strict frontier: nested #line switch->for missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134504,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_line_directive_include_nested_switch_for_missing_body_parser_presence_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_line_directive_include_nested_switch_for_missing_body_parser_presence.c',
        note='strict frontier: include nested #line switch->for missing-body should preserve parser diagnostics JSON presence',
        expected_codes=[1000],
        expected_line=134554,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_if_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_if_missing_lparen.c',
        note="diagnostics JSON should be emitted for missing '(' in if statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_while_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_while_missing_lparen.c',
        note="diagnostics JSON should be emitted for missing '(' in while statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_lparen.c',
        note="diagnostics JSON should be emitted for missing '(' in do-while condition parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_for_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_for_missing_lparen.c',
        note="diagnostics JSON should be emitted for missing '(' in for statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_if_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_if_missing_rparen.c',
        note="diagnostics JSON should be emitted for missing ')' in if statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_while_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_while_missing_rparen.c',
        note="diagnostics JSON should be emitted for missing ')' in while statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_rparen.c',
        note="diagnostics JSON should be emitted for missing ')' in do-while condition parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_for_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_for_missing_rparen.c',
        note="diagnostics JSON should be emitted for missing ')' in for statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_for_missing_first_semicolon',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_for_missing_first_semicolon.c',
        note="diagnostics JSON should be emitted for missing first ';' in for header",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_for_missing_second_semicolon',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_for_missing_second_semicolon.c',
        note="diagnostics JSON should be emitted for missing second ';' in for header",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_for_missing_second_semicolon_simple',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_for_missing_second_semicolon_simple.c',
        note="diagnostics JSON should be emitted for missing second ';' in minimal for-header form",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_if_missing_condition',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_if_missing_condition.c',
        note='diagnostics JSON should be emitted for missing condition expression in if statement parser recovery',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_while',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_while.c',
        note="diagnostics JSON should be emitted for missing 'while' in do-while statement",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_while_simple',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_while_simple.c',
        note="diagnostics JSON should be emitted for missing 'while' in minimal do-while form",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_condition',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_condition.c',
        note='diagnostics JSON should be emitted for missing condition expression in do-while condition parser recovery',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_semicolon',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_semicolon.c',
        note="diagnostics JSON should be emitted for missing ';' after do-while condition",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_for_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_for_missing_body.c',
        note='diagnostics JSON should be emitted for missing for-loop body statement',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_while_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_while_missing_body.c',
        note='diagnostics JSON should be emitted for missing while-loop body statement',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_body.c',
        note='diagnostics JSON should be emitted for missing do-while loop body statement',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_do_while_missing_body_simple',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_do_while_missing_body_simple.c',
        note='diagnostics JSON should be emitted for minimal missing do-while loop body statement',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_switch_missing_body',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_switch_missing_body.c',
        note='diagnostics JSON should be emitted for missing switch body statement',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_switch_missing_lparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_switch_missing_lparen.c',
        note="diagnostics JSON should be emitted for missing '(' in switch statement",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_while_empty_condition',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_while_empty_condition.c',
        note='diagnostics JSON should be emitted for missing while condition expression',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_switch_missing_rparen',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_switch_missing_rparen.c',
        note="diagnostics JSON should be emitted for missing ')' in switch statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_if_missing_then_stmt',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_if_missing_then_stmt.c',
        note='diagnostics JSON should be emitted for missing then-statement in if parser recovery',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_else_missing_stmt_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_else_missing_stmt_reject.c',
        note='diagnostics JSON should be emitted for missing statement in else parser recovery',
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_switch_missing_lbrace',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_switch_missing_lbrace.c',
        note="diagnostics JSON should be emitted for missing '{' in switch statement parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_switch_case_missing_colon',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_switch_case_missing_colon.c',
        note="diagnostics JSON should be emitted for missing ':' in switch case label parser recovery",
    ),
    DiagnosticJsonProbe(
        probe_id='13__probe_diagjson_parser_switch_default_missing_colon_reject',
        source=PROBE_DIR / 'diagnostics/13__probe_diagjson_parser_switch_default_missing_colon.c',
        note="diagnostics JSON should be emitted for missing ':' in switch default label parser recovery",
    ),
]
