from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='03__probe_runtime_wave40_object_replacement_tail_call_strict',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave40_object_replacement_tail_call_strict.c',
        note='strict frontier: an object-like replacement with prefix tokens must rescan its trailing function-like macro together with the caller-supplied argument list',
        promoted_test_id='03__runtime_wave40_object_replacement_tail_call_strict',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave40_function_replacement_tail_call_strict',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave40_function_replacement_tail_call_strict.c',
        note='strict frontier: a function-like replacement with prefix tokens must rescan its trailing function-like macro together with the next caller-supplied argument list',
        promoted_test_id='03__runtime_wave40_function_replacement_tail_call_strict',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave40_replacement_tail_provenance_strict',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave40_replacement_tail_provenance_strict.c',
        note='strict frontier: replacement-tail function rescanning must preserve remapped __FILE__ and __LINE__ provenance across the caller boundary',
        promoted_test_id='03__runtime_wave40_replacement_tail_provenance_strict',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave40_mutual_function_disable_rescan_strict',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave40_mutual_function_disable_rescan_strict.c',
        note='strict frontier: chained mutually recursive function macros must rescan caller argument lists while preserving the standard disable and re-enable boundary',
        promoted_test_id='03__runtime_wave40_mutual_function_disable_rescan_strict',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave38_guard_collision_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave38_guard_collision_state.c',
        note='wave38 guard collision: a shared guard macro should suppress the second header body without perturbing the first header state',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave38_guard_reopen_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave38_guard_reopen_state.c',
        note='wave38 guard reopen: clearing a header guard should permit a macro-rebound second include to emit a distinct declaration',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave38_pragma_once_nested_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave38_pragma_once_nested_state.c',
        note='wave38 pragma-once conditional state: nested active and inactive conditional includes should retain a single pragma-once header definition',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave37_include_rebind_tail_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave37_include_rebind_tail_state.c',
        note='wave37 macro/include state reentry: repeated header tail should replay under caller macro rebinds while guarded helpers remain stable',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave37_nested_tail_reentry_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave37_nested_tail_reentry_state.c',
        note='wave37 nested include reentry: guarded inner helper state should survive repeat includes while unguarded macro-dependent tails replay',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave37_inactive_noise_token_provenance',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave37_inactive_noise_token_provenance.c',
        note='wave37 macro provenance: inactive include noise should stay inert while token paste, stringize, and line-map runtime values remain stable',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave37_line_macro_callsite_provenance',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave37_line_macro_callsite_provenance.c',
        note='wave37 macro provenance: header-defined macros should report #line-remapped call-site file and line at runtime',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave36_nested_guard_reentry_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave36_nested_guard_reentry_state.c',
        note='wave36 macro/include state reentry: nested guarded helper state should survive repeat includes while inactive branch macro noise stays inert',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave36_include_return_redefine_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave36_include_return_redefine_state.c',
        note='wave36 macro/include state reentry: macro undef/redefine across include return should feed the next include without losing caller-visible tail state',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave36_token_paste_stringize_line_map',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave36_token_paste_stringize_line_map.c',
        note='wave36 macro provenance: token paste and stringize should honor #line remapped macro expansion and runtime call-site provenance',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave36_inactive_conditional_macro_noise',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave36_inactive_conditional_macro_noise.c',
        note='wave36 macro/include state reentry: inactive conditional macro undef/redefine and missing include noise should not perturb active state',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave35_include_state_reentry_diag_boundary',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave35_include_state_reentry_diag_boundary.c',
        note='wave35 macro/include state reentry: guarded helper plus unguarded macro-dependent tail should replay across caller rebinds while inactive diagnostic noise stays inert',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave35_line_stack_reentry_value',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave35_line_stack_reentry_value.c',
        note='wave35 line-map runtime boundary: repeated include tail should evaluate __LINE__ at the virtual header line while runtime resumes at the remapped main call site',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave35_macro_rebind_line_diag_boundary',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave35_macro_rebind_line_diag_boundary.c',
        note='wave35 macro state reentry: function-like macro rebind after inactive malformed preprocessor branch should preserve token paste, stringize, and runtime #line values',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave34_inactive_branch_macro_state_rebind',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave34_inactive_branch_macro_state_rebind.c',
        note='wave34 macro provenance: inactive branch include/macro noise should not perturb active token paste, stringize, macro state rebind, or #line runtime values',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave34_include_macro_state_current',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave34_include_macro_state_current.c',
        note='wave34 current threshold: caller-controlled macro state should feed an included header slot once and preserve pasted enum spelling plus remapped runtime call-site location',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave34_nested_include_line_value',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave34_nested_include_line_value.c',
        note='wave34 nested include remap: inner-header #line should feed __LINE__ into pasted constants while runtime __FILE__/__LINE__ follows the main remap',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave34_include_reentry_slot_rebind',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave34_include_reentry_slot_rebind.c',
        note='fixed baseline: guarded helper headers with unguarded macro-dependent tails should replay repeat includes under caller macro rebinds',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave33_token_paste_stringize_provenance',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave33_token_paste_stringize_provenance.c',
        note='wave33 macro provenance: token paste and two-level stringize should preserve #line-adjusted runtime call-site file and line',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave33_nested_macro_callsite_remap',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave33_nested_macro_callsite_remap.c',
        note='wave33 macro provenance: nested macro call chains should evaluate __FILE__/__LINE__ at the remapped outer call site',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave33_include_reentry_macro_state',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave33_include_reentry_macro_state.c',
        note='wave33 include provenance: guarded include reentry should preserve macro arity, token paste, stringize, and call-site remap at runtime',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave33_nested_include_line_remap',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave33_nested_include_line_remap.c',
        note='wave33 include provenance: nested included helpers should preserve header-defined token paste while runtime __LINE__ follows the remapped main call site',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave30_macro_line_stringize_paste',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave30_macro_line_stringize_paste.c',
        note='macro expansion should preserve token paste, two-level stringize, function-like invocation, and #line-adjusted __LINE__ at runtime',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave31_include_line_stringize_paste',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave31_include_line_stringize_paste.c',
        note='wave31 macro/include provenance: included-header token paste, stringize, and #line-adjusted __LINE__ should match clang at runtime',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave32_include_guard_reentry_line',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave32_include_guard_reentry_line.c',
        note='wave32 macro/include provenance: include guard reentry should preserve token paste, stringize, call-site __FILE__/__LINE__, and runtime parity',
    ),
    RuntimeProbe(
        probe_id='03__probe_runtime_wave32_inactive_conditional_macro_noise',
        source=PROBE_DIR / 'runtime/03__probe_runtime_wave32_inactive_conditional_macro_noise.c',
        note='wave32 macro provenance: inactive conditional include/macro noise should not perturb active token paste, stringize, or #line runtime values',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='03__probe_include_collision_inactive_angle_active_quote_long_clean',
        source=PROBE_DIR.parent / 'cases/03__include_collision_inactive_angle_active_quote_long_clean.c',
        note='clean-path parity: dead angle-include collision branch should not perturb the active longer quote-chain local-first resolution',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_collide2_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_collide2_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_collide2_p3"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_cycle_inactive_reject_active_pragma_once_clean',
        source=PROBE_DIR.parent / 'cases/03__include_cycle_inactive_reject_active_pragma_once_clean.c',
        note='clean-path parity: a dead recursive include cycle should stay inert while the active pure pragma-once three-hop graph resolves cleanly',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_defined_include_nested_post_inactive_noise_clean',
        source=PROBE_DIR.parent / 'cases/03__defined_include_nested_post_inactive_noise_clean.c',
        note='clean-path parity: post-include inactive macro-state noise should not perturb nested include defined/undef convergence',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_cycle_inactive_reject_active_guard_clean',
        source=PROBE_DIR.parent / 'cases/03__include_cycle_inactive_reject_active_guard_clean.c',
        note='clean-path parity: a dead recursive include cycle should stay inert while the active include-guard three-hop graph resolves cleanly',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_cycle_inactive_reject_active_mixed_guard_once_clean',
        source=PROBE_DIR.parent / 'cases/03__include_cycle_inactive_reject_active_mixed_guard_once_clean.c',
        note='clean-path parity: a dead recursive include cycle should stay inert while the active mixed include-guard/pragma-once graph resolves cleanly',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_defined_include_nested_inactive_noise_clean',
        source=PROBE_DIR.parent / 'cases/03__defined_include_nested_inactive_noise_clean.c',
        note='clean-path parity: inactive macro-state noise should not perturb nested include defined/undef convergence',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_collision_inactive_quote_active_angle_long_clean',
        source=PROBE_DIR.parent / 'cases/03__include_collision_inactive_quote_active_angle_long_clean.c',
        note='clean-path parity: dead quote-include collision branch should not perturb the active longer angle-chain search-order resolution',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_collide2_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_collide2_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_collide2_p3"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_collision_inactive_angle_active_mixed_quote_clean',
        source=PROBE_DIR.parent / 'cases/03__include_collision_inactive_angle_active_mixed_quote_clean.c',
        note='clean-path parity: dead angle-include collision branch should not perturb the active mixed-delimiter local-first resolution chain',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_mix2_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_mix2_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_mix2_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_mix2_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_defined_include_nested_undef_clean',
        source=PROBE_DIR.parent / 'cases/03__defined_include_nested_undef_clean.c',
        note='clean-path parity: nested include macro state should preserve defined visibility, ordered undefs, and final post-chain convergence',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_collision_inactive_quote_active_angle_clean',
        source=PROBE_DIR.parent / 'cases/03__include_collision_inactive_quote_active_angle_clean.c',
        note='clean-path parity: dead quote-include collision branch should not perturb active angle-chain search-order resolution',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_collide_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_collide_p2"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_collision_inactive_angle_active_quote_clean',
        source=PROBE_DIR.parent / 'cases/03__include_collision_inactive_angle_active_quote_clean.c',
        note='clean-path parity: dead angle-include collision branch should not perturb active quote-chain local-first resolution',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_collide_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_collide_p2"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_defined_include_cross_header_undef_clean',
        source=PROBE_DIR.parent / 'cases/03__defined_include_cross_header_undef_clean.c',
        note='clean-path parity: macro definition visibility and #undef convergence should remain consistent across include boundaries',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_inactive_missing_skip_order_chain_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_inactive_missing_skip_order_chain_clean.c',
        note='clean-path parity: dead #if branch should skip missing #include_next while active order chain still resolves cleanly',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_inactive_invalid_skip_mixed_chain_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_inactive_invalid_skip_mixed_chain_clean.c',
        note='clean-path parity: dead #if branch should skip invalid #include_next operand while active mixed-delimiter chain still resolves cleanly',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_nested_inactive_expr_once_chain_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_nested_inactive_expr_once_chain_clean.c',
        note='clean-path parity: nested inactive bad expression and missing #include_next should be skipped while active pragma-once include_next chain stays clean',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_once_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_once_p2"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_extra_tokens_diag_current_text',
        source=PROBE_DIR.parent / 'cases/03__include_next_extra_tokens_reject.c',
        note='current threshold: invalid #include_next operand with trailing tokens still emits text diagnostics even without diagjson export',
        required_substrings=['invalid #include operand'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_macro_trailing_diag_current_text',
        source=PROBE_DIR.parent / 'cases/03__include_next_macro_trailing_tokens_reject.c',
        note='current threshold: macro-expanded invalid #include_next operand still emits text diagnostics even without diagjson export',
        required_substrings=['invalid #include operand'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_error_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_error_location_reject.c',
        note='#line virtual line should propagate into #error diagnostic location',
        required_substrings=['Error at (777:'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_error_current_physical_line',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_error_current_physical_line.c',
        note='fixed baseline: #error diagnostic now reports remapped virtual line',
        required_substrings=['Error at (777:1): bucket03 - probe - error'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_error_filename_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_error_filename_location_reject.c',
        note='#line virtual filename should propagate into #error diagnostic spelling location',
        required_substrings=['Spelling: virtual_pp_error_filename_probe.c:777:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_error_filename_current_physical',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_error_filename_current_physical.c',
        note='fixed baseline: #error diagnostic spelling now uses remapped virtual filename',
        required_substrings=['virtual_pp_error_filename_probe_current.c:777:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_warning_filename_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_warning_filename_location_reject.c',
        note='#line virtual filename should propagate into #warning diagnostic spelling location',
        required_substrings=['Spelling: virtual_pp_warning_filename_probe.c:888:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_warning_filename_current_physical',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_warning_filename_current_physical.c',
        note='fixed baseline: #warning diagnostic spelling now uses remapped virtual filename',
        required_substrings=['virtual_pp_warning_filename_probe_current.c:888:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_pragma_stdc_filename_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_pragma_stdc_filename_location_reject.c',
        note='#line virtual filename should propagate into #pragma STDC diagnostic spelling location',
        required_substrings=['Spelling: virtual_pragma_stdc_filename_probe.c:444:9'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_pragma_stdc_filename_current_physical',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_pragma_stdc_filename_current_physical.c',
        note='fixed baseline: #pragma STDC diagnostic spelling now uses remapped virtual filename',
        required_substrings=['virtual_pragma_stdc_filename_probe_current.c:444:9'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_include_error_filename_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_include_error_filename_location_reject.c',
        note='#line virtual filename in included header should propagate into #error diagnostic spelling location',
        required_substrings=['Spelling: virtual_pp_include_error_header_probe.h:615:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_include_error_filename_current_physical',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_include_error_filename_current_physical.c',
        note='fixed baseline: include #error diagnostic spelling now uses remapped virtual header filename',
        required_substrings=['virtual_pp_include_error_header_probe_current.h:615:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_include_warning_filename_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_include_warning_filename_location_reject.c',
        note='#line virtual filename in included header should propagate into #warning diagnostic spelling location',
        required_substrings=['Spelling: virtual_pp_include_warning_header_probe.h:616:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_include_warning_filename_current_physical',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_include_warning_filename_current_physical.c',
        note='fixed baseline: include #warning diagnostic spelling now uses remapped virtual header filename',
        required_substrings=['virtual_pp_include_warning_header_probe_current.h:616:1'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_include_pragma_stdc_filename_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_include_pragma_stdc_filename_location_reject.c',
        note='#line virtual filename in included header should propagate into #pragma STDC diagnostic spelling location',
        required_substrings=['Spelling: virtual_pp_include_pragma_header_probe.h:617:9'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_line_directive_include_pragma_stdc_filename_current_physical',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_include_pragma_stdc_filename_current_physical.c',
        note='fixed baseline: include #pragma STDC diagnostic spelling now uses remapped virtual header filename',
        required_substrings=['virtual_pp_include_pragma_header_probe_current.h:617:9'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_if0_then_elif_order_chain_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_if0_then_elif_order_chain_clean.c',
        note='clean-path parity: dead #if and dead #else include_next branches should not perturb the taken #elif order chain',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_defined_skip_invalid_mixed_chain_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_defined_skip_invalid_mixed_chain_clean.c',
        note='clean-path parity: absent defined-condition should skip invalid #include_next while the active mixed-delimiter chain resolves cleanly',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_defined_include_nested_conditional_recheck_clean',
        source=PROBE_DIR.parent / 'cases/03__defined_include_nested_conditional_recheck_clean.c',
        note='clean-path parity: nested include macro convergence should survive a compound conditional recheck and inactive post-chain noise',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_elif_defined_macro_state_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_elif_defined_macro_state_clean.c',
        note='clean-path parity: absent defined-condition and dead fallback branches should still leave the active include_next order chain and tail macro state intact',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_ord_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_include_next_defined_mixed_chain_recheck_clean',
        source=PROBE_DIR.parent / 'cases/03__include_next_defined_mixed_chain_recheck_clean.c',
        note='clean-path parity: dead defined-gated invalid include_next branches should not perturb the active mixed-delimiter include_next chain or final tail macro visibility',
        expect_any_diagnostic=False,
        fisics_args=[
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p1"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p2"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p3"}',
            f'-I{PROBE_DIR.parent / "cases/pp_inext_mix_p4"}',
        ],
    ),
    DiagnosticProbe(
        probe_id='03__probe_defined_include_nested_reentry_macro_state_clean',
        source=PROBE_DIR.parent / 'cases/03__defined_include_nested_reentry_macro_state_clean.c',
        note='clean-path parity: nested include defined/undef convergence should preserve the final visible macro set across a guarded reentry-style post-check',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='03__probe_macro_callsite_line_remap_arity_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_callsite_line_remap_arity_strict.c',
        note='strict macro provenance: #line-remapped macro call-site arity diagnostics should report virtual call-site file and line',
        required_substrings=['virtual_macro_callsite_arity.c:312:39', "requires 2 argument(s), got 1"],
    ),
    DiagnosticProbe(
        probe_id='03__probe_macro_include_reentry_arity_bridge_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_include_reentry_arity_bridge.c',
        note='strict macro provenance: include reentry with #line-remapped header should report the virtual header call-site for arity diagnostics',
        required_substrings=['virtual_macro_reentry_header.h:430:42', "requires 3 argument(s), got 2"],
    ),
    DiagnosticProbe(
        probe_id='03__probe_macro_gnu_comma_line_remap_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_gnu_comma_line_remap_current.c',
        note='strict macro provenance: GNU comma vaargs rejection should report the #line-remapped macro call site',
        required_substrings=['virtual_macro_gnu_comma.c:531:34', "GNU ', ##__VA_ARGS__' extension is not supported"],
    ),
    DiagnosticProbe(
        probe_id='03__probe_macro_token_paste_line_remap_current',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_token_paste_line_remap_current.c',
        note='current threshold: token-paste hex-literal failure should at least preserve the #line-remapped call-site spelling',
        required_substrings=['virtual_macro_token_paste.c:641:50', 'Hex literal requires at least one hex digit'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_wave31_include_line_tokenpaste_diag_current',
        source=PROBE_DIR / 'diagnostics/03__probe_wave31_include_line_tokenpaste_diag.c',
        note='current threshold: include-wrapped token-paste failure should still emit text diagnostics for the paste failure and macro expansion failure',
        required_substrings=['Hex literal requires at least one hex digit', 'macro expansion failed'],
    ),
    DiagnosticProbe(
        probe_id='03__probe_wave31_diagjson_text_parity_stringize_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_wave31_diagjson_text_parity_stringize.c',
        note='strict wave31 macro provenance: stringize companion plus arity failure should report the #line-remapped virtual call-site in text diagnostics',
        required_substrings=['virtual_wave31_diagjson_text_parity.c:1331:41', "requires 2 argument(s), got 1"],
    ),
    DiagnosticProbe(
        probe_id='03__probe_wave32_include_guard_macro_arity_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_wave32_include_guard_macro_arity_diag.c',
        note='strict wave32 macro provenance: guarded include header with inactive macro noise should report #line-remapped header call-site for arity diagnostics',
        required_substrings=["requires 2 argument(s), got 1"],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_include_next_missing_target_basic_strict',
        source=PROBE_DIR.parent / 'cases/03__include_next_missing.c',
        note='strict parity: missing first-hop #include_next target should export preprocessor diagnostics JSON with file, line, and column',
        expected_codes=[3000],
        expected_line=1,
        expected_column=15,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_include_next_missing_target_mid_chain_strict',
        source=PROBE_DIR.parent / 'cases/03__include_next_missing_mid_chain.c',
        note='strict parity: missing mid-chain #include_next target should export preprocessor diagnostics JSON with file, line, and column',
        expected_codes=[3000],
        expected_line=1,
        expected_column=10,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_include_next_extra_tokens_strict',
        source=PROBE_DIR.parent / 'cases/03__include_next_extra_tokens_reject.c',
        note='strict frontier: invalid #include_next operand with trailing tokens should still export diagnostics JSON',
        expected_codes=[3000],
        expected_line=1,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_include_next_macro_trailing_strict',
        source=PROBE_DIR.parent / 'cases/03__include_next_macro_trailing_tokens_reject.c',
        note='strict frontier: macro-expanded invalid #include_next operand should still export diagnostics JSON',
        expected_codes=[3000],
        expected_line=2,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_error_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_error_location_reject.c',
        note='diagnostics JSON should honor #line remap for #error directive diagnostics',
        expected_codes=[3000],
        expected_line=777,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_error_current_physical_line',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_error_current_physical_line.c',
        note='fixed baseline: diagnostics JSON now reports remapped line for #error directive diagnostics',
        expected_codes=[3000],
        expected_line=777,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_warning_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_warning_location_reject.c',
        note='diagnostics JSON should honor #line remap for #warning directive diagnostics',
        expected_codes=[3000],
        expected_line=888,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_warning_current_physical_line',
        source=PROBE_DIR / 'diagnostics/03__probe_line_directive_warning_current_physical_line.c',
        note='fixed baseline: diagnostics JSON now reports remapped line for #warning directive diagnostics',
        expected_codes=[3000],
        expected_line=888,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_pragma_stdc_location_reject',
        source=PROBE_DIR / 'diagnostics/03__probe_diagjson_line_directive_pragma_stdc_location_reject.c',
        note='diagnostics JSON should honor #line remap for #pragma STDC diagnostics',
        expected_codes=[3000],
        expected_line=444,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_pragma_stdc_current_physical_line',
        source=PROBE_DIR / 'diagnostics/03__probe_diagjson_line_directive_pragma_stdc_current_physical_line.c',
        note='fixed baseline: diagnostics JSON now reports remapped line for #pragma STDC diagnostics',
        expected_codes=[3000],
        expected_line=444,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_include_error_filename_current_physical',
        source=PROBE_DIR.parent / 'cases/03__line_directive_include_error_diagjson_filename_current_physical.c',
        note='current threshold: included-header #error diagnostics JSON should preserve remapped #line file presence and line',
        expected_codes=[3000],
        expected_line=615,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_include_warning_filename_current_physical',
        source=PROBE_DIR.parent / 'cases/03__line_directive_include_warning_diagjson_filename_current_physical.c',
        note='current threshold: included-header #warning diagnostics JSON should preserve remapped #line file presence and line',
        expected_codes=[3000],
        expected_line=616,
        expected_column=1,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_line_directive_include_pragma_stdc_filename_current_physical',
        source=PROBE_DIR.parent / 'cases/03__line_directive_include_pragma_stdc_diagjson_filename_current_physical.c',
        note='current threshold: included-header #pragma STDC diagnostics JSON should preserve remapped #line file presence and line',
        expected_codes=[3000],
        expected_line=617,
        expected_column=9,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_macro_callsite_line_remap_arity_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_callsite_line_remap_arity_strict.c',
        note='strict macro provenance: diagnostics JSON should preserve #line-remapped macro call-site arity location',
        expected_codes=[3000],
        expected_line=312,
        expected_column=39,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_macro_include_reentry_arity_bridge_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_include_reentry_arity_bridge.c',
        note='strict macro provenance: diagnostics JSON should preserve #line-remapped include-reentry arity location',
        expected_codes=[3000],
        expected_line=430,
        expected_column=42,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_macro_gnu_comma_line_remap_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_gnu_comma_line_remap_current.c',
        note='strict macro provenance: diagnostics JSON should preserve #line-remapped GNU comma vaargs call-site location',
        expected_codes=[3000],
        expected_line=531,
        expected_column=34,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_macro_token_paste_line_remap_current',
        source=PROBE_DIR / 'diagnostics/03__probe_macro_token_paste_line_remap_current.c',
        note='current threshold: diagnostics JSON should at least preserve #line-remapped token-paste failure location',
        expected_codes=[1],
        expected_line=641,
        expected_column=50,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_wave31_include_line_tokenpaste_diag_current',
        source=PROBE_DIR / 'diagnostics/03__probe_wave31_include_line_tokenpaste_diag.c',
        note='current threshold: include-wrapped token-paste failure should export diagnostics JSON even though virtual provenance is not preserved for the paste failure',
        expected_codes=[3000],
        expected_line=0,
        expected_column=0,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_wave31_diagjson_text_parity_stringize_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_wave31_diagjson_text_parity_stringize.c',
        note='strict wave31 macro provenance: diagnostics JSON should match text location for the #line-remapped arity failure',
        expected_codes=[3000],
        expected_line=1331,
        expected_column=41,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='03__probe_diagjson_wave32_include_guard_macro_arity_strict',
        source=PROBE_DIR / 'diagnostics/03__probe_wave32_include_guard_macro_arity_diag.c',
        note='strict wave32 macro provenance: diagnostics JSON should preserve #line-remapped guarded include arity location',
        expected_codes=[3000],
        expected_line=2041,
        expected_column=30,
        expected_has_file=True,
    ),
]
