from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent

RUNTIME_PROBES = [
    RuntimeProbe(
        probe_id='08__probe_runtime_designated_override_zero_fill',
        source=PROBE_DIR / 'runtime/08__probe_runtime_designated_override_zero_fill.c',
        note='designated initializer override order and implicit zero-fill should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_brace_elision_matrix',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_brace_elision_matrix.c',
        note='nested aggregate brace elision should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_union_designator_selection',
        source=PROBE_DIR / 'runtime/08__probe_runtime_union_designator_selection.c',
        note='union designated-member selection inside aggregate initializers should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_sparse_designator_checksum_grid',
        source=PROBE_DIR / 'runtime/08__probe_runtime_sparse_designator_checksum_grid.c',
        note='sparse array designated initializers and implicit zero-fill should match clang runtime behavior',
    ),
    RuntimeProbe(
        probe_id='08__probe_runtime_nested_designator_override_chain',
        source=PROBE_DIR / 'runtime/08__probe_runtime_nested_designator_override_chain.c',
        note='nested designated initializer override chains should match clang runtime behavior',
    ),
]

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='08__probe_designator_unknown_field_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_designator_unknown_field_reject.c',
        note='designated initializer should reject unknown field names',
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_designator_array_nonconst_probe_diag_text.c:4802:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_designator_array_negative_probe_diag_text.c:4901:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: include-header non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_designator_array_nonconst_probe_diag_text.h:5002:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: include-header non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: include-header negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_designator_array_negative_probe_diag_text.h:5101:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: include-header negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: nested non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_nested_designator_array_nonconst_probe_diag_text.c:6402:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: nested non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c',
        note='strict frontier: include-header nested non-const designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_nested_designator_array_nonconst_probe_diag_text.h:6502:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c',
        note='reduced threshold: include-header nested non-const designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index must be a constant expression'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_nonconst_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: nested negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_nested_designator_array_negative_probe_diag_text.c:6601:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_nested_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: nested negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c',
        note='strict frontier: include-header nested negative designator-index text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_nested_designator_array_negative_probe_diag_text.h:6701:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c',
        note='reduced threshold: include-header nested negative designator-index text diagnostics should emit semantic rejection message',
        required_substrings=['designator index -1 is negative'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_nested_designator_array_index_negative_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_flex_not_last_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_flex_not_last_spelling_strict.c',
        note='strict frontier: flex-not-last text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_flex_not_last_probe_diag_text.c:5902:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_flex_not_last_spelling_strict.c',
        note='reduced threshold: flex-not-last text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array member must be the last field in a struct'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_flex_not_last_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c',
        note='strict frontier: include-header flex-not-last text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_flex_not_last_probe_diag_text.h:6002:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c',
        note='reduced threshold: include-header flex-not-last text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array member must be the last field in a struct'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_flex_not_last_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_union_flex_member_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_union_flex_member_spelling_strict.c',
        note='strict frontier: union flexible-member text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_union_flex_member_probe_diag_text.c:6102:'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_union_flex_member_spelling_strict.c',
        note='reduced threshold: union flexible-member text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array members are not allowed in unions'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_union_flex_member_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c',
        note='strict frontier: include-header union flexible-member text diagnostics under #line remap should preserve spelling file/line',
        required_substrings=['Spelling: virtual_init_include_union_flex_member_probe_diag_text.h:6202:'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c',
        note='reduced threshold: include-header union flexible-member text diagnostics should emit semantic rejection message',
        required_substrings=['Flexible array members are not allowed in unions'],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.c', PROBE_DIR / 'diagnostics/08__probe_diag_line_directive_include_union_flex_member_spelling_strict.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_unknown_field_rich_presence.c',
        note='strict frontier: designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3006:39): Unknown field 'missing' in designated initializer for 'value'",
            'Spelling: virtual_init_designator_unknown_field_probe.c:3006:39',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_oob_rich_presence.c',
        note='strict frontier: designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3101:16): Array 'arr' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_designator_array_oob_probe.c:3101:16',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3406:39): Unknown field 'missing' in designated initializer for 'value'",
            'Spelling: virtual_init_include_designator_unknown_field_probe.h:3406:39',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_oob_rich_presence.c',
        note='strict frontier: include-header designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (3501:16): Array 'arr' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_include_designator_array_oob_probe.h:3501:16',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_oob_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_oob_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: nested designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4006:20): Unknown field 'missing' in designated initializer for 'g'",
            'Spelling: virtual_init_nested_designator_unknown_field_probe.c:4006:20',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_nested_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: nested designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4103:10): Array 'grid' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_nested_designator_array_oob_probe.c:4103:10',
        ],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_unknown_field_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header nested designator unknown-field text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4206:20): Unknown field 'missing' in designated initializer for 'g'",
            'Spelling: virtual_init_include_nested_designator_unknown_field_probe.h:4206:20',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_line_directive_include_nested_designator_array_index_oob_spelling_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: include-header nested designator array-index-oob text diagnostics under #line remap should preserve error line and spelling file/line',
        required_substrings=[
            "Error at (4303:10): Array 'grid' designator index 3 is out of bounds (size 2)",
            'Spelling: virtual_init_include_nested_designator_array_oob_probe.h:4303:10',
        ],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_designated_nonconst_reject.c',
        note='file-scope designated initializer should reject non-constant field expressions',
        required_substrings=["Initializer for static variable 'g' is not a constant expression"],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_include_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c',
        note='include-header file-scope designated initializer should reject non-constant field expressions',
        required_substrings=["Initializer for static variable 'g' is not a constant expression"],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.h'],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_nested_designated_nonconst_reject.c',
        note='file-scope nested designated initializer should reject non-constant aggregate field expressions',
        required_substrings=["Initializer for static variable 'state' is not a constant expression"],
    ),
    DiagnosticProbe(
        probe_id='08__probe_diag_file_scope_include_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c',
        note='include-header file-scope nested designated initializer should reject non-constant aggregate field expressions',
        required_substrings=["Initializer for static variable 'state' is not a constant expression"],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.h'],
    ),
]

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_unknown_field_rich_presence.c',
        note='strict frontier: designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3006,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_unknown_field_rich_presence.c',
        note='reduced threshold: designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_oob_rich_presence.c',
        note='strict frontier: designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3101,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_oob_rich_presence.c',
        note='reduced threshold: designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3406,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_unknown_field_rich_presence.c',
        note='reduced threshold: include-header designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_oob_rich_presence.c',
        note='strict frontier: include-header designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=3501,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_oob_rich_presence.c',
        note='reduced threshold: include-header designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: nested designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4006,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_unknown_field_rich_presence.c',
        note='reduced threshold: nested designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: nested designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4103,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_oob_rich_presence.c',
        note='reduced threshold: nested designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_unknown_field_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c',
        note='strict frontier: include-header nested designator unknown-field diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4206,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_unknown_field_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_unknown_field_rich_presence.c',
        note='reduced threshold: include-header nested designator unknown-field diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_oob_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c',
        note='strict frontier: include-header nested designator array-index-oob diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4303,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_oob_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_oob_rich_presence.c',
        note='reduced threshold: include-header nested designator array-index-oob diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_negative_rich_presence.c',
        note='strict frontier: negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4501,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: include-header non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4602,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: include-header non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c',
        note='strict frontier: include-header negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=4701,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: include-header negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: nested non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6402,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: nested non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c',
        note='strict frontier: include-header nested non-const designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6502,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c',
        note='reduced threshold: include-header nested non-const designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_nonconst_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_negative_rich_presence.c',
        note='strict frontier: nested negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6602,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_nested_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: nested negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c',
        note='strict frontier: include-header nested negative designator-index diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=6702,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c',
        note='reduced threshold: include-header nested negative designator-index diagnostics JSON under #line remap emits initializer diagnostic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_nested_designator_array_index_negative_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_flex_not_last_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_flex_not_last_rich_presence.c',
        note='strict frontier: flex-not-last diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5502,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_flex_not_last_rich_presence.c',
        note='reduced threshold: flex-not-last diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_flex_not_last_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c',
        note='strict frontier: include-header flex-not-last diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5602,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_flex_not_last_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c',
        note='reduced threshold: include-header flex-not-last diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_flex_not_last_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_union_flex_member_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_union_flex_member_rich_presence.c',
        note='strict frontier: union flexible-member diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5702,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_union_flex_member_rich_presence.c',
        note='reduced threshold: union flexible-member diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_union_flex_member_file_presence_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c',
        note='strict frontier: include-header union flexible-member diagnostics JSON under #line remap should include file presence',
        expected_codes=[2000],
        expected_line=5802,
        expected_has_file=True,
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_line_directive_include_union_flex_member_current_sparse_pass',
        source=PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c',
        note='reduced threshold: include-header union flexible-member diagnostics JSON currently emits sparse semantic payload',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.c', PROBE_DIR / 'diagnostics/08__probe_diagjson_line_directive_include_union_flex_member_rich_presence.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_designated_nonconst_reject.c',
        note='diagnostics JSON should include file-scope designated non-constant initializer rejection',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_include_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c',
        note='diagnostics JSON should include include-header file-scope designated non-constant initializer rejection',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_designated_nonconst_reject.h'],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_nested_designated_nonconst_reject.c',
        note='diagnostics JSON should include file-scope nested designated non-constant initializer rejection',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='08__probe_diagjson_file_scope_include_nested_designated_nonconst_reject',
        source=PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c',
        note='diagnostics JSON should include include-header file-scope nested designated non-constant initializer rejection',
        expected_codes=[2000],
        inputs=[PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.c', PROBE_DIR / 'diagnostics/08__probe_diag_file_scope_include_nested_designated_nonconst_reject.h'],
    ),
]
