#ifndef COMPILER_PREPROCESS_MODE_H
#define COMPILER_PREPROCESS_MODE_H

typedef enum {
    PREPROCESS_INTERNAL = 0,
    PREPROCESS_EXTERNAL = 1,
    PREPROCESS_HYBRID = 2
} PreprocessMode;

#endif /* COMPILER_PREPROCESS_MODE_H */
