from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent.parent

RUNTIME_PROBES = []

DIAG_PROBES = [
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_unterminated_string_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_unterminated_string_no_crash.c',
        note='malformed unterminated-string input should fail closed without crashing',
        required_substrings=['Unterminated string literal'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_bad_escape_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_bad_escape_no_crash.c',
        note='malformed bad-escape input should fail closed without crashing',
        required_substrings=['Invalid escape in string literal'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_directive_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_directive_no_crash.c',
        note='malformed preprocessor directive should fail closed without crashing',
        required_substrings=['invalid parameter list in #define'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_unterminated_if_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_unterminated_if_chain_no_crash.c',
        note='malformed unterminated #if/#elif chain should fail closed without crashing',
        required_substrings=['unclosed #if/#ifdef/#ifndef'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_macro_paste_fragments_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_macro_paste_fragments_no_crash.c',
        note='malformed macro-paste fragments should fail closed without crashing',
        required_substrings=["GNU ', ##__VA_ARGS__' extension is not supported"],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_pp_macro_paste_variadic_comma_extension_no_diag',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_macro_paste_fragments_no_crash.c',
        note="GNU-style ', ##__VA_ARGS__' macro-paste extension should fail closed with preprocessing diagnostics",
        required_substrings=["GNU ', ##__VA_ARGS__' extension is not supported"],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_macro_paste_operator_tail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_macro_paste_operator_tail_no_crash.c',
        note='operator-tail token-paste malformed lane should fail closed with preprocessing diagnostics',
        required_substrings=['macro expansion failed (possible recursion)'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_gnu_comma_vaargs_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_gnu_comma_vaargs_chain_no_crash.c',
        note='GNU comma-vaargs nested chain should fail closed with preprocessing diagnostics',
        required_substrings=["GNU ', ##__VA_ARGS__' extension is not supported"],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_token_paste_variadic_tail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_token_paste_variadic_tail_no_crash.c',
        note='variadic token-paste tail lane should fail closed with preprocessing diagnostics',
        required_substrings=['macro expansion failed (possible recursion)'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_nested_ifdef_chain_seeded_d_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_nested_ifdef_chain_seeded_d_no_crash.c',
        note='malformed nested #if/#elif chain should fail closed without crashing',
        required_substrings=['unclosed #if/#ifdef/#ifndef'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_pp_include_cycle_guarded_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_include_cycle_guarded_no_crash.c',
        note='recursive self-include should fail closed with deterministic preprocessing diagnostic',
        required_substrings=['detected recursive include of'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_multifile_header_tail_garbage_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_multifile_header_tail_garbage_no_crash.c',
        note='malformed multi-file include with header-tail garbage should fail closed without crashing',
        required_substrings=['Invalid character in source'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_multifile_macro_arity_mismatch_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_multifile_macro_arity_mismatch_no_crash.c',
        note='malformed multi-file macro arity mismatch should fail closed without crashing',
        required_substrings=['requires 2 argument(s), got 1'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_header_guard_tail_mismatch_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_header_guard_tail_mismatch_no_crash.c',
        note='malformed header include-guard mismatch recursion should fail closed without crashing',
        required_substrings=['detected recursive include of'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_header_macro_cycle_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_header_macro_cycle_chain_no_crash.c',
        note='malformed header cycle + macro-arity chain should fail closed without crashing',
        required_substrings=['requires 2 argument(s), got 1'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_header_guard_tail_mismatch_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_header_guard_tail_mismatch_chain_no_crash.c',
        note='malformed header guard-tail mismatch chain recursion should fail closed without crashing',
        required_substrings=['detected recursive include of'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_include_graph_guard_collision_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_include_graph_guard_collision_no_crash.c',
        note='malformed include-graph guard collision should fail closed with deterministic diagnostics',
        required_substrings=['Undeclared identifier'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_multitu_duplicate_symbol_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_symbol_reject_main.c',
        note='multi-TU duplicate external symbol definitions should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_symbol_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_symbol_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject_main.c',
        note='axis1 wave1: multi-TU duplicate data definitions should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject_main.c',
        note='axis1 wave2: multi-TU duplicate weak/strong conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c',
        note='axis1 wave3: multi-TU duplicate tentative-definition matrix should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_current_no_diag',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c',
        note='axis1 wave3 current-threshold: duplicate tentative-definition matrix now emits deterministic duplicate-symbol diagnostics',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject_main.c',
        note='axis1 wave4: multi-TU function-vs-data same-name symbol conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject_main.c',
        note='axis1 wave5: multi-TU duplicate initialized globals should fail at link stage (always-hard lane)',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current_main.c',
        note='axis1 wave5 current-threshold: duplicate tentative split lane now emits deterministic duplicate-symbol diagnostics',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_main.c',
        note='axis1 wave6: multi-TU function-vs-object alias partition conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_main.c',
        note='axis1 wave7: mixed function-vs-object alias collisions across three TU partitions should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_main.c',
        note='axis1 wave8: dual mixed function-vs-object alias permutations should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_main.c',
        note='axis1 wave9: mixed function-vs-object alias ring conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_main.c',
        note='axis1 wave10: mixed function-vs-object alias checkpoint conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_main.c',
        note='axis1 wave11: mixed function-vs-object alias pointer-table rebase conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_main.c',
        note='axis1 wave12: mixed function-vs-object alias link-order checkpoint conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_main.c',
        note='axis1 wave13: mixed function-vs-object alias four-level checkpoint conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_main.c',
        note='axis1 wave14: mixed function-vs-object alias relocation-order conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_main.c',
        note='axis1 wave15: mixed function-vs-object alias three-plan replay conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_aux.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis2_wave1_line_map_nested_include_macro_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave1_line_map_nested_include_macro_chain_reject.c',
        note='axis2 wave1: #line remap through nested include+macro chain should preserve virtual spelling location',
        required_substrings=['axis2_wave1_nested_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis2_wave2_line_map_nested_include_macro_function_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave2_line_map_nested_include_macro_function_chain_reject.c',
        note='axis2 wave2: #line remap through nested include+macro function chain should preserve deep virtual spelling location',
        required_substrings=['axis2_wave2_nested_layer_c.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis2_wave3_line_map_nested_include_macro_arity_bridge_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave3_line_map_nested_include_macro_arity_bridge_reject.c',
        note='axis2 wave3: #line remap through four-layer include+macro arity bridge should preserve deep virtual spelling location',
        required_substrings=['axis2_wave3_nested_layer_d.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis2_wave4_line_map_nested_include_macro_token_bridge_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave4_line_map_nested_include_macro_token_bridge_reject.c',
        note='axis2 wave4: #line remap through token-paste include+macro bridge should preserve deep virtual spelling location',
        required_substrings=['axis2_wave4_token_layer_d.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave1_malformed_include_guard_reentry_depth_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave1_malformed_include_guard_reentry_depth_no_crash.c',
        note='axis4 wave1: deep include-guard reentry chain should fail closed and preserve deep virtual #line location',
        required_substrings=['axis4_wave1_guard_depth_layer_e.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave1_malformed_include_graph_mixed_arity_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave1_malformed_include_graph_mixed_arity_reentry_no_crash.c',
        note='axis4 wave1: include-graph macro reentry with arity drift should fail closed with deterministic preprocessing diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave1_mixed_arity_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave2_malformed_include_guard_cycle_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave2_malformed_include_guard_cycle_reentry_no_crash.c',
        note='axis4 wave2: include-guard contradiction cycle should fail closed with deterministic recursive-include diagnostics',
        required_substrings=['detected recursive include of'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave2_malformed_include_macro_arity_flip_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave2_malformed_include_macro_arity_flip_reentry_no_crash.c',
        note='axis4 wave2: include-graph macro reentry should deterministically surface arity drift diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave2_arity_flip_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave3_malformed_include_gnu_comma_vaargs_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave3_malformed_include_gnu_comma_vaargs_reentry_no_crash.c',
        note='axis4 wave3: include-graph variadic macro reentry should fail closed on GNU comma-paste extension usage',
        required_substrings=["GNU ', ##__VA_ARGS__' extension is not supported"],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave3_malformed_include_token_paste_tail_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave3_malformed_include_token_paste_tail_reentry_no_crash.c',
        note='axis4 wave3: include-graph token-paste tail lane should fail closed with deterministic expansion diagnostics',
        required_substrings=['macro expansion failed (possible recursion)'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave4_line_map_deep_missing_symbol_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave4_line_map_deep_missing_symbol_reentry_no_crash.c',
        note='axis4 wave4: deep include reentry line-map lane should preserve virtual spelling location for semantic failures',
        required_substrings=['axis4_wave4_depth_layer_e.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave4_line_map_deep_arity_bridge_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave4_line_map_deep_arity_bridge_reentry_no_crash.c',
        note='axis4 wave4: deep include reentry arity-bridge lane should fail closed with deterministic preprocessing diagnostics',
        required_substrings=['requires 5 argument(s), got 4', 'axis4_wave4_arity_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave5_conditional_dead_branch_skip_reentry_no_diag',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave5_conditional_dead_branch_skip_reentry_no_diag.c',
        note='axis4 wave5: malformed tokens hidden behind dead include-branch conditionals should be skipped without diagnostics',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave5_conditional_active_branch_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave5_conditional_active_branch_arity_fail_no_crash.c',
        note='axis4 wave5: active include-branch macro reentry should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave5_active_branch_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave6_guard_namespace_collision_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave6_guard_namespace_collision_reentry_no_crash.c',
        note='axis4 wave6: shared include-guard namespace collisions should fail closed on missing active-path symbol surfaces',
        required_substrings=['axis4_wave6_guard_collision_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave6_macro_state_undef_rebind_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave6_macro_state_undef_rebind_reentry_no_crash.c',
        note='axis4 wave6: cross-header #undef/#define macro-state churn should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave6_state_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave7_include_order_permute_a_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave7_include_order_permute_a_arity_fail_no_crash.c',
        note='axis4 wave7: include-order permutation A should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave7_perm_a_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave7_include_order_permute_b_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave7_include_order_permute_b_arity_fail_no_crash.c',
        note='axis4 wave7: include-order permutation B should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave7_perm_b_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave8_depth_conditional_dead_branch_matrix_no_diag',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave8_depth_conditional_dead_branch_matrix_no_diag.c',
        note='axis4 wave8: depth-amplified dead-branch conditional matrix should skip malformed lanes without diagnostics',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave8_depth_conditional_active_branch_matrix_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave8_depth_conditional_active_branch_matrix_fail_no_crash.c',
        note='axis4 wave8: depth-amplified active-branch conditional matrix should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave8_active_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave9_macro_alias_permute_a_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave9_macro_alias_permute_a_arity_fail_no_crash.c',
        note='axis4 wave9: macro-alias rename permutation A should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave9_perm_a_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave9_macro_alias_permute_b_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave9_macro_alias_permute_b_arity_fail_no_crash.c',
        note='axis4 wave9: macro-alias rename permutation B should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave9_perm_b_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave10_branch_convergence_inactive_path_no_diag',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave10_branch_convergence_inactive_path_no_diag.c',
        note='axis4 wave10: inactive branch-convergence path should keep winner-only malformed surface suppressed without diagnostics',
        expect_any_diagnostic=False,
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave10_branch_convergence_winner_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave10_branch_convergence_winner_arity_fail_no_crash.c',
        note='axis4 wave10: converged macro-state winner should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave10_winner_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave11_dual_convergence_order_a_winner_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave11_dual_convergence_order_a_winner_arity_fail_no_crash.c',
        note='axis4 wave11: dual convergence order-A winner should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave11_order_a_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_axis4_wave11_dual_convergence_order_b_winner_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave11_dual_convergence_order_b_winner_arity_fail_no_crash.c',
        note='axis4 wave11: dual convergence order-B winner should fail closed with deterministic arity diagnostics',
        required_substrings=['requires 3 argument(s), got 2', 'axis4_wave11_order_b_layer_a.h'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_corpus_external_compile_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_external_compile_reject.c',
        note='external-corpus fragment with malformed typedef tail should fail closed with parser diagnostic',
        required_substrings=['Expected identifier in declarator'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_corpus_external_macro_guard_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_external_macro_guard_reject.c',
        note='external-corpus malformed macro-guard fragment should fail closed in preprocessing',
        required_substrings=['invalid parameter list in #define'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_corpus_external_macro_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_external_macro_chain_reject.c',
        note='external-corpus malformed macro-chain fragment should fail closed in preprocessing',
        required_substrings=['invalid parameter list in #define'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_corpus_external_include_guard_mismatch_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_external_include_guard_mismatch_reject.c',
        note='external-corpus include-guard mismatch should fail closed via recursive-include detection',
        required_substrings=['detected recursive include of'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_corpus_pinned_macro_include_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_pinned_macro_include_chain_reject.c',
        note='pinned corpus macro include-chain fragment should fail closed in preprocessing',
        required_substrings=['invalid parameter list in #define'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_corpus_pinned_typedef_decl_cycle_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_pinned_typedef_decl_cycle_reject.c',
        note='pinned corpus typedef-decl cycle fragment should fail closed with parser diagnostic',
        required_substrings=['Expected identifier in declarator'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_pathological_initializer_shape_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_pathological_initializer_shape_reject.c',
        note='pathological designated-initializer shape should fail closed with deterministic diagnostics',
        required_substrings=["Expected expression after '=' in struct initializer"],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_pathological_initializer_rewrite_surface_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_pathological_initializer_rewrite_surface_reject.c',
        note='pathological initializer rewrite surface lane should fail closed with deterministic diagnostics',
        required_substrings=["Expected expression after '=' in struct initializer"],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_pathological_switch_case_surface_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_pathological_switch_case_surface_reject.c',
        note='pathological switch case surface lane should reject non-constant case labels',
        required_substrings=['Case label is not an integer constant expression'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_token_stream_seeded_a_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_token_stream_seeded_a_no_crash.c',
        note='seeded malformed token-stream A should fail closed without crashing',
        required_substrings=['Unexpected token at start of expression'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_token_stream_seeded_b_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_token_stream_seeded_b_no_crash.c',
        note='seeded malformed token-stream B should fail closed without crashing',
        required_substrings=['Unexpected token at start of expression'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_token_stream_seeded_c_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_token_stream_seeded_c_no_crash.c',
        note='seeded malformed token-stream C should fail closed without crashing',
        required_substrings=['Unexpected token at start of expression'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_fuzz_seeded_malformed_volume_replay_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_fuzz_seeded_malformed_volume_replay_no_crash.c',
        note='seeded malformed fuzz-volume replay lane should fail closed without crashing',
        required_substrings=['Unexpected token at start of expression'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_multitu_duplicate_function_definition_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_function_definition_reject_main.c',
        note='multi-TU duplicate function definitions should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_function_definition_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_function_definition_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_multitu_symbol_type_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_multitu_symbol_type_conflict_reject_main.c',
        note='multi-TU duplicate global symbols with type conflict should fail at link stage',
        required_substrings=['duplicate symbol'],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_multitu_symbol_type_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_multitu_symbol_type_conflict_reject_lib.c'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_invalid_dollar_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_invalid_dollar_no_crash.c',
        note='malformed invalid-dollar token stream should fail closed without crashing',
        required_substrings=['Invalid character in source'],
    ),
    DiagnosticProbe(
        probe_id='15__probe_diag_malformed_char_invalid_hex_escape_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_char_invalid_hex_escape_no_crash.c',
        note='malformed invalid hex escape in character literal should fail closed without crashing',
        required_substrings=['Invalid \\x escape in character literal'],
    ),
]

DIAG_JSON_PROBES = []
