from pathlib import Path

from lib.models import DiagnosticJsonProbe, DiagnosticProbe, RuntimeProbe


PROBE_DIR = Path(__file__).resolve().parent.parent.parent

RUNTIME_PROBES = []

DIAG_PROBES = []

DIAG_JSON_PROBES = [
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_unbalanced_block_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diagjson_malformed_unbalanced_block_no_crash.c',
        note='diagnostics JSON should be emitted for malformed unbalanced-block torture lane',
        expected_codes=[2000],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_unclosed_comment_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diagjson_malformed_unclosed_comment_no_crash.c',
        note='diagnostics JSON should be emitted for malformed unclosed-comment torture lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_multitu_duplicate_symbol_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_symbol_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU duplicate-symbol link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_symbol_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_symbol_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave1_multitu_duplicate_definition_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject_main.c',
        note='axis1 wave1: diagnostics JSON should be exported for multi-TU duplicate data-definition link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave1_multitu_duplicate_definition_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject_main.c',
        note='axis1 wave2: diagnostics JSON should be exported for multi-TU duplicate weak/strong conflict link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave2_multitu_duplicate_weak_strong_conflict_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave3_multitu_duplicate_tentative_matrix_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c',
        note='axis1 wave3: diagnostics JSON should be exported for multi-TU duplicate tentative-definition link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave3_multitu_duplicate_tentative_matrix_current_empty',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c',
        note='axis1 wave3 current-threshold: diagnostics JSON export may be empty for duplicate tentative-definition matrix under current defaults',
        require_any_diagnostic=False,
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave3_multitu_duplicate_tentative_matrix_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave4_multitu_function_data_symbol_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject_main.c',
        note='axis1 wave4: diagnostics JSON should be exported for multi-TU function-vs-data symbol conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave4_multitu_function_data_symbol_conflict_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave5_multitu_duplicate_initialized_global_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject_main.c',
        note='axis1 wave5: diagnostics JSON should be exported for duplicate initialized-global link conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_initialized_global_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave5_multitu_duplicate_tentative_split_current',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current_main.c',
        note='axis1 wave5 current-threshold: diagnostics JSON may be empty for duplicate tentative split lane under current defaults',
        require_any_diagnostic=False,
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave5_multitu_duplicate_tentative_split_current_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave6_multitu_function_object_alias_partition_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_main.c',
        note='axis1 wave6: diagnostics JSON should be exported for function-vs-object alias partition link conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave6_multitu_function_object_alias_partition_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave7_multitu_function_object_alias_perm_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_main.c',
        note='axis1 wave7: diagnostics JSON should be exported for mixed function-vs-object alias permutation link conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave7_multitu_function_object_alias_perm_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_main.c',
        note='axis1 wave8: diagnostics JSON should be exported for dual mixed function-vs-object alias permutation link conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave8_multitu_dual_function_object_alias_perm_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave9_multitu_function_object_alias_ring_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_main.c',
        note='axis1 wave9: diagnostics JSON should be exported for mixed function-vs-object alias ring conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave9_multitu_function_object_alias_ring_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_main.c',
        note='axis1 wave10: diagnostics JSON should be exported for mixed function-vs-object alias checkpoint conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave10_multitu_function_object_alias_checkpoint_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_main.c',
        note='axis1 wave11: diagnostics JSON should be exported for mixed function-vs-object alias pointer-table rebase conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave11_multitu_function_object_alias_ptrtable_rebase_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_main.c',
        note='axis1 wave12: diagnostics JSON should be exported for mixed function-vs-object alias link-order checkpoint conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave12_multitu_function_object_alias_linkorder_checkpoint_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_main.c',
        note='axis1 wave13: diagnostics JSON should be exported for mixed function-vs-object alias four-level checkpoint conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave13_multitu_function_object_alias_four_level_checkpoint_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_main.c',
        note='axis1 wave14: diagnostics JSON should be exported for mixed function-vs-object alias relocation-order conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave14_multitu_function_object_alias_relocation_order_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_main.c',
        note='axis1 wave15: diagnostics JSON should be exported for mixed function-vs-object alias three-plan replay conflicts',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_lib.c', PROBE_DIR / 'diagnostics/15__probe_diag_axis1_wave15_multitu_function_object_alias_three_plan_replay_conflict_reject_aux.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis2_wave1_line_map_nested_include_macro_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave1_line_map_nested_include_macro_chain_reject.c',
        note='axis2 wave1: diagnostics JSON should preserve line/file presence for nested include+macro #line remap lane',
        expected_codes=[2000],
        expected_line=300299,
        expected_column=33,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis2_wave2_line_map_nested_include_macro_function_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave2_line_map_nested_include_macro_function_chain_reject.c',
        note='axis2 wave2: diagnostics JSON should preserve deep line/file presence for nested include+macro function-chain #line remap lane',
        expected_codes=[2000],
        expected_line=340304,
        expected_column=12,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis2_wave3_line_map_nested_include_macro_arity_bridge_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave3_line_map_nested_include_macro_arity_bridge_reject.c',
        note='axis2 wave3: diagnostics JSON should preserve deep line/file presence for four-layer include+macro arity-bridge #line remap lane',
        expected_codes=[2000],
        expected_line=260697,
        expected_column=38,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis2_wave4_line_map_nested_include_macro_token_bridge_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis2_wave4_line_map_nested_include_macro_token_bridge_reject.c',
        note='axis2 wave4: diagnostics JSON should preserve deep line/file presence for token-paste include+macro bridge #line remap lane',
        expected_codes=[2000],
        expected_line=340798,
        expected_column=34,
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave1_malformed_include_guard_reentry_depth_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave1_malformed_include_guard_reentry_depth_no_crash.c',
        note='axis4 wave1: diagnostics JSON should preserve deep line/file presence for include-guard reentry depth lane',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave2_malformed_include_guard_cycle_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave2_malformed_include_guard_cycle_reentry_no_crash.c',
        note='axis4 wave2: diagnostics JSON should preserve file-presence fields for include-guard contradiction cycle diagnostics',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave3_malformed_include_gnu_comma_vaargs_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave3_malformed_include_gnu_comma_vaargs_reentry_no_crash.c',
        note='axis4 wave3: diagnostics JSON should preserve file-presence fields for include-graph GNU comma-paste rejection',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave4_line_map_deep_missing_symbol_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave4_line_map_deep_missing_symbol_reentry_no_crash.c',
        note='axis4 wave4: diagnostics JSON should preserve deep virtual file-presence for line-map semantic failure lanes',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave5_conditional_active_branch_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave5_conditional_active_branch_arity_fail_no_crash.c',
        note='axis4 wave5: diagnostics JSON should preserve file-presence fields for active-branch include reentry arity failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave6_macro_state_undef_rebind_reentry_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave6_macro_state_undef_rebind_reentry_no_crash.c',
        note='axis4 wave6: diagnostics JSON should preserve file-presence fields for macro-state churn include reentry failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave7_include_order_permute_b_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave7_include_order_permute_b_arity_fail_no_crash.c',
        note='axis4 wave7: diagnostics JSON should preserve file-presence fields across include-order permutation arity failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave8_depth_conditional_active_branch_matrix_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave8_depth_conditional_active_branch_matrix_fail_no_crash.c',
        note='axis4 wave8: diagnostics JSON should preserve file-presence fields for depth-amplified active-branch conditional failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave9_macro_alias_permute_b_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave9_macro_alias_permute_b_arity_fail_no_crash.c',
        note='axis4 wave9: diagnostics JSON should preserve file-presence fields across macro-alias permutation failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave10_branch_convergence_winner_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave10_branch_convergence_winner_arity_fail_no_crash.c',
        note='axis4 wave10: diagnostics JSON should preserve file-presence fields for converged macro-state winner failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_axis4_wave11_dual_convergence_order_b_winner_arity_fail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_axis4_wave11_dual_convergence_order_b_winner_arity_fail_no_crash.c',
        note='axis4 wave11: diagnostics JSON should preserve file-presence fields for dual convergence order-B winner failures',
        expected_has_file=True,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_pathological_initializer_shape_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_pathological_initializer_shape_reject.c',
        note='diagnostics JSON should be exported for pathological designated-initializer rejection',
        expected_codes=[2000],
        expected_line=15,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_corpus_pinned_macro_include_chain_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_pinned_macro_include_chain_reject.c',
        note='diagnostics JSON should be exported for pinned-corpus macro include-chain rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_corpus_pinned_typedef_decl_cycle_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_corpus_pinned_typedef_decl_cycle_reject.c',
        note='diagnostics JSON should be exported for pinned-corpus typedef-decl-cycle rejection',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_pathological_initializer_rewrite_surface_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_pathological_initializer_rewrite_surface_reject.c',
        note='diagnostics JSON should be exported for pathological initializer-rewrite surface rejection',
        expected_codes=[2000],
        expected_line=22,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_pathological_switch_case_surface_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_pathological_switch_case_surface_reject.c',
        note='diagnostics JSON should be exported for pathological non-constant switch-case surface rejection',
        expected_codes=[2000],
        expected_line=5,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_token_stream_seeded_a_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_token_stream_seeded_a_no_crash.c',
        note='diagnostics JSON should be exported for seeded malformed token-stream A',
        expected_codes=[1000],
        expected_line=3,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_token_stream_seeded_b_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_token_stream_seeded_b_no_crash.c',
        note='diagnostics JSON should be exported for seeded malformed token-stream B',
        expected_codes=[1000],
        expected_line=3,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_token_stream_seeded_c_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_token_stream_seeded_c_no_crash.c',
        note='diagnostics JSON should be exported for seeded malformed token-stream C',
        expected_codes=[1000],
        expected_line=3,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_fuzz_seeded_malformed_volume_replay_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_fuzz_seeded_malformed_volume_replay_no_crash.c',
        note='diagnostics JSON should be exported for seeded malformed fuzz-volume replay lane',
        expected_codes=[1000],
        expected_line=5,
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_multitu_duplicate_function_definition_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_function_definition_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU duplicate function definition link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_function_definition_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_multitu_duplicate_function_definition_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_multitu_symbol_type_conflict_reject',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_multitu_symbol_type_conflict_reject_main.c',
        note='diagnostics JSON should be exported for multi-TU duplicate symbol type-conflict link failures',
        expected_codes=[4001],
        inputs=[PROBE_DIR / 'diagnostics/15__probe_diag_multitu_symbol_type_conflict_reject_main.c', PROBE_DIR / 'diagnostics/15__probe_diag_multitu_symbol_type_conflict_reject_lib.c'],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_invalid_dollar_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_invalid_dollar_no_crash.c',
        note='diagnostics JSON should be exported for malformed invalid-dollar lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_char_invalid_hex_escape_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_char_invalid_hex_escape_no_crash.c',
        note='diagnostics JSON should be exported for malformed invalid-hex-escape char lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_unterminated_if_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_unterminated_if_chain_no_crash.c',
        note='diagnostics JSON should be exported for malformed unterminated #if/#elif chain lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_macro_paste_fragments_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_macro_paste_fragments_no_crash.c',
        note='diagnostics JSON should be exported for malformed macro-paste fragment lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_pp_macro_paste_variadic_comma_extension_no_diag',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_macro_paste_fragments_no_crash.c',
        note="GNU-style ', ##__VA_ARGS__' extension lane should export preprocessing diagnostics JSON",
        expected_codes=[3000],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_macro_paste_operator_tail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_macro_paste_operator_tail_no_crash.c',
        note='operator-tail token-paste malformed lane should export preprocessing diagnostics JSON',
        expected_codes=[3000],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_gnu_comma_vaargs_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_gnu_comma_vaargs_chain_no_crash.c',
        note='GNU comma-vaargs nested chain should export preprocessing diagnostics JSON',
        expected_codes=[3000],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_token_paste_variadic_tail_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_token_paste_variadic_tail_no_crash.c',
        note='variadic token-paste tail lane should export preprocessing diagnostics JSON',
        expected_codes=[3000],
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_nested_ifdef_chain_seeded_d_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_nested_ifdef_chain_seeded_d_no_crash.c',
        note='diagnostics JSON should be exported for malformed nested #if/#elif chain lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_pp_include_cycle_guarded_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_pp_include_cycle_guarded_no_crash.c',
        note='diagnostics JSON should be exported for recursive self-include malformed lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_multifile_header_tail_garbage_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_multifile_header_tail_garbage_no_crash.c',
        note='diagnostics JSON should be exported for malformed multi-file header-tail-garbage lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_multifile_macro_arity_mismatch_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_multifile_macro_arity_mismatch_no_crash.c',
        note='diagnostics JSON should be exported for malformed multi-file macro-arity-mismatch lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_header_guard_tail_mismatch_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_header_guard_tail_mismatch_no_crash.c',
        note='diagnostics JSON should be exported for malformed header guard-tail mismatch lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_header_macro_cycle_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_header_macro_cycle_chain_no_crash.c',
        note='diagnostics JSON should be exported for malformed header macro-cycle chain lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_header_guard_tail_mismatch_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_header_guard_tail_mismatch_chain_no_crash.c',
        note='diagnostics JSON should be exported for malformed header guard-tail mismatch chain lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_include_graph_guard_collision_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_include_graph_guard_collision_no_crash.c',
        note='diagnostics JSON should be exported for malformed include-graph guard-collision lane',
    ),
    DiagnosticJsonProbe(
        probe_id='15__probe_diagjson_malformed_include_graph_macro_arity_chain_no_crash',
        source=PROBE_DIR / 'diagnostics/15__probe_diag_malformed_include_graph_macro_arity_chain_no_crash.c',
        note='diagnostics JSON should be exported for malformed include-graph macro-arity chain lane',
    ),
]
