#ifndef CASE_MALFORMED_HEADER_GUARD_TAIL_MISMATCH_CHAIN_B_H
#define CASE_MALFORMED_HEADER_GUARD_TAIL_MISMATCH_CHAIN_B_H

#include "15__torture__malformed_header_guard_tail_mismatch_chain_no_crash_a.h"

#endif
