#ifndef FISICS_PROBE_RUNTIME_WAVE23_PASTED_FUNCTION_PROVENANCE_STRICT_H
#define FISICS_PROBE_RUNTIME_WAVE23_PASTED_FUNCTION_PROVENANCE_STRICT_H

#define PHASE01_W23_PROV_CAT_RAW(a, b) a##b
#define PHASE01_W23_PROV_CAT(a, b) PHASE01_W23_PROV_CAT_RAW(a, b)
#define PHASE01_W23_PROV_STR_RAW(x) #x
#define PHASE01_W23_PROV_STR(x) PHASE01_W23_PROV_STR_RAW(x)
#define PHASE01_W23_PROV_ROOT beta
#define PHASE01_W23_PROV_RECORD_beta(file, line) file ":" PHASE01_W23_PROV_STR(line)
#define PHASE01_W23_PROV_SELECT(name) PHASE01_W23_PROV_CAT(PHASE01_W23_PROV_RECORD_, name)
#define PHASE01_W23_PROV_CAPTURE(name, file, line) PHASE01_W23_PROV_SELECT(name)(file, line)

#endif
