#ifndef FISICS_PROBE_RUNTIME_WAVE38_GUARD_REOPEN_STATE_H
#define FISICS_PROBE_RUNTIME_WAVE38_GUARD_REOPEN_STATE_H

#define W38_REOPEN_CAT2(a, b) a##b
#define W38_REOPEN_CAT(a, b) W38_REOPEN_CAT2(a, b)
#define W38_REOPEN_DECL(slot, value) enum { W38_REOPEN_CAT(w38_reopen_, slot) = (value) + 5 }

W38_REOPEN_DECL(W38_REOPEN_SLOT, W38_REOPEN_VALUE);

#endif
