#ifndef FISICS_PROBE_04_WAVE19_INCLUDE_PARAM_VLA_STATIC_CONST_ADJUST_BRIDGE_SHARED_H
#define FISICS_PROBE_04_WAVE19_INCLUDE_PARAM_VLA_STATIC_CONST_ADJUST_BRIDGE_SHARED_H

int wave19_multitu_include_vla_static_const_fold(int rows, int cols, int matrix[const static rows][cols]);

#endif
