#ifndef FISICS_BUCKET10_WAVE60_TENTATIVE_EXTERN_ARRAY_COMPLETION_CURRENT_H
#define FISICS_BUCKET10_WAVE60_TENTATIVE_EXTERN_ARRAY_COMPLETION_CURRENT_H

extern int bucket10_wave60_current_cells[];

int bucket10_wave60_current_array_seed(int base);
int bucket10_wave60_current_array_fold(void);

#endif
