#ifndef FISICS_BUCKET10_WAVE59_EXTERN_ARRAY_STATIC_LOCAL_SHADOW_CURRENT_RUNTIME_H
#define FISICS_BUCKET10_WAVE59_EXTERN_ARRAY_STATIC_LOCAL_SHADOW_CURRENT_RUNTIME_H

extern int bucket10_wave59_current_lane[4];

int bucket10_wave59_current_lib_seed(int seed);
int bucket10_wave59_current_lib_fold(int step);
int bucket10_wave59_current_lib_total(void);

#endif
