typedef struct Axis6W4Snapshot { unsigned int shard, phase, watermark, lane_a, lane_b; } Axis6W4Snapshot;
typedef struct Axis6W4Aggregate { unsigned int phase[4], watermark[4], lane_a[4], lane_b[4]; } Axis6W4Aggregate;
static unsigned int mix4s(unsigned int h,unsigned int v){ h ^= v + 0x9e3779b9u + (h<<6) + (h>>2); return h; }
void axis6_w4_seed_snapshot(Axis6W4Snapshot* out,unsigned int shard,unsigned int phase,unsigned int watermark,unsigned int lane_a,unsigned int lane_b){ out->shard=shard%4u; out->phase=phase; out->watermark=watermark; out->lane_a=lane_a; out->lane_b=lane_b; }
void axis6_w4_encode_snapshot(const Axis6W4Snapshot* s,unsigned int wire[5]){ wire[0]=s->shard^0x21u; wire[1]=s->phase^0x43u; wire[2]=s->watermark^0x65u; wire[3]=s->lane_a^0x87u; wire[4]=s->lane_b^0xa9u; }
void axis6_w4_decode_snapshot(Axis6W4Snapshot* s,const unsigned int wire[5]){ s->shard=wire[0]^0x21u; s->phase=wire[1]^0x43u; s->watermark=wire[2]^0x65u; s->lane_a=wire[3]^0x87u; s->lane_b=wire[4]^0xa9u; }
void axis6_w4_clear_aggregate(Axis6W4Aggregate* a){ for(int shard=0; shard<4; ++shard){ a->phase[shard]=0u; a->watermark[shard]=0u; a->lane_a[shard]=0u; a->lane_b[shard]=0u; } }
void axis6_w4_absorb_snapshot(Axis6W4Aggregate* a,const Axis6W4Snapshot* s){ unsigned int shard=s->shard%4u; if(s->phase<a->phase[shard]) return; if(s->phase>a->phase[shard]){ a->phase[shard]=s->phase; a->watermark[shard]=s->watermark; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; return; } if(s->watermark>a->watermark[shard]){ a->watermark[shard]=s->watermark; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; } else if(s->watermark==a->watermark[shard]){ a->lane_a[shard]+=s->lane_a; a->lane_b[shard]+=s->lane_b; } }
unsigned int axis6_w4_snapshot_signature(const Axis6W4Aggregate* a){ unsigned int h=2166136261u; for(int shard=0; shard<4; ++shard){ h=mix4s(h,a->phase[shard]); h=mix4s(h,a->watermark[shard]); h=mix4s(h,a->lane_a[shard]); h=mix4s(h,a->lane_b[shard]); } return h; }
