typedef struct Axis6W6Snapshot { unsigned int shard, checkpoint, frontier, lane_a, lane_b; } Axis6W6Snapshot;
typedef struct Axis6W6Aggregate { unsigned int checkpoint[4], frontier[4], lane_a[4], lane_b[4]; } Axis6W6Aggregate;
static unsigned int mix6s(unsigned int h,unsigned int v){ h ^= v + 0x9e3779b9u + (h<<6)+(h>>2); return h; }
void axis6_w6_seed_snapshot(Axis6W6Snapshot* out,unsigned int shard,unsigned int checkpoint,unsigned int frontier,unsigned int lane_a,unsigned int lane_b){ out->shard=shard%4u; out->checkpoint=checkpoint; out->frontier=frontier; out->lane_a=lane_a; out->lane_b=lane_b; }
void axis6_w6_encode_snapshot(const Axis6W6Snapshot* s,unsigned int wire[5]){ wire[0]=s->shard^0x25u; wire[1]=s->checkpoint^0x47u; wire[2]=s->frontier^0x69u; wire[3]=s->lane_a^0x8bu; wire[4]=s->lane_b^0xadu; }
void axis6_w6_decode_snapshot(Axis6W6Snapshot* s,const unsigned int wire[5]){ s->shard=wire[0]^0x25u; s->checkpoint=wire[1]^0x47u; s->frontier=wire[2]^0x69u; s->lane_a=wire[3]^0x8bu; s->lane_b=wire[4]^0xadu; }
void axis6_w6_clear_aggregate(Axis6W6Aggregate* a){ for(int shard=0; shard<4; ++shard){ a->checkpoint[shard]=0u; a->frontier[shard]=0u; a->lane_a[shard]=0u; a->lane_b[shard]=0u; } }
void axis6_w6_absorb_snapshot(Axis6W6Aggregate* a,const Axis6W6Snapshot* s){ unsigned int shard=s->shard%4u; if(s->checkpoint<a->checkpoint[shard]) return; if(s->checkpoint>a->checkpoint[shard]){ a->checkpoint[shard]=s->checkpoint; a->frontier[shard]=s->frontier; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; return; } if(s->frontier>a->frontier[shard]){ a->frontier[shard]=s->frontier; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; } else if(s->frontier==a->frontier[shard]){ a->lane_a[shard]+=s->lane_a; a->lane_b[shard]+=s->lane_b; } }
unsigned int axis6_w6_snapshot_signature(const Axis6W6Aggregate* a){ unsigned int h=2166136261u; for(int shard=0; shard<4; ++shard){ h=mix6s(h,a->checkpoint[shard]); h=mix6s(h,a->frontier[shard]); h=mix6s(h,a->lane_a[shard]); h=mix6s(h,a->lane_b[shard]); } return h; }
