typedef struct Axis6W5Snapshot { unsigned int shard, checkpoint, shadow, lane_a, lane_b; } Axis6W5Snapshot;
typedef struct Axis6W5Aggregate { unsigned int checkpoint[4], shadow[4], lane_a[4], lane_b[4]; } Axis6W5Aggregate;
static unsigned int mix5s(unsigned int h,unsigned int v){ h ^= v + 0x9e3779b9u + (h<<6)+(h>>2); return h; }
void axis6_w5_seed_snapshot(Axis6W5Snapshot* out,unsigned int shard,unsigned int checkpoint,unsigned int shadow,unsigned int lane_a,unsigned int lane_b){ out->shard=shard%4u; out->checkpoint=checkpoint; out->shadow=shadow; out->lane_a=lane_a; out->lane_b=lane_b; }
void axis6_w5_encode_snapshot(const Axis6W5Snapshot* s,unsigned int wire[5]){ wire[0]=s->shard^0x23u; wire[1]=s->checkpoint^0x45u; wire[2]=s->shadow^0x67u; wire[3]=s->lane_a^0x89u; wire[4]=s->lane_b^0xabu; }
void axis6_w5_decode_snapshot(Axis6W5Snapshot* s,const unsigned int wire[5]){ s->shard=wire[0]^0x23u; s->checkpoint=wire[1]^0x45u; s->shadow=wire[2]^0x67u; s->lane_a=wire[3]^0x89u; s->lane_b=wire[4]^0xabu; }
void axis6_w5_clear_aggregate(Axis6W5Aggregate* a){ for(int shard=0; shard<4; ++shard){ a->checkpoint[shard]=0u; a->shadow[shard]=0u; a->lane_a[shard]=0u; a->lane_b[shard]=0u; } }
void axis6_w5_absorb_snapshot(Axis6W5Aggregate* a,const Axis6W5Snapshot* s){ unsigned int shard=s->shard%4u; if(s->checkpoint<a->checkpoint[shard]) return; if(s->checkpoint>a->checkpoint[shard]){ a->checkpoint[shard]=s->checkpoint; a->shadow[shard]=s->shadow; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; return; } if(s->shadow>a->shadow[shard]){ a->shadow[shard]=s->shadow; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; } else if(s->shadow==a->shadow[shard]){ a->lane_a[shard]+=s->lane_a; a->lane_b[shard]+=s->lane_b; } }
unsigned int axis6_w5_snapshot_signature(const Axis6W5Aggregate* a){ unsigned int h=2166136261u; for(int shard=0; shard<4; ++shard){ h=mix5s(h,a->checkpoint[shard]); h=mix5s(h,a->shadow[shard]); h=mix5s(h,a->lane_a[shard]); h=mix5s(h,a->lane_b[shard]); } return h; }
