typedef struct Axis6W7Snapshot { unsigned int shard, phase, checkpoint, lane_a, lane_b; } Axis6W7Snapshot;
typedef struct Axis6W7Aggregate { unsigned int phase[4], checkpoint[4], lane_a[4], lane_b[4]; } Axis6W7Aggregate;
static unsigned int mix7s(unsigned int h,unsigned int v){ h ^= v + 0x9e3779b9u + (h<<6) + (h>>2); return h; }
void axis6_w7_seed_snapshot(Axis6W7Snapshot* out,unsigned int shard,unsigned int phase,unsigned int checkpoint,unsigned int lane_a,unsigned int lane_b){ out->shard=shard%4u; out->phase=phase; out->checkpoint=checkpoint; out->lane_a=lane_a; out->lane_b=lane_b; }
void axis6_w7_encode_snapshot(const Axis6W7Snapshot* s,unsigned int wire[5]){ wire[0]=s->shard^0x35u; wire[1]=s->phase^0x57u; wire[2]=s->checkpoint^0x79u; wire[3]=s->lane_a^0x9bu; wire[4]=s->lane_b^0xbdu; }
void axis6_w7_decode_snapshot(Axis6W7Snapshot* s,const unsigned int wire[5]){ s->shard=wire[0]^0x35u; s->phase=wire[1]^0x57u; s->checkpoint=wire[2]^0x79u; s->lane_a=wire[3]^0x9bu; s->lane_b=wire[4]^0xbdu; }
void axis6_w7_clear_aggregate(Axis6W7Aggregate* a){ for(int shard=0; shard<4; ++shard){ a->phase[shard]=0u; a->checkpoint[shard]=0u; a->lane_a[shard]=0u; a->lane_b[shard]=0u; } }
void axis6_w7_absorb_snapshot(Axis6W7Aggregate* a,const Axis6W7Snapshot* s){ unsigned int shard=s->shard%4u; if(s->phase<a->phase[shard]) return; if(s->phase>a->phase[shard]){ a->phase[shard]=s->phase; a->checkpoint[shard]=s->checkpoint; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; return; } if(s->checkpoint>a->checkpoint[shard]){ a->checkpoint[shard]=s->checkpoint; a->lane_a[shard]=s->lane_a; a->lane_b[shard]=s->lane_b; } else if(s->checkpoint==a->checkpoint[shard]){ a->lane_a[shard]+=s->lane_a; a->lane_b[shard]+=s->lane_b; } }
unsigned int axis6_w7_snapshot_signature(const Axis6W7Aggregate* a){ unsigned int h=2166136261u; for(int shard=0; shard<4; ++shard){ h=mix7s(h,a->phase[shard]); h=mix7s(h,a->checkpoint[shard]); h=mix7s(h,a->lane_a[shard]); h=mix7s(h,a->lane_b[shard]); } return h; }
