#include <stdio.h>
typedef struct R { unsigned int shard, lane, checkpoint, watermark; int delta; } R;
typedef struct A { unsigned int checkpoint[5], watermark[5]; int value[5]; } A;
static unsigned int mix(unsigned int h,unsigned int v){ h ^= v + 0x9e3779b9u + (h<<6) + (h>>2); return h; }
static void clear(A* a){ for(int i=0;i<5;++i){ a->checkpoint[i]=0u; a->watermark[i]=0u; a->value[i]=0; } }
static void absorb(A* a,const R* r){ unsigned int lane=r->lane%5u; if(r->checkpoint<a->checkpoint[lane]) return; if(r->checkpoint>a->checkpoint[lane]){ a->checkpoint[lane]=r->checkpoint; a->watermark[lane]=r->watermark; a->value[lane]=r->delta; return; } if(r->watermark>a->watermark[lane]){ a->watermark[lane]=r->watermark; a->value[lane]=r->delta; } else if(r->watermark==a->watermark[lane]) a->value[lane]+=r->delta; }
static unsigned int sig(const A* a){ unsigned int h=2166136261u; for(unsigned int lane=0; lane<5u; ++lane){ h=mix(h,lane+1u); h=mix(h,a->checkpoint[lane]); h=mix(h,a->watermark[lane]); h=mix(h,(unsigned int)(a->value[lane]&0xffff)); } return h; }
static void fold(A* a,const R* rows,unsigned int count){ for(unsigned int i=0;i<count;++i) absorb(a,&rows[i]); }
int main(void){ const R shard0[]={{0u,0u,3u,2u,4},{0u,1u,4u,1u,5},{0u,2u,2u,3u,7},{0u,0u,6u,5u,8}}; const R shard1[]={{1u,3u,3u,2u,6},{1u,1u,6u,4u,3},{1u,4u,2u,5u,2},{1u,3u,7u,6u,9}}; const R shard2[]={{2u,2u,4u,4u,1},{2u,0u,6u,5u,-2},{2u,4u,5u,4u,4},{2u,2u,8u,7u,6}}; const R shard3[]={{3u,1u,6u,4u,1},{3u,4u,5u,6u,5},{3u,3u,7u,6u,-3},{3u,4u,8u,7u,7}}; A direct,permuted,collapsed; clear(&direct); fold(&direct,shard0,4u); fold(&direct,shard1,4u); fold(&direct,shard2,4u); fold(&direct,shard3,4u); clear(&permuted); fold(&permuted,shard2,4u); fold(&permuted,shard0,4u); fold(&permuted,shard3,4u); fold(&permuted,shard1,4u); clear(&collapsed); for(unsigned int lane=0u; lane<5u; ++lane){ int merged=0,saw=0; unsigned int checkpoint=0u,watermark=0u; const R* groups[]={shard0,shard1,shard2,shard3}; for(unsigned int g=0u; g<4u; ++g){ for(unsigned int i=0u; i<4u; ++i){ const R* row=&groups[g][i]; if(row->lane%5u!=lane) continue; if(row->checkpoint<checkpoint) continue; if(row->checkpoint>checkpoint){ checkpoint=row->checkpoint; watermark=row->watermark; merged=row->delta; saw=1; continue; } if(row->watermark>watermark){ watermark=row->watermark; merged=row->delta; saw=1; } else if(row->watermark==watermark){ merged+=row->delta; saw=1; } } } if(saw){ R row={lane,lane,checkpoint,watermark,merged}; absorb(&collapsed,&row); } } { unsigned int sd=sig(&direct), sp=sig(&permuted), sc=sig(&collapsed); printf("%u %u %u %u\n", sd, sp, sc, (sd==sp && sd==sc)?1u:0u); } return 0; }
